version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: gigsource-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gigsource_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: gigsource-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console UI
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_gigsource:/data
    healthcheck:
      test: ["CMD-SHELL", "mc admin info minio"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gigsource-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_gigsource:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: gigsource-general-api
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   restart: unless-stopped



volumes:
  postgres_data:
  minio_data_gigsource:
  rabbitmq_data_gigsource:
