// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"

	mock "github.com/stretchr/testify/mock"
)

// ActivityLogRepo is an autogenerated mock type for the ActivityLogRepo type
type ActivityLogRepo struct {
	mock.Mock
}

type ActivityLogRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityLogRepo) EXPECT() *ActivityLogRepo_Expecter {
	return &ActivityLogRepo_Expecter{mock: &_m.Mock}
}

// CreateLogActivity provides a mock function with given fields: ctx, model
func (_m *ActivityLogRepo) CreateLogActivity(ctx context.Context, model *gorm_model.LogActivity) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm_model.LogActivity) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActivityLogRepo_CreateLogActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLogActivity'
type ActivityLogRepo_CreateLogActivity_Call struct {
	*mock.Call
}

// CreateLogActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - model *gorm_model.LogActivity
func (_e *ActivityLogRepo_Expecter) CreateLogActivity(ctx interface{}, model interface{}) *ActivityLogRepo_CreateLogActivity_Call {
	return &ActivityLogRepo_CreateLogActivity_Call{Call: _e.mock.On("CreateLogActivity", ctx, model)}
}

func (_c *ActivityLogRepo_CreateLogActivity_Call) Run(run func(ctx context.Context, model *gorm_model.LogActivity)) *ActivityLogRepo_CreateLogActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm_model.LogActivity))
	})
	return _c
}

func (_c *ActivityLogRepo_CreateLogActivity_Call) Return(_a0 error) *ActivityLogRepo_CreateLogActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ActivityLogRepo_CreateLogActivity_Call) RunAndReturn(run func(context.Context, *gorm_model.LogActivity) error) *ActivityLogRepo_CreateLogActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityLogRepo creates a new instance of ActivityLogRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityLogRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityLogRepo {
	mock := &ActivityLogRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
