// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// AIChatAppUsecase is an autogenerated mock type for the AIChatAppUsecase type
type AIChatAppUsecase struct {
	mock.Mock
}

type AIChatAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *AIChatAppUsecase) EXPECT() *AIChatAppUsecase_Expecter {
	return &AIChatAppUsecase_Expecter{mock: &_m.Mock}
}

// CreateChat provides a mock function with given fields: ctx, adminID, firstQuery
func (_m *AIChatAppUsecase) CreateChat(ctx context.Context, adminID string, firstQuery string) response.Base {
	ret := _m.Called(ctx, adminID, firstQuery)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string) response.Base); ok {
		r0 = rf(ctx, adminID, firstQuery)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// AIChatAppUsecase_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type AIChatAppUsecase_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - firstQuery string
func (_e *AIChatAppUsecase_Expecter) CreateChat(ctx interface{}, adminID interface{}, firstQuery interface{}) *AIChatAppUsecase_CreateChat_Call {
	return &AIChatAppUsecase_CreateChat_Call{Call: _e.mock.On("CreateChat", ctx, adminID, firstQuery)}
}

func (_c *AIChatAppUsecase_CreateChat_Call) Run(run func(ctx context.Context, adminID string, firstQuery string)) *AIChatAppUsecase_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AIChatAppUsecase_CreateChat_Call) Return(_a0 response.Base) *AIChatAppUsecase_CreateChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AIChatAppUsecase_CreateChat_Call) RunAndReturn(run func(context.Context, string, string) response.Base) *AIChatAppUsecase_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChat provides a mock function with given fields: ctx, adminID, chatID
func (_m *AIChatAppUsecase) DeleteChat(ctx context.Context, adminID string, chatID string) response.Base {
	ret := _m.Called(ctx, adminID, chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChat")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string) response.Base); ok {
		r0 = rf(ctx, adminID, chatID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// AIChatAppUsecase_DeleteChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChat'
type AIChatAppUsecase_DeleteChat_Call struct {
	*mock.Call
}

// DeleteChat is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - chatID string
func (_e *AIChatAppUsecase_Expecter) DeleteChat(ctx interface{}, adminID interface{}, chatID interface{}) *AIChatAppUsecase_DeleteChat_Call {
	return &AIChatAppUsecase_DeleteChat_Call{Call: _e.mock.On("DeleteChat", ctx, adminID, chatID)}
}

func (_c *AIChatAppUsecase_DeleteChat_Call) Run(run func(ctx context.Context, adminID string, chatID string)) *AIChatAppUsecase_DeleteChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AIChatAppUsecase_DeleteChat_Call) Return(_a0 response.Base) *AIChatAppUsecase_DeleteChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AIChatAppUsecase_DeleteChat_Call) RunAndReturn(run func(context.Context, string, string) response.Base) *AIChatAppUsecase_DeleteChat_Call {
	_c.Call.Return(run)
	return _c
}

// FetchChatMessages provides a mock function with given fields: ctx, adminID, chatID
func (_m *AIChatAppUsecase) FetchChatMessages(ctx context.Context, adminID string, chatID string) response.Base {
	ret := _m.Called(ctx, adminID, chatID)

	if len(ret) == 0 {
		panic("no return value specified for FetchChatMessages")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string) response.Base); ok {
		r0 = rf(ctx, adminID, chatID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// AIChatAppUsecase_FetchChatMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchChatMessages'
type AIChatAppUsecase_FetchChatMessages_Call struct {
	*mock.Call
}

// FetchChatMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - chatID string
func (_e *AIChatAppUsecase_Expecter) FetchChatMessages(ctx interface{}, adminID interface{}, chatID interface{}) *AIChatAppUsecase_FetchChatMessages_Call {
	return &AIChatAppUsecase_FetchChatMessages_Call{Call: _e.mock.On("FetchChatMessages", ctx, adminID, chatID)}
}

func (_c *AIChatAppUsecase_FetchChatMessages_Call) Run(run func(ctx context.Context, adminID string, chatID string)) *AIChatAppUsecase_FetchChatMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AIChatAppUsecase_FetchChatMessages_Call) Return(_a0 response.Base) *AIChatAppUsecase_FetchChatMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AIChatAppUsecase_FetchChatMessages_Call) RunAndReturn(run func(context.Context, string, string) response.Base) *AIChatAppUsecase_FetchChatMessages_Call {
	_c.Call.Return(run)
	return _c
}

// FetchMyChats provides a mock function with given fields: ctx, adminID
func (_m *AIChatAppUsecase) FetchMyChats(ctx context.Context, adminID string) response.Base {
	ret := _m.Called(ctx, adminID)

	if len(ret) == 0 {
		panic("no return value specified for FetchMyChats")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, adminID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// AIChatAppUsecase_FetchMyChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMyChats'
type AIChatAppUsecase_FetchMyChats_Call struct {
	*mock.Call
}

// FetchMyChats is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
func (_e *AIChatAppUsecase_Expecter) FetchMyChats(ctx interface{}, adminID interface{}) *AIChatAppUsecase_FetchMyChats_Call {
	return &AIChatAppUsecase_FetchMyChats_Call{Call: _e.mock.On("FetchMyChats", ctx, adminID)}
}

func (_c *AIChatAppUsecase_FetchMyChats_Call) Run(run func(ctx context.Context, adminID string)) *AIChatAppUsecase_FetchMyChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AIChatAppUsecase_FetchMyChats_Call) Return(_a0 response.Base) *AIChatAppUsecase_FetchMyChats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AIChatAppUsecase_FetchMyChats_Call) RunAndReturn(run func(context.Context, string) response.Base) *AIChatAppUsecase_FetchMyChats_Call {
	_c.Call.Return(run)
	return _c
}

// StoreChatMessage provides a mock function with given fields: ctx, adminID, chatID, role, content, isLast
func (_m *AIChatAppUsecase) StoreChatMessage(ctx context.Context, adminID string, chatID string, role string, content string, isLast bool) response.Base {
	ret := _m.Called(ctx, adminID, chatID, role, content, isLast)

	if len(ret) == 0 {
		panic("no return value specified for StoreChatMessage")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, bool) response.Base); ok {
		r0 = rf(ctx, adminID, chatID, role, content, isLast)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// AIChatAppUsecase_StoreChatMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreChatMessage'
type AIChatAppUsecase_StoreChatMessage_Call struct {
	*mock.Call
}

// StoreChatMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - chatID string
//   - role string
//   - content string
//   - isLast bool
func (_e *AIChatAppUsecase_Expecter) StoreChatMessage(ctx interface{}, adminID interface{}, chatID interface{}, role interface{}, content interface{}, isLast interface{}) *AIChatAppUsecase_StoreChatMessage_Call {
	return &AIChatAppUsecase_StoreChatMessage_Call{Call: _e.mock.On("StoreChatMessage", ctx, adminID, chatID, role, content, isLast)}
}

func (_c *AIChatAppUsecase_StoreChatMessage_Call) Run(run func(ctx context.Context, adminID string, chatID string, role string, content string, isLast bool)) *AIChatAppUsecase_StoreChatMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(bool))
	})
	return _c
}

func (_c *AIChatAppUsecase_StoreChatMessage_Call) Return(_a0 response.Base) *AIChatAppUsecase_StoreChatMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AIChatAppUsecase_StoreChatMessage_Call) RunAndReturn(run func(context.Context, string, string, string, string, bool) response.Base) *AIChatAppUsecase_StoreChatMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewAIChatAppUsecase creates a new instance of AIChatAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIChatAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIChatAppUsecase {
	mock := &AIChatAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
