// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"
	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// BookmarkAppUsecase is an autogenerated mock type for the BookmarkAppUsecase type
type BookmarkAppUsecase struct {
	mock.Mock
}

type BookmarkAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *BookmarkAppUsecase) EXPECT() *BookmarkAppUsecase_Expecter {
	return &BookmarkAppUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, adminID, req
func (_m *BookmarkAppUsecase) Create(ctx context.Context, adminID string, req request_model.CreateBookmarkRequest) response.Base {
	ret := _m.Called(ctx, adminID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.CreateBookmarkRequest) response.Base); ok {
		r0 = rf(ctx, adminID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// BookmarkAppUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BookmarkAppUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - req request_model.CreateBookmarkRequest
func (_e *BookmarkAppUsecase_Expecter) Create(ctx interface{}, adminID interface{}, req interface{}) *BookmarkAppUsecase_Create_Call {
	return &BookmarkAppUsecase_Create_Call{Call: _e.mock.On("Create", ctx, adminID, req)}
}

func (_c *BookmarkAppUsecase_Create_Call) Run(run func(ctx context.Context, adminID string, req request_model.CreateBookmarkRequest)) *BookmarkAppUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.CreateBookmarkRequest))
	})
	return _c
}

func (_c *BookmarkAppUsecase_Create_Call) Return(_a0 response.Base) *BookmarkAppUsecase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookmarkAppUsecase_Create_Call) RunAndReturn(run func(context.Context, string, request_model.CreateBookmarkRequest) response.Base) *BookmarkAppUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, adminID, candidateID
func (_m *BookmarkAppUsecase) Delete(ctx context.Context, adminID string, candidateID string) response.Base {
	ret := _m.Called(ctx, adminID, candidateID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string) response.Base); ok {
		r0 = rf(ctx, adminID, candidateID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// BookmarkAppUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BookmarkAppUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - candidateID string
func (_e *BookmarkAppUsecase_Expecter) Delete(ctx interface{}, adminID interface{}, candidateID interface{}) *BookmarkAppUsecase_Delete_Call {
	return &BookmarkAppUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, adminID, candidateID)}
}

func (_c *BookmarkAppUsecase_Delete_Call) Run(run func(ctx context.Context, adminID string, candidateID string)) *BookmarkAppUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *BookmarkAppUsecase_Delete_Call) Return(_a0 response.Base) *BookmarkAppUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookmarkAppUsecase_Delete_Call) RunAndReturn(run func(context.Context, string, string) response.Base) *BookmarkAppUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchByAdmin provides a mock function with given fields: ctx, adminID, page, limit
func (_m *BookmarkAppUsecase) FetchByAdmin(ctx context.Context, adminID string, page int64, limit int64) response.Base {
	ret := _m.Called(ctx, adminID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchByAdmin")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) response.Base); ok {
		r0 = rf(ctx, adminID, page, limit)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// BookmarkAppUsecase_FetchByAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchByAdmin'
type BookmarkAppUsecase_FetchByAdmin_Call struct {
	*mock.Call
}

// FetchByAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - page int64
//   - limit int64
func (_e *BookmarkAppUsecase_Expecter) FetchByAdmin(ctx interface{}, adminID interface{}, page interface{}, limit interface{}) *BookmarkAppUsecase_FetchByAdmin_Call {
	return &BookmarkAppUsecase_FetchByAdmin_Call{Call: _e.mock.On("FetchByAdmin", ctx, adminID, page, limit)}
}

func (_c *BookmarkAppUsecase_FetchByAdmin_Call) Run(run func(ctx context.Context, adminID string, page int64, limit int64)) *BookmarkAppUsecase_FetchByAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *BookmarkAppUsecase_FetchByAdmin_Call) Return(_a0 response.Base) *BookmarkAppUsecase_FetchByAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookmarkAppUsecase_FetchByAdmin_Call) RunAndReturn(run func(context.Context, string, int64, int64) response.Base) *BookmarkAppUsecase_FetchByAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookmarkAppUsecase creates a new instance of BookmarkAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmarkAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookmarkAppUsecase {
	mock := &BookmarkAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
