// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	proto "github.com/adkurnwn/gigsourcehub-general-api/proto"
	mock "github.com/stretchr/testify/mock"
)

// CandidateServiceServer is an autogenerated mock type for the CandidateServiceServer type
type CandidateServiceServer struct {
	mock.Mock
}

type CandidateServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *CandidateServiceServer) EXPECT() *CandidateServiceServer_Expecter {
	return &CandidateServiceServer_Expecter{mock: &_m.Mock}
}

// GetEnrichmentData provides a mock function with given fields: _a0, _a1
func (_m *CandidateServiceServer) GetEnrichmentData(_a0 context.Context, _a1 *proto.EnrichmentRequest) (*proto.EnrichmentResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetEnrichmentData")
	}

	var r0 *proto.EnrichmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.EnrichmentRequest) (*proto.EnrichmentResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.EnrichmentRequest) *proto.EnrichmentResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.EnrichmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.EnrichmentRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CandidateServiceServer_GetEnrichmentData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnrichmentData'
type CandidateServiceServer_GetEnrichmentData_Call struct {
	*mock.Call
}

// GetEnrichmentData is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *proto.EnrichmentRequest
func (_e *CandidateServiceServer_Expecter) GetEnrichmentData(_a0 interface{}, _a1 interface{}) *CandidateServiceServer_GetEnrichmentData_Call {
	return &CandidateServiceServer_GetEnrichmentData_Call{Call: _e.mock.On("GetEnrichmentData", _a0, _a1)}
}

func (_c *CandidateServiceServer_GetEnrichmentData_Call) Run(run func(_a0 context.Context, _a1 *proto.EnrichmentRequest)) *CandidateServiceServer_GetEnrichmentData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.EnrichmentRequest))
	})
	return _c
}

func (_c *CandidateServiceServer_GetEnrichmentData_Call) Return(_a0 *proto.EnrichmentResponse, _a1 error) *CandidateServiceServer_GetEnrichmentData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CandidateServiceServer_GetEnrichmentData_Call) RunAndReturn(run func(context.Context, *proto.EnrichmentRequest) (*proto.EnrichmentResponse, error)) *CandidateServiceServer_GetEnrichmentData_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobRoles provides a mock function with given fields: _a0, _a1
func (_m *CandidateServiceServer) GetJobRoles(_a0 context.Context, _a1 *proto.GetJobRolesRequest) (*proto.GetJobRolesResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetJobRoles")
	}

	var r0 *proto.GetJobRolesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetJobRolesRequest) (*proto.GetJobRolesResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetJobRolesRequest) *proto.GetJobRolesResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetJobRolesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetJobRolesRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CandidateServiceServer_GetJobRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobRoles'
type CandidateServiceServer_GetJobRoles_Call struct {
	*mock.Call
}

// GetJobRoles is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *proto.GetJobRolesRequest
func (_e *CandidateServiceServer_Expecter) GetJobRoles(_a0 interface{}, _a1 interface{}) *CandidateServiceServer_GetJobRoles_Call {
	return &CandidateServiceServer_GetJobRoles_Call{Call: _e.mock.On("GetJobRoles", _a0, _a1)}
}

func (_c *CandidateServiceServer_GetJobRoles_Call) Run(run func(_a0 context.Context, _a1 *proto.GetJobRolesRequest)) *CandidateServiceServer_GetJobRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.GetJobRolesRequest))
	})
	return _c
}

func (_c *CandidateServiceServer_GetJobRoles_Call) Return(_a0 *proto.GetJobRolesResponse, _a1 error) *CandidateServiceServer_GetJobRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CandidateServiceServer_GetJobRoles_Call) RunAndReturn(run func(context.Context, *proto.GetJobRolesRequest) (*proto.GetJobRolesResponse, error)) *CandidateServiceServer_GetJobRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetSectors provides a mock function with given fields: _a0, _a1
func (_m *CandidateServiceServer) GetSectors(_a0 context.Context, _a1 *proto.GetSectorsRequest) (*proto.GetSectorsResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetSectors")
	}

	var r0 *proto.GetSectorsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSectorsRequest) (*proto.GetSectorsResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSectorsRequest) *proto.GetSectorsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetSectorsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetSectorsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CandidateServiceServer_GetSectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSectors'
type CandidateServiceServer_GetSectors_Call struct {
	*mock.Call
}

// GetSectors is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *proto.GetSectorsRequest
func (_e *CandidateServiceServer_Expecter) GetSectors(_a0 interface{}, _a1 interface{}) *CandidateServiceServer_GetSectors_Call {
	return &CandidateServiceServer_GetSectors_Call{Call: _e.mock.On("GetSectors", _a0, _a1)}
}

func (_c *CandidateServiceServer_GetSectors_Call) Run(run func(_a0 context.Context, _a1 *proto.GetSectorsRequest)) *CandidateServiceServer_GetSectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.GetSectorsRequest))
	})
	return _c
}

func (_c *CandidateServiceServer_GetSectors_Call) Return(_a0 *proto.GetSectorsResponse, _a1 error) *CandidateServiceServer_GetSectors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CandidateServiceServer_GetSectors_Call) RunAndReturn(run func(context.Context, *proto.GetSectorsRequest) (*proto.GetSectorsResponse, error)) *CandidateServiceServer_GetSectors_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCVProgress provides a mock function with given fields: _a0, _a1
func (_m *CandidateServiceServer) UpdateCVProgress(_a0 context.Context, _a1 *proto.UpdateCVProgressRequest) (*proto.UpdateCVProgressResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCVProgress")
	}

	var r0 *proto.UpdateCVProgressResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateCVProgressRequest) (*proto.UpdateCVProgressResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateCVProgressRequest) *proto.UpdateCVProgressResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UpdateCVProgressResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateCVProgressRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CandidateServiceServer_UpdateCVProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCVProgress'
type CandidateServiceServer_UpdateCVProgress_Call struct {
	*mock.Call
}

// UpdateCVProgress is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *proto.UpdateCVProgressRequest
func (_e *CandidateServiceServer_Expecter) UpdateCVProgress(_a0 interface{}, _a1 interface{}) *CandidateServiceServer_UpdateCVProgress_Call {
	return &CandidateServiceServer_UpdateCVProgress_Call{Call: _e.mock.On("UpdateCVProgress", _a0, _a1)}
}

func (_c *CandidateServiceServer_UpdateCVProgress_Call) Run(run func(_a0 context.Context, _a1 *proto.UpdateCVProgressRequest)) *CandidateServiceServer_UpdateCVProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.UpdateCVProgressRequest))
	})
	return _c
}

func (_c *CandidateServiceServer_UpdateCVProgress_Call) Return(_a0 *proto.UpdateCVProgressResponse, _a1 error) *CandidateServiceServer_UpdateCVProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CandidateServiceServer_UpdateCVProgress_Call) RunAndReturn(run func(context.Context, *proto.UpdateCVProgressRequest) (*proto.UpdateCVProgressResponse, error)) *CandidateServiceServer_UpdateCVProgress_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedCandidateServiceServer provides a mock function with no fields
func (_m *CandidateServiceServer) mustEmbedUnimplementedCandidateServiceServer() {
	_m.Called()
}

// CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedCandidateServiceServer'
type CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedCandidateServiceServer is a helper method to define mock.On call
func (_e *CandidateServiceServer_Expecter) mustEmbedUnimplementedCandidateServiceServer() *CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call {
	return &CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedCandidateServiceServer")}
}

func (_c *CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call) Run(run func()) *CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call) Return() *CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call) RunAndReturn(run func()) *CandidateServiceServer_mustEmbedUnimplementedCandidateServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewCandidateServiceServer creates a new instance of CandidateServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCandidateServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CandidateServiceServer {
	mock := &CandidateServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
