// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	proto "github.com/adkurnwn/gigsourcehub-general-api/proto"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// CandidateServiceClient is an autogenerated mock type for the CandidateServiceClient type
type CandidateServiceClient struct {
	mock.Mock
}

type CandidateServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CandidateServiceClient) EXPECT() *CandidateServiceClient_Expecter {
	return &CandidateServiceClient_Expecter{mock: &_m.Mock}
}

// GetEnrichmentData provides a mock function with given fields: ctx, in, opts
func (_m *CandidateServiceClient) GetEnrichmentData(ctx context.Context, in *proto.EnrichmentRequest, opts ...grpc.CallOption) (*proto.EnrichmentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetEnrichmentData")
	}

	var r0 *proto.EnrichmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.EnrichmentRequest, ...grpc.CallOption) (*proto.EnrichmentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.EnrichmentRequest, ...grpc.CallOption) *proto.EnrichmentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.EnrichmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.EnrichmentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CandidateServiceClient_GetEnrichmentData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnrichmentData'
type CandidateServiceClient_GetEnrichmentData_Call struct {
	*mock.Call
}

// GetEnrichmentData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.EnrichmentRequest
//   - opts ...grpc.CallOption
func (_e *CandidateServiceClient_Expecter) GetEnrichmentData(ctx interface{}, in interface{}, opts ...interface{}) *CandidateServiceClient_GetEnrichmentData_Call {
	return &CandidateServiceClient_GetEnrichmentData_Call{Call: _e.mock.On("GetEnrichmentData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CandidateServiceClient_GetEnrichmentData_Call) Run(run func(ctx context.Context, in *proto.EnrichmentRequest, opts ...grpc.CallOption)) *CandidateServiceClient_GetEnrichmentData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.EnrichmentRequest), variadicArgs...)
	})
	return _c
}

func (_c *CandidateServiceClient_GetEnrichmentData_Call) Return(_a0 *proto.EnrichmentResponse, _a1 error) *CandidateServiceClient_GetEnrichmentData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CandidateServiceClient_GetEnrichmentData_Call) RunAndReturn(run func(context.Context, *proto.EnrichmentRequest, ...grpc.CallOption) (*proto.EnrichmentResponse, error)) *CandidateServiceClient_GetEnrichmentData_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobRoles provides a mock function with given fields: ctx, in, opts
func (_m *CandidateServiceClient) GetJobRoles(ctx context.Context, in *proto.GetJobRolesRequest, opts ...grpc.CallOption) (*proto.GetJobRolesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetJobRoles")
	}

	var r0 *proto.GetJobRolesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetJobRolesRequest, ...grpc.CallOption) (*proto.GetJobRolesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetJobRolesRequest, ...grpc.CallOption) *proto.GetJobRolesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetJobRolesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetJobRolesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CandidateServiceClient_GetJobRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobRoles'
type CandidateServiceClient_GetJobRoles_Call struct {
	*mock.Call
}

// GetJobRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetJobRolesRequest
//   - opts ...grpc.CallOption
func (_e *CandidateServiceClient_Expecter) GetJobRoles(ctx interface{}, in interface{}, opts ...interface{}) *CandidateServiceClient_GetJobRoles_Call {
	return &CandidateServiceClient_GetJobRoles_Call{Call: _e.mock.On("GetJobRoles",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CandidateServiceClient_GetJobRoles_Call) Run(run func(ctx context.Context, in *proto.GetJobRolesRequest, opts ...grpc.CallOption)) *CandidateServiceClient_GetJobRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetJobRolesRequest), variadicArgs...)
	})
	return _c
}

func (_c *CandidateServiceClient_GetJobRoles_Call) Return(_a0 *proto.GetJobRolesResponse, _a1 error) *CandidateServiceClient_GetJobRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CandidateServiceClient_GetJobRoles_Call) RunAndReturn(run func(context.Context, *proto.GetJobRolesRequest, ...grpc.CallOption) (*proto.GetJobRolesResponse, error)) *CandidateServiceClient_GetJobRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetSectors provides a mock function with given fields: ctx, in, opts
func (_m *CandidateServiceClient) GetSectors(ctx context.Context, in *proto.GetSectorsRequest, opts ...grpc.CallOption) (*proto.GetSectorsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSectors")
	}

	var r0 *proto.GetSectorsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSectorsRequest, ...grpc.CallOption) (*proto.GetSectorsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSectorsRequest, ...grpc.CallOption) *proto.GetSectorsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetSectorsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetSectorsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CandidateServiceClient_GetSectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSectors'
type CandidateServiceClient_GetSectors_Call struct {
	*mock.Call
}

// GetSectors is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetSectorsRequest
//   - opts ...grpc.CallOption
func (_e *CandidateServiceClient_Expecter) GetSectors(ctx interface{}, in interface{}, opts ...interface{}) *CandidateServiceClient_GetSectors_Call {
	return &CandidateServiceClient_GetSectors_Call{Call: _e.mock.On("GetSectors",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CandidateServiceClient_GetSectors_Call) Run(run func(ctx context.Context, in *proto.GetSectorsRequest, opts ...grpc.CallOption)) *CandidateServiceClient_GetSectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetSectorsRequest), variadicArgs...)
	})
	return _c
}

func (_c *CandidateServiceClient_GetSectors_Call) Return(_a0 *proto.GetSectorsResponse, _a1 error) *CandidateServiceClient_GetSectors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CandidateServiceClient_GetSectors_Call) RunAndReturn(run func(context.Context, *proto.GetSectorsRequest, ...grpc.CallOption) (*proto.GetSectorsResponse, error)) *CandidateServiceClient_GetSectors_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCVProgress provides a mock function with given fields: ctx, in, opts
func (_m *CandidateServiceClient) UpdateCVProgress(ctx context.Context, in *proto.UpdateCVProgressRequest, opts ...grpc.CallOption) (*proto.UpdateCVProgressResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCVProgress")
	}

	var r0 *proto.UpdateCVProgressResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateCVProgressRequest, ...grpc.CallOption) (*proto.UpdateCVProgressResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateCVProgressRequest, ...grpc.CallOption) *proto.UpdateCVProgressResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UpdateCVProgressResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateCVProgressRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CandidateServiceClient_UpdateCVProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCVProgress'
type CandidateServiceClient_UpdateCVProgress_Call struct {
	*mock.Call
}

// UpdateCVProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UpdateCVProgressRequest
//   - opts ...grpc.CallOption
func (_e *CandidateServiceClient_Expecter) UpdateCVProgress(ctx interface{}, in interface{}, opts ...interface{}) *CandidateServiceClient_UpdateCVProgress_Call {
	return &CandidateServiceClient_UpdateCVProgress_Call{Call: _e.mock.On("UpdateCVProgress",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CandidateServiceClient_UpdateCVProgress_Call) Run(run func(ctx context.Context, in *proto.UpdateCVProgressRequest, opts ...grpc.CallOption)) *CandidateServiceClient_UpdateCVProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UpdateCVProgressRequest), variadicArgs...)
	})
	return _c
}

func (_c *CandidateServiceClient_UpdateCVProgress_Call) Return(_a0 *proto.UpdateCVProgressResponse, _a1 error) *CandidateServiceClient_UpdateCVProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CandidateServiceClient_UpdateCVProgress_Call) RunAndReturn(run func(context.Context, *proto.UpdateCVProgressRequest, ...grpc.CallOption) (*proto.UpdateCVProgressResponse, error)) *CandidateServiceClient_UpdateCVProgress_Call {
	_c.Call.Return(run)
	return _c
}

// NewCandidateServiceClient creates a new instance of CandidateServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCandidateServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CandidateServiceClient {
	mock := &CandidateServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
