// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	multipart "mime/multipart"

	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"
	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// CareerDepartmentAppUsecase is an autogenerated mock type for the CareerDepartmentAppUsecase type
type CareerDepartmentAppUsecase struct {
	mock.Mock
}

type CareerDepartmentAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CareerDepartmentAppUsecase) EXPECT() *CareerDepartmentAppUsecase_Expecter {
	return &CareerDepartmentAppUsecase_Expecter{mock: &_m.Mock}
}

// ApproveRequest provides a mock function with given fields: ctx, superadminID, approvalID
func (_m *CareerDepartmentAppUsecase) ApproveRequest(ctx context.Context, superadminID string, approvalID string) response.Base {
	ret := _m.Called(ctx, superadminID, approvalID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveRequest")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string) response.Base); ok {
		r0 = rf(ctx, superadminID, approvalID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_ApproveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveRequest'
type CareerDepartmentAppUsecase_ApproveRequest_Call struct {
	*mock.Call
}

// ApproveRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - superadminID string
//   - approvalID string
func (_e *CareerDepartmentAppUsecase_Expecter) ApproveRequest(ctx interface{}, superadminID interface{}, approvalID interface{}) *CareerDepartmentAppUsecase_ApproveRequest_Call {
	return &CareerDepartmentAppUsecase_ApproveRequest_Call{Call: _e.mock.On("ApproveRequest", ctx, superadminID, approvalID)}
}

func (_c *CareerDepartmentAppUsecase_ApproveRequest_Call) Run(run func(ctx context.Context, superadminID string, approvalID string)) *CareerDepartmentAppUsecase_ApproveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_ApproveRequest_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_ApproveRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_ApproveRequest_Call) RunAndReturn(run func(context.Context, string, string) response.Base) *CareerDepartmentAppUsecase_ApproveRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, adminID, req
func (_m *CareerDepartmentAppUsecase) Create(ctx context.Context, adminID string, req request_model.CreateCareerDepartmentRequest) response.Base {
	ret := _m.Called(ctx, adminID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.CreateCareerDepartmentRequest) response.Base); ok {
		r0 = rf(ctx, adminID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CareerDepartmentAppUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - req request_model.CreateCareerDepartmentRequest
func (_e *CareerDepartmentAppUsecase_Expecter) Create(ctx interface{}, adminID interface{}, req interface{}) *CareerDepartmentAppUsecase_Create_Call {
	return &CareerDepartmentAppUsecase_Create_Call{Call: _e.mock.On("Create", ctx, adminID, req)}
}

func (_c *CareerDepartmentAppUsecase_Create_Call) Run(run func(ctx context.Context, adminID string, req request_model.CreateCareerDepartmentRequest)) *CareerDepartmentAppUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.CreateCareerDepartmentRequest))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_Create_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_Create_Call) RunAndReturn(run func(context.Context, string, request_model.CreateCareerDepartmentRequest) response.Base) *CareerDepartmentAppUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CareerDepartmentAppUsecase) Delete(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CareerDepartmentAppUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CareerDepartmentAppUsecase_Expecter) Delete(ctx interface{}, id interface{}) *CareerDepartmentAppUsecase_Delete_Call {
	return &CareerDepartmentAppUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CareerDepartmentAppUsecase_Delete_Call) Run(run func(ctx context.Context, id string)) *CareerDepartmentAppUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_Delete_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_Delete_Call) RunAndReturn(run func(context.Context, string) response.Base) *CareerDepartmentAppUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAll provides a mock function with given fields: ctx, page, limit, search
func (_m *CareerDepartmentAppUsecase) FetchAll(ctx context.Context, page int64, limit int64, search *string) response.Base {
	ret := _m.Called(ctx, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *string) response.Base); ok {
		r0 = rf(ctx, page, limit, search)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type CareerDepartmentAppUsecase_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - search *string
func (_e *CareerDepartmentAppUsecase_Expecter) FetchAll(ctx interface{}, page interface{}, limit interface{}, search interface{}) *CareerDepartmentAppUsecase_FetchAll_Call {
	return &CareerDepartmentAppUsecase_FetchAll_Call{Call: _e.mock.On("FetchAll", ctx, page, limit, search)}
}

func (_c *CareerDepartmentAppUsecase_FetchAll_Call) Run(run func(ctx context.Context, page int64, limit int64, search *string)) *CareerDepartmentAppUsecase_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(*string))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchAll_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_FetchAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchAll_Call) RunAndReturn(run func(context.Context, int64, int64, *string) response.Base) *CareerDepartmentAppUsecase_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// FetchApprovals provides a mock function with given fields: ctx, page, limit
func (_m *CareerDepartmentAppUsecase) FetchApprovals(ctx context.Context, page int64, limit int64) response.Base {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchApprovals")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) response.Base); ok {
		r0 = rf(ctx, page, limit)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_FetchApprovals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchApprovals'
type CareerDepartmentAppUsecase_FetchApprovals_Call struct {
	*mock.Call
}

// FetchApprovals is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
func (_e *CareerDepartmentAppUsecase_Expecter) FetchApprovals(ctx interface{}, page interface{}, limit interface{}) *CareerDepartmentAppUsecase_FetchApprovals_Call {
	return &CareerDepartmentAppUsecase_FetchApprovals_Call{Call: _e.mock.On("FetchApprovals", ctx, page, limit)}
}

func (_c *CareerDepartmentAppUsecase_FetchApprovals_Call) Run(run func(ctx context.Context, page int64, limit int64)) *CareerDepartmentAppUsecase_FetchApprovals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchApprovals_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_FetchApprovals_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchApprovals_Call) RunAndReturn(run func(context.Context, int64, int64) response.Base) *CareerDepartmentAppUsecase_FetchApprovals_Call {
	_c.Call.Return(run)
	return _c
}

// FetchData provides a mock function with given fields: ctx, id
func (_m *CareerDepartmentAppUsecase) FetchData(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchData")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_FetchData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchData'
type CareerDepartmentAppUsecase_FetchData_Call struct {
	*mock.Call
}

// FetchData is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CareerDepartmentAppUsecase_Expecter) FetchData(ctx interface{}, id interface{}) *CareerDepartmentAppUsecase_FetchData_Call {
	return &CareerDepartmentAppUsecase_FetchData_Call{Call: _e.mock.On("FetchData", ctx, id)}
}

func (_c *CareerDepartmentAppUsecase_FetchData_Call) Run(run func(ctx context.Context, id string)) *CareerDepartmentAppUsecase_FetchData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchData_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_FetchData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchData_Call) RunAndReturn(run func(context.Context, string) response.Base) *CareerDepartmentAppUsecase_FetchData_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPublic provides a mock function with given fields: ctx, page, limit, search
func (_m *CareerDepartmentAppUsecase) FetchPublic(ctx context.Context, page int64, limit int64, search *string) response.Base {
	ret := _m.Called(ctx, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for FetchPublic")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *string) response.Base); ok {
		r0 = rf(ctx, page, limit, search)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_FetchPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPublic'
type CareerDepartmentAppUsecase_FetchPublic_Call struct {
	*mock.Call
}

// FetchPublic is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - search *string
func (_e *CareerDepartmentAppUsecase_Expecter) FetchPublic(ctx interface{}, page interface{}, limit interface{}, search interface{}) *CareerDepartmentAppUsecase_FetchPublic_Call {
	return &CareerDepartmentAppUsecase_FetchPublic_Call{Call: _e.mock.On("FetchPublic", ctx, page, limit, search)}
}

func (_c *CareerDepartmentAppUsecase_FetchPublic_Call) Run(run func(ctx context.Context, page int64, limit int64, search *string)) *CareerDepartmentAppUsecase_FetchPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(*string))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchPublic_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_FetchPublic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchPublic_Call) RunAndReturn(run func(context.Context, int64, int64, *string) response.Base) *CareerDepartmentAppUsecase_FetchPublic_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPublicByID provides a mock function with given fields: ctx, id
func (_m *CareerDepartmentAppUsecase) FetchPublicByID(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchPublicByID")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_FetchPublicByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPublicByID'
type CareerDepartmentAppUsecase_FetchPublicByID_Call struct {
	*mock.Call
}

// FetchPublicByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CareerDepartmentAppUsecase_Expecter) FetchPublicByID(ctx interface{}, id interface{}) *CareerDepartmentAppUsecase_FetchPublicByID_Call {
	return &CareerDepartmentAppUsecase_FetchPublicByID_Call{Call: _e.mock.On("FetchPublicByID", ctx, id)}
}

func (_c *CareerDepartmentAppUsecase_FetchPublicByID_Call) Run(run func(ctx context.Context, id string)) *CareerDepartmentAppUsecase_FetchPublicByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchPublicByID_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_FetchPublicByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_FetchPublicByID_Call) RunAndReturn(run func(context.Context, string) response.Base) *CareerDepartmentAppUsecase_FetchPublicByID_Call {
	_c.Call.Return(run)
	return _c
}

// RejectRequest provides a mock function with given fields: ctx, superadminID, approvalID, req
func (_m *CareerDepartmentAppUsecase) RejectRequest(ctx context.Context, superadminID string, approvalID string, req request_model.ReviewApprovalRequest) response.Base {
	ret := _m.Called(ctx, superadminID, approvalID, req)

	if len(ret) == 0 {
		panic("no return value specified for RejectRequest")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request_model.ReviewApprovalRequest) response.Base); ok {
		r0 = rf(ctx, superadminID, approvalID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_RejectRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectRequest'
type CareerDepartmentAppUsecase_RejectRequest_Call struct {
	*mock.Call
}

// RejectRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - superadminID string
//   - approvalID string
//   - req request_model.ReviewApprovalRequest
func (_e *CareerDepartmentAppUsecase_Expecter) RejectRequest(ctx interface{}, superadminID interface{}, approvalID interface{}, req interface{}) *CareerDepartmentAppUsecase_RejectRequest_Call {
	return &CareerDepartmentAppUsecase_RejectRequest_Call{Call: _e.mock.On("RejectRequest", ctx, superadminID, approvalID, req)}
}

func (_c *CareerDepartmentAppUsecase_RejectRequest_Call) Run(run func(ctx context.Context, superadminID string, approvalID string, req request_model.ReviewApprovalRequest)) *CareerDepartmentAppUsecase_RejectRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request_model.ReviewApprovalRequest))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_RejectRequest_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_RejectRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_RejectRequest_Call) RunAndReturn(run func(context.Context, string, string, request_model.ReviewApprovalRequest) response.Base) *CareerDepartmentAppUsecase_RejectRequest_Call {
	_c.Call.Return(run)
	return _c
}

// TakedownRequest provides a mock function with given fields: ctx, superadminID, approvalID
func (_m *CareerDepartmentAppUsecase) TakedownRequest(ctx context.Context, superadminID string, approvalID string) response.Base {
	ret := _m.Called(ctx, superadminID, approvalID)

	if len(ret) == 0 {
		panic("no return value specified for TakedownRequest")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string) response.Base); ok {
		r0 = rf(ctx, superadminID, approvalID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_TakedownRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TakedownRequest'
type CareerDepartmentAppUsecase_TakedownRequest_Call struct {
	*mock.Call
}

// TakedownRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - superadminID string
//   - approvalID string
func (_e *CareerDepartmentAppUsecase_Expecter) TakedownRequest(ctx interface{}, superadminID interface{}, approvalID interface{}) *CareerDepartmentAppUsecase_TakedownRequest_Call {
	return &CareerDepartmentAppUsecase_TakedownRequest_Call{Call: _e.mock.On("TakedownRequest", ctx, superadminID, approvalID)}
}

func (_c *CareerDepartmentAppUsecase_TakedownRequest_Call) Run(run func(ctx context.Context, superadminID string, approvalID string)) *CareerDepartmentAppUsecase_TakedownRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_TakedownRequest_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_TakedownRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_TakedownRequest_Call) RunAndReturn(run func(context.Context, string, string) response.Base) *CareerDepartmentAppUsecase_TakedownRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, adminID, id, req
func (_m *CareerDepartmentAppUsecase) Update(ctx context.Context, adminID string, id string, req request_model.UpdateCareerDepartmentRequest) response.Base {
	ret := _m.Called(ctx, adminID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request_model.UpdateCareerDepartmentRequest) response.Base); ok {
		r0 = rf(ctx, adminID, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CareerDepartmentAppUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - id string
//   - req request_model.UpdateCareerDepartmentRequest
func (_e *CareerDepartmentAppUsecase_Expecter) Update(ctx interface{}, adminID interface{}, id interface{}, req interface{}) *CareerDepartmentAppUsecase_Update_Call {
	return &CareerDepartmentAppUsecase_Update_Call{Call: _e.mock.On("Update", ctx, adminID, id, req)}
}

func (_c *CareerDepartmentAppUsecase_Update_Call) Run(run func(ctx context.Context, adminID string, id string, req request_model.UpdateCareerDepartmentRequest)) *CareerDepartmentAppUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request_model.UpdateCareerDepartmentRequest))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_Update_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_Update_Call) RunAndReturn(run func(context.Context, string, string, request_model.UpdateCareerDepartmentRequest) response.Base) *CareerDepartmentAppUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UploadImage provides a mock function with given fields: ctx, id, file
func (_m *CareerDepartmentAppUsecase) UploadImage(ctx context.Context, id string, file *multipart.FileHeader) response.Base {
	ret := _m.Called(ctx, id, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, *multipart.FileHeader) response.Base); ok {
		r0 = rf(ctx, id, file)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CareerDepartmentAppUsecase_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type CareerDepartmentAppUsecase_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - file *multipart.FileHeader
func (_e *CareerDepartmentAppUsecase_Expecter) UploadImage(ctx interface{}, id interface{}, file interface{}) *CareerDepartmentAppUsecase_UploadImage_Call {
	return &CareerDepartmentAppUsecase_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, id, file)}
}

func (_c *CareerDepartmentAppUsecase_UploadImage_Call) Run(run func(ctx context.Context, id string, file *multipart.FileHeader)) *CareerDepartmentAppUsecase_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*multipart.FileHeader))
	})
	return _c
}

func (_c *CareerDepartmentAppUsecase_UploadImage_Call) Return(_a0 response.Base) *CareerDepartmentAppUsecase_UploadImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CareerDepartmentAppUsecase_UploadImage_Call) RunAndReturn(run func(context.Context, string, *multipart.FileHeader) response.Base) *CareerDepartmentAppUsecase_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewCareerDepartmentAppUsecase creates a new instance of CareerDepartmentAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCareerDepartmentAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CareerDepartmentAppUsecase {
	mock := &CareerDepartmentAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
