// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"
	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// CompanyProfileAppUsecase is an autogenerated mock type for the CompanyProfileAppUsecase type
type CompanyProfileAppUsecase struct {
	mock.Mock
}

type CompanyProfileAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyProfileAppUsecase) EXPECT() *CompanyProfileAppUsecase_Expecter {
	return &CompanyProfileAppUsecase_Expecter{mock: &_m.Mock}
}

// AdminUpdate provides a mock function with given fields: ctx, adminID, req
func (_m *CompanyProfileAppUsecase) AdminUpdate(ctx context.Context, adminID string, req request_model.UpdateCompanyProfileRequest) response.Base {
	ret := _m.Called(ctx, adminID, req)

	if len(ret) == 0 {
		panic("no return value specified for AdminUpdate")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.UpdateCompanyProfileRequest) response.Base); ok {
		r0 = rf(ctx, adminID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CompanyProfileAppUsecase_AdminUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminUpdate'
type CompanyProfileAppUsecase_AdminUpdate_Call struct {
	*mock.Call
}

// AdminUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - req request_model.UpdateCompanyProfileRequest
func (_e *CompanyProfileAppUsecase_Expecter) AdminUpdate(ctx interface{}, adminID interface{}, req interface{}) *CompanyProfileAppUsecase_AdminUpdate_Call {
	return &CompanyProfileAppUsecase_AdminUpdate_Call{Call: _e.mock.On("AdminUpdate", ctx, adminID, req)}
}

func (_c *CompanyProfileAppUsecase_AdminUpdate_Call) Run(run func(ctx context.Context, adminID string, req request_model.UpdateCompanyProfileRequest)) *CompanyProfileAppUsecase_AdminUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.UpdateCompanyProfileRequest))
	})
	return _c
}

func (_c *CompanyProfileAppUsecase_AdminUpdate_Call) Return(_a0 response.Base) *CompanyProfileAppUsecase_AdminUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyProfileAppUsecase_AdminUpdate_Call) RunAndReturn(run func(context.Context, string, request_model.UpdateCompanyProfileRequest) response.Base) *CompanyProfileAppUsecase_AdminUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// ApproveRequest provides a mock function with given fields: ctx, superadminID, approvalID
func (_m *CompanyProfileAppUsecase) ApproveRequest(ctx context.Context, superadminID string, approvalID string) response.Base {
	ret := _m.Called(ctx, superadminID, approvalID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveRequest")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string) response.Base); ok {
		r0 = rf(ctx, superadminID, approvalID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CompanyProfileAppUsecase_ApproveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveRequest'
type CompanyProfileAppUsecase_ApproveRequest_Call struct {
	*mock.Call
}

// ApproveRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - superadminID string
//   - approvalID string
func (_e *CompanyProfileAppUsecase_Expecter) ApproveRequest(ctx interface{}, superadminID interface{}, approvalID interface{}) *CompanyProfileAppUsecase_ApproveRequest_Call {
	return &CompanyProfileAppUsecase_ApproveRequest_Call{Call: _e.mock.On("ApproveRequest", ctx, superadminID, approvalID)}
}

func (_c *CompanyProfileAppUsecase_ApproveRequest_Call) Run(run func(ctx context.Context, superadminID string, approvalID string)) *CompanyProfileAppUsecase_ApproveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CompanyProfileAppUsecase_ApproveRequest_Call) Return(_a0 response.Base) *CompanyProfileAppUsecase_ApproveRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyProfileAppUsecase_ApproveRequest_Call) RunAndReturn(run func(context.Context, string, string) response.Base) *CompanyProfileAppUsecase_ApproveRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CancelPendingApproval provides a mock function with given fields: ctx, approvalID
func (_m *CompanyProfileAppUsecase) CancelPendingApproval(ctx context.Context, approvalID string) response.Base {
	ret := _m.Called(ctx, approvalID)

	if len(ret) == 0 {
		panic("no return value specified for CancelPendingApproval")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, approvalID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CompanyProfileAppUsecase_CancelPendingApproval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPendingApproval'
type CompanyProfileAppUsecase_CancelPendingApproval_Call struct {
	*mock.Call
}

// CancelPendingApproval is a helper method to define mock.On call
//   - ctx context.Context
//   - approvalID string
func (_e *CompanyProfileAppUsecase_Expecter) CancelPendingApproval(ctx interface{}, approvalID interface{}) *CompanyProfileAppUsecase_CancelPendingApproval_Call {
	return &CompanyProfileAppUsecase_CancelPendingApproval_Call{Call: _e.mock.On("CancelPendingApproval", ctx, approvalID)}
}

func (_c *CompanyProfileAppUsecase_CancelPendingApproval_Call) Run(run func(ctx context.Context, approvalID string)) *CompanyProfileAppUsecase_CancelPendingApproval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CompanyProfileAppUsecase_CancelPendingApproval_Call) Return(_a0 response.Base) *CompanyProfileAppUsecase_CancelPendingApproval_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyProfileAppUsecase_CancelPendingApproval_Call) RunAndReturn(run func(context.Context, string) response.Base) *CompanyProfileAppUsecase_CancelPendingApproval_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPendingApprovals provides a mock function with given fields: ctx, page, limit
func (_m *CompanyProfileAppUsecase) FetchPendingApprovals(ctx context.Context, page int64, limit int64) response.Base {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchPendingApprovals")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) response.Base); ok {
		r0 = rf(ctx, page, limit)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CompanyProfileAppUsecase_FetchPendingApprovals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPendingApprovals'
type CompanyProfileAppUsecase_FetchPendingApprovals_Call struct {
	*mock.Call
}

// FetchPendingApprovals is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
func (_e *CompanyProfileAppUsecase_Expecter) FetchPendingApprovals(ctx interface{}, page interface{}, limit interface{}) *CompanyProfileAppUsecase_FetchPendingApprovals_Call {
	return &CompanyProfileAppUsecase_FetchPendingApprovals_Call{Call: _e.mock.On("FetchPendingApprovals", ctx, page, limit)}
}

func (_c *CompanyProfileAppUsecase_FetchPendingApprovals_Call) Run(run func(ctx context.Context, page int64, limit int64)) *CompanyProfileAppUsecase_FetchPendingApprovals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *CompanyProfileAppUsecase_FetchPendingApprovals_Call) Return(_a0 response.Base) *CompanyProfileAppUsecase_FetchPendingApprovals_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyProfileAppUsecase_FetchPendingApprovals_Call) RunAndReturn(run func(context.Context, int64, int64) response.Base) *CompanyProfileAppUsecase_FetchPendingApprovals_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx
func (_m *CompanyProfileAppUsecase) Get(ctx context.Context) response.Base {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context) response.Base); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CompanyProfileAppUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CompanyProfileAppUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CompanyProfileAppUsecase_Expecter) Get(ctx interface{}) *CompanyProfileAppUsecase_Get_Call {
	return &CompanyProfileAppUsecase_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *CompanyProfileAppUsecase_Get_Call) Run(run func(ctx context.Context)) *CompanyProfileAppUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CompanyProfileAppUsecase_Get_Call) Return(_a0 response.Base) *CompanyProfileAppUsecase_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyProfileAppUsecase_Get_Call) RunAndReturn(run func(context.Context) response.Base) *CompanyProfileAppUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublic provides a mock function with given fields: ctx
func (_m *CompanyProfileAppUsecase) GetPublic(ctx context.Context) response.Base {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPublic")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context) response.Base); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CompanyProfileAppUsecase_GetPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublic'
type CompanyProfileAppUsecase_GetPublic_Call struct {
	*mock.Call
}

// GetPublic is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CompanyProfileAppUsecase_Expecter) GetPublic(ctx interface{}) *CompanyProfileAppUsecase_GetPublic_Call {
	return &CompanyProfileAppUsecase_GetPublic_Call{Call: _e.mock.On("GetPublic", ctx)}
}

func (_c *CompanyProfileAppUsecase_GetPublic_Call) Run(run func(ctx context.Context)) *CompanyProfileAppUsecase_GetPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CompanyProfileAppUsecase_GetPublic_Call) Return(_a0 response.Base) *CompanyProfileAppUsecase_GetPublic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyProfileAppUsecase_GetPublic_Call) RunAndReturn(run func(context.Context) response.Base) *CompanyProfileAppUsecase_GetPublic_Call {
	_c.Call.Return(run)
	return _c
}

// RejectRequest provides a mock function with given fields: ctx, superadminID, approvalID, req
func (_m *CompanyProfileAppUsecase) RejectRequest(ctx context.Context, superadminID string, approvalID string, req request_model.ReviewApprovalRequest) response.Base {
	ret := _m.Called(ctx, superadminID, approvalID, req)

	if len(ret) == 0 {
		panic("no return value specified for RejectRequest")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request_model.ReviewApprovalRequest) response.Base); ok {
		r0 = rf(ctx, superadminID, approvalID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CompanyProfileAppUsecase_RejectRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectRequest'
type CompanyProfileAppUsecase_RejectRequest_Call struct {
	*mock.Call
}

// RejectRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - superadminID string
//   - approvalID string
//   - req request_model.ReviewApprovalRequest
func (_e *CompanyProfileAppUsecase_Expecter) RejectRequest(ctx interface{}, superadminID interface{}, approvalID interface{}, req interface{}) *CompanyProfileAppUsecase_RejectRequest_Call {
	return &CompanyProfileAppUsecase_RejectRequest_Call{Call: _e.mock.On("RejectRequest", ctx, superadminID, approvalID, req)}
}

func (_c *CompanyProfileAppUsecase_RejectRequest_Call) Run(run func(ctx context.Context, superadminID string, approvalID string, req request_model.ReviewApprovalRequest)) *CompanyProfileAppUsecase_RejectRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request_model.ReviewApprovalRequest))
	})
	return _c
}

func (_c *CompanyProfileAppUsecase_RejectRequest_Call) Return(_a0 response.Base) *CompanyProfileAppUsecase_RejectRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompanyProfileAppUsecase_RejectRequest_Call) RunAndReturn(run func(context.Context, string, string, request_model.ReviewApprovalRequest) response.Base) *CompanyProfileAppUsecase_RejectRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompanyProfileAppUsecase creates a new instance of CompanyProfileAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyProfileAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyProfileAppUsecase {
	mock := &CompanyProfileAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
