// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
)

// CVUsecase is an autogenerated mock type for the CVUsecase type
type CVUsecase struct {
	mock.Mock
}

type CVUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CVUsecase) EXPECT() *CVUsecase_Expecter {
	return &CVUsecase_Expecter{mock: &_m.Mock}
}

// ConfirmCV provides a mock function with given fields: ctx, userID, editedData
func (_m *CVUsecase) ConfirmCV(ctx context.Context, userID string, editedData map[string]interface{}) response.Base {
	ret := _m.Called(ctx, userID, editedData)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmCV")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) response.Base); ok {
		r0 = rf(ctx, userID, editedData)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CVUsecase_ConfirmCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmCV'
type CVUsecase_ConfirmCV_Call struct {
	*mock.Call
}

// ConfirmCV is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - editedData map[string]interface{}
func (_e *CVUsecase_Expecter) ConfirmCV(ctx interface{}, userID interface{}, editedData interface{}) *CVUsecase_ConfirmCV_Call {
	return &CVUsecase_ConfirmCV_Call{Call: _e.mock.On("ConfirmCV", ctx, userID, editedData)}
}

func (_c *CVUsecase_ConfirmCV_Call) Run(run func(ctx context.Context, userID string, editedData map[string]interface{})) *CVUsecase_ConfirmCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *CVUsecase_ConfirmCV_Call) Return(_a0 response.Base) *CVUsecase_ConfirmCV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CVUsecase_ConfirmCV_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) response.Base) *CVUsecase_ConfirmCV_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCVLink provides a mock function with given fields: ctx, userID
func (_m *CVUsecase) GenerateCVLink(ctx context.Context, userID string) response.Base {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCVLink")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CVUsecase_GenerateCVLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCVLink'
type CVUsecase_GenerateCVLink_Call struct {
	*mock.Call
}

// GenerateCVLink is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CVUsecase_Expecter) GenerateCVLink(ctx interface{}, userID interface{}) *CVUsecase_GenerateCVLink_Call {
	return &CVUsecase_GenerateCVLink_Call{Call: _e.mock.On("GenerateCVLink", ctx, userID)}
}

func (_c *CVUsecase_GenerateCVLink_Call) Run(run func(ctx context.Context, userID string)) *CVUsecase_GenerateCVLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CVUsecase_GenerateCVLink_Call) Return(_a0 response.Base) *CVUsecase_GenerateCVLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CVUsecase_GenerateCVLink_Call) RunAndReturn(run func(context.Context, string) response.Base) *CVUsecase_GenerateCVLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetParsedCV provides a mock function with given fields: ctx, userID
func (_m *CVUsecase) GetParsedCV(ctx context.Context, userID string) response.Base {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetParsedCV")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CVUsecase_GetParsedCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParsedCV'
type CVUsecase_GetParsedCV_Call struct {
	*mock.Call
}

// GetParsedCV is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CVUsecase_Expecter) GetParsedCV(ctx interface{}, userID interface{}) *CVUsecase_GetParsedCV_Call {
	return &CVUsecase_GetParsedCV_Call{Call: _e.mock.On("GetParsedCV", ctx, userID)}
}

func (_c *CVUsecase_GetParsedCV_Call) Run(run func(ctx context.Context, userID string)) *CVUsecase_GetParsedCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CVUsecase_GetParsedCV_Call) Return(_a0 response.Base) *CVUsecase_GetParsedCV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CVUsecase_GetParsedCV_Call) RunAndReturn(run func(context.Context, string) response.Base) *CVUsecase_GetParsedCV_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCV provides a mock function with given fields: ctx, userID, fileHeader, skipParsing
func (_m *CVUsecase) UploadCV(ctx context.Context, userID string, fileHeader *multipart.FileHeader, skipParsing bool) response.Base {
	ret := _m.Called(ctx, userID, fileHeader, skipParsing)

	if len(ret) == 0 {
		panic("no return value specified for UploadCV")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, *multipart.FileHeader, bool) response.Base); ok {
		r0 = rf(ctx, userID, fileHeader, skipParsing)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// CVUsecase_UploadCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCV'
type CVUsecase_UploadCV_Call struct {
	*mock.Call
}

// UploadCV is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - fileHeader *multipart.FileHeader
//   - skipParsing bool
func (_e *CVUsecase_Expecter) UploadCV(ctx interface{}, userID interface{}, fileHeader interface{}, skipParsing interface{}) *CVUsecase_UploadCV_Call {
	return &CVUsecase_UploadCV_Call{Call: _e.mock.On("UploadCV", ctx, userID, fileHeader, skipParsing)}
}

func (_c *CVUsecase_UploadCV_Call) Run(run func(ctx context.Context, userID string, fileHeader *multipart.FileHeader, skipParsing bool)) *CVUsecase_UploadCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*multipart.FileHeader), args[3].(bool))
	})
	return _c
}

func (_c *CVUsecase_UploadCV_Call) Return(_a0 response.Base) *CVUsecase_UploadCV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CVUsecase_UploadCV_Call) RunAndReturn(run func(context.Context, string, *multipart.FileHeader, bool) response.Base) *CVUsecase_UploadCV_Call {
	_c.Call.Return(run)
	return _c
}

// NewCVUsecase creates a new instance of CVUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCVUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CVUsecase {
	mock := &CVUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
