// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// GormRepo is an autogenerated mock type for the GormRepo type
type GormRepo struct {
	mock.Mock
}

type GormRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *GormRepo) EXPECT() *GormRepo_Expecter {
	return &GormRepo_Expecter{mock: &_m.Mock}
}

// CountUser provides a mock function with given fields: ctx, options
func (_m *GormRepo) CountUser(ctx context.Context, options gorm_model.UserFilter) int64 {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for CountUser")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, gorm_model.UserFilter) int64); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GormRepo_CountUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUser'
type GormRepo_CountUser_Call struct {
	*mock.Call
}

// CountUser is a helper method to define mock.On call
//   - ctx context.Context
//   - options gorm_model.UserFilter
func (_e *GormRepo_Expecter) CountUser(ctx interface{}, options interface{}) *GormRepo_CountUser_Call {
	return &GormRepo_CountUser_Call{Call: _e.mock.On("CountUser", ctx, options)}
}

func (_c *GormRepo_CountUser_Call) Run(run func(ctx context.Context, options gorm_model.UserFilter)) *GormRepo_CountUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gorm_model.UserFilter))
	})
	return _c
}

func (_c *GormRepo_CountUser_Call) Return(_a0 int64) *GormRepo_CountUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GormRepo_CountUser_Call) RunAndReturn(run func(context.Context, gorm_model.UserFilter) int64) *GormRepo_CountUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCV provides a mock function with given fields: ctx, cv
func (_m *GormRepo) CreateCV(ctx context.Context, cv *gorm_model.CV) error {
	ret := _m.Called(ctx, cv)

	if len(ret) == 0 {
		panic("no return value specified for CreateCV")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm_model.CV) error); ok {
		r0 = rf(ctx, cv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GormRepo_CreateCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCV'
type GormRepo_CreateCV_Call struct {
	*mock.Call
}

// CreateCV is a helper method to define mock.On call
//   - ctx context.Context
//   - cv *gorm_model.CV
func (_e *GormRepo_Expecter) CreateCV(ctx interface{}, cv interface{}) *GormRepo_CreateCV_Call {
	return &GormRepo_CreateCV_Call{Call: _e.mock.On("CreateCV", ctx, cv)}
}

func (_c *GormRepo_CreateCV_Call) Run(run func(ctx context.Context, cv *gorm_model.CV)) *GormRepo_CreateCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm_model.CV))
	})
	return _c
}

func (_c *GormRepo_CreateCV_Call) Return(_a0 error) *GormRepo_CreateCV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GormRepo_CreateCV_Call) RunAndReturn(run func(context.Context, *gorm_model.CV) error) *GormRepo_CreateCV_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, model
func (_m *GormRepo) CreateUser(ctx context.Context, model *gorm_model.User) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm_model.User) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GormRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type GormRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - model *gorm_model.User
func (_e *GormRepo_Expecter) CreateUser(ctx interface{}, model interface{}) *GormRepo_CreateUser_Call {
	return &GormRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, model)}
}

func (_c *GormRepo_CreateUser_Call) Run(run func(ctx context.Context, model *gorm_model.User)) *GormRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm_model.User))
	})
	return _c
}

func (_c *GormRepo_CreateUser_Call) Return(err error) *GormRepo_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GormRepo_CreateUser_Call) RunAndReturn(run func(context.Context, *gorm_model.User) error) *GormRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FetchCVs provides a mock function with given fields: ctx, userID
func (_m *GormRepo) FetchCVs(ctx context.Context, userID string) ([]gorm_model.CV, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchCVs")
	}

	var r0 []gorm_model.CV
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]gorm_model.CV, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []gorm_model.CV); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gorm_model.CV)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GormRepo_FetchCVs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCVs'
type GormRepo_FetchCVs_Call struct {
	*mock.Call
}

// FetchCVs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *GormRepo_Expecter) FetchCVs(ctx interface{}, userID interface{}) *GormRepo_FetchCVs_Call {
	return &GormRepo_FetchCVs_Call{Call: _e.mock.On("FetchCVs", ctx, userID)}
}

func (_c *GormRepo_FetchCVs_Call) Run(run func(ctx context.Context, userID string)) *GormRepo_FetchCVs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GormRepo_FetchCVs_Call) Return(_a0 []gorm_model.CV, _a1 error) *GormRepo_FetchCVs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GormRepo_FetchCVs_Call) RunAndReturn(run func(context.Context, string) ([]gorm_model.CV, error)) *GormRepo_FetchCVs_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOneUser provides a mock function with given fields: ctx, options
func (_m *GormRepo) FetchOneUser(ctx context.Context, options gorm_model.UserFilter) (*gorm_model.User, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for FetchOneUser")
	}

	var r0 *gorm_model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gorm_model.UserFilter) (*gorm_model.User, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gorm_model.UserFilter) *gorm_model.User); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm_model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gorm_model.UserFilter) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GormRepo_FetchOneUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOneUser'
type GormRepo_FetchOneUser_Call struct {
	*mock.Call
}

// FetchOneUser is a helper method to define mock.On call
//   - ctx context.Context
//   - options gorm_model.UserFilter
func (_e *GormRepo_Expecter) FetchOneUser(ctx interface{}, options interface{}) *GormRepo_FetchOneUser_Call {
	return &GormRepo_FetchOneUser_Call{Call: _e.mock.On("FetchOneUser", ctx, options)}
}

func (_c *GormRepo_FetchOneUser_Call) Run(run func(ctx context.Context, options gorm_model.UserFilter)) *GormRepo_FetchOneUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gorm_model.UserFilter))
	})
	return _c
}

func (_c *GormRepo_FetchOneUser_Call) Return(_a0 *gorm_model.User, _a1 error) *GormRepo_FetchOneUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GormRepo_FetchOneUser_Call) RunAndReturn(run func(context.Context, gorm_model.UserFilter) (*gorm_model.User, error)) *GormRepo_FetchOneUser_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUser provides a mock function with given fields: ctx, options
func (_m *GormRepo) FetchUser(ctx context.Context, options gorm_model.UserFilter) (*sql.Rows, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for FetchUser")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gorm_model.UserFilter) (*sql.Rows, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gorm_model.UserFilter) *sql.Rows); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gorm_model.UserFilter) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GormRepo_FetchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUser'
type GormRepo_FetchUser_Call struct {
	*mock.Call
}

// FetchUser is a helper method to define mock.On call
//   - ctx context.Context
//   - options gorm_model.UserFilter
func (_e *GormRepo_Expecter) FetchUser(ctx interface{}, options interface{}) *GormRepo_FetchUser_Call {
	return &GormRepo_FetchUser_Call{Call: _e.mock.On("FetchUser", ctx, options)}
}

func (_c *GormRepo_FetchUser_Call) Run(run func(ctx context.Context, options gorm_model.UserFilter)) *GormRepo_FetchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gorm_model.UserFilter))
	})
	return _c
}

func (_c *GormRepo_FetchUser_Call) Return(_a0 *sql.Rows, _a1 error) *GormRepo_FetchUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GormRepo_FetchUser_Call) RunAndReturn(run func(context.Context, gorm_model.UserFilter) (*sql.Rows, error)) *GormRepo_FetchUser_Call {
	_c.Call.Return(run)
	return _c
}

// StructScan provides a mock function with given fields: rows, dest
func (_m *GormRepo) StructScan(rows *sql.Rows, dest any) error {
	ret := _m.Called(rows, dest)

	if len(ret) == 0 {
		panic("no return value specified for StructScan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Rows, any) error); ok {
		r0 = rf(rows, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GormRepo_StructScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StructScan'
type GormRepo_StructScan_Call struct {
	*mock.Call
}

// StructScan is a helper method to define mock.On call
//   - rows *sql.Rows
//   - dest any
func (_e *GormRepo_Expecter) StructScan(rows interface{}, dest interface{}) *GormRepo_StructScan_Call {
	return &GormRepo_StructScan_Call{Call: _e.mock.On("StructScan", rows, dest)}
}

func (_c *GormRepo_StructScan_Call) Run(run func(rows *sql.Rows, dest any)) *GormRepo_StructScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Rows), args[1].(any))
	})
	return _c
}

func (_c *GormRepo_StructScan_Call) Return(_a0 error) *GormRepo_StructScan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GormRepo_StructScan_Call) RunAndReturn(run func(*sql.Rows, any) error) *GormRepo_StructScan_Call {
	_c.Call.Return(run)
	return _c
}

// NewGormRepo creates a new instance of GormRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGormRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *GormRepo {
	mock := &GormRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
