// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"
	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"
	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// JobRoleAppUsecase is an autogenerated mock type for the JobRoleAppUsecase type
type JobRoleAppUsecase struct {
	mock.Mock
}

type JobRoleAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *JobRoleAppUsecase) EXPECT() *JobRoleAppUsecase_Expecter {
	return &JobRoleAppUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *JobRoleAppUsecase) Create(ctx context.Context, req request_model.CreateJobRoleRequest) response.Base {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.CreateJobRoleRequest) response.Base); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobRoleAppUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type JobRoleAppUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.CreateJobRoleRequest
func (_e *JobRoleAppUsecase_Expecter) Create(ctx interface{}, req interface{}) *JobRoleAppUsecase_Create_Call {
	return &JobRoleAppUsecase_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *JobRoleAppUsecase_Create_Call) Run(run func(ctx context.Context, req request_model.CreateJobRoleRequest)) *JobRoleAppUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.CreateJobRoleRequest))
	})
	return _c
}

func (_c *JobRoleAppUsecase_Create_Call) Return(_a0 response.Base) *JobRoleAppUsecase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobRoleAppUsecase_Create_Call) RunAndReturn(run func(context.Context, request_model.CreateJobRoleRequest) response.Base) *JobRoleAppUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *JobRoleAppUsecase) Delete(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobRoleAppUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type JobRoleAppUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *JobRoleAppUsecase_Expecter) Delete(ctx interface{}, id interface{}) *JobRoleAppUsecase_Delete_Call {
	return &JobRoleAppUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *JobRoleAppUsecase_Delete_Call) Run(run func(ctx context.Context, id string)) *JobRoleAppUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *JobRoleAppUsecase_Delete_Call) Return(_a0 response.Base) *JobRoleAppUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobRoleAppUsecase_Delete_Call) RunAndReturn(run func(context.Context, string) response.Base) *JobRoleAppUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAll provides a mock function with given fields: ctx, page, limit, cursor, filter
func (_m *JobRoleAppUsecase) FetchAll(ctx context.Context, page int64, limit int64, cursor string, filter gorm_model.JobRoleFilter) response.Base {
	ret := _m.Called(ctx, page, limit, cursor, filter)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, gorm_model.JobRoleFilter) response.Base); ok {
		r0 = rf(ctx, page, limit, cursor, filter)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobRoleAppUsecase_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type JobRoleAppUsecase_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - cursor string
//   - filter gorm_model.JobRoleFilter
func (_e *JobRoleAppUsecase_Expecter) FetchAll(ctx interface{}, page interface{}, limit interface{}, cursor interface{}, filter interface{}) *JobRoleAppUsecase_FetchAll_Call {
	return &JobRoleAppUsecase_FetchAll_Call{Call: _e.mock.On("FetchAll", ctx, page, limit, cursor, filter)}
}

func (_c *JobRoleAppUsecase_FetchAll_Call) Run(run func(ctx context.Context, page int64, limit int64, cursor string, filter gorm_model.JobRoleFilter)) *JobRoleAppUsecase_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string), args[4].(gorm_model.JobRoleFilter))
	})
	return _c
}

func (_c *JobRoleAppUsecase_FetchAll_Call) Return(_a0 response.Base) *JobRoleAppUsecase_FetchAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobRoleAppUsecase_FetchAll_Call) RunAndReturn(run func(context.Context, int64, int64, string, gorm_model.JobRoleFilter) response.Base) *JobRoleAppUsecase_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// FetchData provides a mock function with given fields: ctx, id
func (_m *JobRoleAppUsecase) FetchData(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchData")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobRoleAppUsecase_FetchData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchData'
type JobRoleAppUsecase_FetchData_Call struct {
	*mock.Call
}

// FetchData is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *JobRoleAppUsecase_Expecter) FetchData(ctx interface{}, id interface{}) *JobRoleAppUsecase_FetchData_Call {
	return &JobRoleAppUsecase_FetchData_Call{Call: _e.mock.On("FetchData", ctx, id)}
}

func (_c *JobRoleAppUsecase_FetchData_Call) Run(run func(ctx context.Context, id string)) *JobRoleAppUsecase_FetchData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *JobRoleAppUsecase_FetchData_Call) Return(_a0 response.Base) *JobRoleAppUsecase_FetchData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobRoleAppUsecase_FetchData_Call) RunAndReturn(run func(context.Context, string) response.Base) *JobRoleAppUsecase_FetchData_Call {
	_c.Call.Return(run)
	return _c
}

// FetchSystemRoles provides a mock function with given fields: ctx
func (_m *JobRoleAppUsecase) FetchSystemRoles(ctx context.Context) response.Base {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchSystemRoles")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context) response.Base); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobRoleAppUsecase_FetchSystemRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchSystemRoles'
type JobRoleAppUsecase_FetchSystemRoles_Call struct {
	*mock.Call
}

// FetchSystemRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobRoleAppUsecase_Expecter) FetchSystemRoles(ctx interface{}) *JobRoleAppUsecase_FetchSystemRoles_Call {
	return &JobRoleAppUsecase_FetchSystemRoles_Call{Call: _e.mock.On("FetchSystemRoles", ctx)}
}

func (_c *JobRoleAppUsecase_FetchSystemRoles_Call) Run(run func(ctx context.Context)) *JobRoleAppUsecase_FetchSystemRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *JobRoleAppUsecase_FetchSystemRoles_Call) Return(_a0 response.Base) *JobRoleAppUsecase_FetchSystemRoles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobRoleAppUsecase_FetchSystemRoles_Call) RunAndReturn(run func(context.Context) response.Base) *JobRoleAppUsecase_FetchSystemRoles_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *JobRoleAppUsecase) Update(ctx context.Context, id string, req request_model.UpdateJobRoleRequest) response.Base {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.UpdateJobRoleRequest) response.Base); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobRoleAppUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type JobRoleAppUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req request_model.UpdateJobRoleRequest
func (_e *JobRoleAppUsecase_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *JobRoleAppUsecase_Update_Call {
	return &JobRoleAppUsecase_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *JobRoleAppUsecase_Update_Call) Run(run func(ctx context.Context, id string, req request_model.UpdateJobRoleRequest)) *JobRoleAppUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.UpdateJobRoleRequest))
	})
	return _c
}

func (_c *JobRoleAppUsecase_Update_Call) Return(_a0 response.Base) *JobRoleAppUsecase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobRoleAppUsecase_Update_Call) RunAndReturn(run func(context.Context, string, request_model.UpdateJobRoleRequest) response.Base) *JobRoleAppUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobRoleAppUsecase creates a new instance of JobRoleAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobRoleAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobRoleAppUsecase {
	mock := &JobRoleAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
