// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"
	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"
	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// JobVacancyAppUsecase is an autogenerated mock type for the JobVacancyAppUsecase type
type JobVacancyAppUsecase struct {
	mock.Mock
}

type JobVacancyAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *JobVacancyAppUsecase) EXPECT() *JobVacancyAppUsecase_Expecter {
	return &JobVacancyAppUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *JobVacancyAppUsecase) Create(ctx context.Context, req request_model.CreateJobVacancyRequest) response.Base {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.CreateJobVacancyRequest) response.Base); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobVacancyAppUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type JobVacancyAppUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.CreateJobVacancyRequest
func (_e *JobVacancyAppUsecase_Expecter) Create(ctx interface{}, req interface{}) *JobVacancyAppUsecase_Create_Call {
	return &JobVacancyAppUsecase_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *JobVacancyAppUsecase_Create_Call) Run(run func(ctx context.Context, req request_model.CreateJobVacancyRequest)) *JobVacancyAppUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.CreateJobVacancyRequest))
	})
	return _c
}

func (_c *JobVacancyAppUsecase_Create_Call) Return(_a0 response.Base) *JobVacancyAppUsecase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobVacancyAppUsecase_Create_Call) RunAndReturn(run func(context.Context, request_model.CreateJobVacancyRequest) response.Base) *JobVacancyAppUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *JobVacancyAppUsecase) Delete(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobVacancyAppUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type JobVacancyAppUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *JobVacancyAppUsecase_Expecter) Delete(ctx interface{}, id interface{}) *JobVacancyAppUsecase_Delete_Call {
	return &JobVacancyAppUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *JobVacancyAppUsecase_Delete_Call) Run(run func(ctx context.Context, id string)) *JobVacancyAppUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *JobVacancyAppUsecase_Delete_Call) Return(_a0 response.Base) *JobVacancyAppUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobVacancyAppUsecase_Delete_Call) RunAndReturn(run func(context.Context, string) response.Base) *JobVacancyAppUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAll provides a mock function with given fields: ctx, page, limit, filter
func (_m *JobVacancyAppUsecase) FetchAll(ctx context.Context, page int64, limit int64, filter gorm_model.JobVacancyFilter) response.Base {
	ret := _m.Called(ctx, page, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, gorm_model.JobVacancyFilter) response.Base); ok {
		r0 = rf(ctx, page, limit, filter)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobVacancyAppUsecase_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type JobVacancyAppUsecase_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - filter gorm_model.JobVacancyFilter
func (_e *JobVacancyAppUsecase_Expecter) FetchAll(ctx interface{}, page interface{}, limit interface{}, filter interface{}) *JobVacancyAppUsecase_FetchAll_Call {
	return &JobVacancyAppUsecase_FetchAll_Call{Call: _e.mock.On("FetchAll", ctx, page, limit, filter)}
}

func (_c *JobVacancyAppUsecase_FetchAll_Call) Run(run func(ctx context.Context, page int64, limit int64, filter gorm_model.JobVacancyFilter)) *JobVacancyAppUsecase_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(gorm_model.JobVacancyFilter))
	})
	return _c
}

func (_c *JobVacancyAppUsecase_FetchAll_Call) Return(_a0 response.Base) *JobVacancyAppUsecase_FetchAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobVacancyAppUsecase_FetchAll_Call) RunAndReturn(run func(context.Context, int64, int64, gorm_model.JobVacancyFilter) response.Base) *JobVacancyAppUsecase_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// FetchData provides a mock function with given fields: ctx, id
func (_m *JobVacancyAppUsecase) FetchData(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchData")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobVacancyAppUsecase_FetchData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchData'
type JobVacancyAppUsecase_FetchData_Call struct {
	*mock.Call
}

// FetchData is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *JobVacancyAppUsecase_Expecter) FetchData(ctx interface{}, id interface{}) *JobVacancyAppUsecase_FetchData_Call {
	return &JobVacancyAppUsecase_FetchData_Call{Call: _e.mock.On("FetchData", ctx, id)}
}

func (_c *JobVacancyAppUsecase_FetchData_Call) Run(run func(ctx context.Context, id string)) *JobVacancyAppUsecase_FetchData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *JobVacancyAppUsecase_FetchData_Call) Return(_a0 response.Base) *JobVacancyAppUsecase_FetchData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobVacancyAppUsecase_FetchData_Call) RunAndReturn(run func(context.Context, string) response.Base) *JobVacancyAppUsecase_FetchData_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPublic provides a mock function with given fields: ctx, page, limit, filter
func (_m *JobVacancyAppUsecase) FetchPublic(ctx context.Context, page int64, limit int64, filter gorm_model.JobVacancyFilter) response.Base {
	ret := _m.Called(ctx, page, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for FetchPublic")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, gorm_model.JobVacancyFilter) response.Base); ok {
		r0 = rf(ctx, page, limit, filter)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobVacancyAppUsecase_FetchPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPublic'
type JobVacancyAppUsecase_FetchPublic_Call struct {
	*mock.Call
}

// FetchPublic is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - filter gorm_model.JobVacancyFilter
func (_e *JobVacancyAppUsecase_Expecter) FetchPublic(ctx interface{}, page interface{}, limit interface{}, filter interface{}) *JobVacancyAppUsecase_FetchPublic_Call {
	return &JobVacancyAppUsecase_FetchPublic_Call{Call: _e.mock.On("FetchPublic", ctx, page, limit, filter)}
}

func (_c *JobVacancyAppUsecase_FetchPublic_Call) Run(run func(ctx context.Context, page int64, limit int64, filter gorm_model.JobVacancyFilter)) *JobVacancyAppUsecase_FetchPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(gorm_model.JobVacancyFilter))
	})
	return _c
}

func (_c *JobVacancyAppUsecase_FetchPublic_Call) Return(_a0 response.Base) *JobVacancyAppUsecase_FetchPublic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobVacancyAppUsecase_FetchPublic_Call) RunAndReturn(run func(context.Context, int64, int64, gorm_model.JobVacancyFilter) response.Base) *JobVacancyAppUsecase_FetchPublic_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPublicByID provides a mock function with given fields: ctx, id
func (_m *JobVacancyAppUsecase) FetchPublicByID(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchPublicByID")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobVacancyAppUsecase_FetchPublicByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPublicByID'
type JobVacancyAppUsecase_FetchPublicByID_Call struct {
	*mock.Call
}

// FetchPublicByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *JobVacancyAppUsecase_Expecter) FetchPublicByID(ctx interface{}, id interface{}) *JobVacancyAppUsecase_FetchPublicByID_Call {
	return &JobVacancyAppUsecase_FetchPublicByID_Call{Call: _e.mock.On("FetchPublicByID", ctx, id)}
}

func (_c *JobVacancyAppUsecase_FetchPublicByID_Call) Run(run func(ctx context.Context, id string)) *JobVacancyAppUsecase_FetchPublicByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *JobVacancyAppUsecase_FetchPublicByID_Call) Return(_a0 response.Base) *JobVacancyAppUsecase_FetchPublicByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobVacancyAppUsecase_FetchPublicByID_Call) RunAndReturn(run func(context.Context, string) response.Base) *JobVacancyAppUsecase_FetchPublicByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *JobVacancyAppUsecase) Update(ctx context.Context, id string, req request_model.UpdateJobVacancyRequest) response.Base {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.UpdateJobVacancyRequest) response.Base); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// JobVacancyAppUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type JobVacancyAppUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req request_model.UpdateJobVacancyRequest
func (_e *JobVacancyAppUsecase_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *JobVacancyAppUsecase_Update_Call {
	return &JobVacancyAppUsecase_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *JobVacancyAppUsecase_Update_Call) Run(run func(ctx context.Context, id string, req request_model.UpdateJobVacancyRequest)) *JobVacancyAppUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.UpdateJobVacancyRequest))
	})
	return _c
}

func (_c *JobVacancyAppUsecase_Update_Call) Return(_a0 response.Base) *JobVacancyAppUsecase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobVacancyAppUsecase_Update_Call) RunAndReturn(run func(context.Context, string, request_model.UpdateJobVacancyRequest) response.Base) *JobVacancyAppUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobVacancyAppUsecase creates a new instance of JobVacancyAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobVacancyAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobVacancyAppUsecase {
	mock := &JobVacancyAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
