// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

type Mailer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mailer) EXPECT() *Mailer_Expecter {
	return &Mailer_Expecter{mock: &_m.Mock}
}

// Attachment provides a mock function with given fields: r, filename, c
func (_m *Mailer) Attachment(r io.Reader, filename string, c string) {
	_m.Called(r, filename, c)
}

// Mailer_Attachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attachment'
type Mailer_Attachment_Call struct {
	*mock.Call
}

// Attachment is a helper method to define mock.On call
//   - r io.Reader
//   - filename string
//   - c string
func (_e *Mailer_Expecter) Attachment(r interface{}, filename interface{}, c interface{}) *Mailer_Attachment_Call {
	return &Mailer_Attachment_Call{Call: _e.mock.On("Attachment", r, filename, c)}
}

func (_c *Mailer_Attachment_Call) Run(run func(r io.Reader, filename string, c string)) *Mailer_Attachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Mailer_Attachment_Call) Return() *Mailer_Attachment_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mailer_Attachment_Call) RunAndReturn(run func(io.Reader, string, string)) *Mailer_Attachment_Call {
	_c.Run(run)
	return _c
}

// AttachmentFile provides a mock function with given fields: filename
func (_m *Mailer) AttachmentFile(filename string) {
	_m.Called(filename)
}

// Mailer_AttachmentFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachmentFile'
type Mailer_AttachmentFile_Call struct {
	*mock.Call
}

// AttachmentFile is a helper method to define mock.On call
//   - filename string
func (_e *Mailer_Expecter) AttachmentFile(filename interface{}) *Mailer_AttachmentFile_Call {
	return &Mailer_AttachmentFile_Call{Call: _e.mock.On("AttachmentFile", filename)}
}

func (_c *Mailer_AttachmentFile_Call) Run(run func(filename string)) *Mailer_AttachmentFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Mailer_AttachmentFile_Call) Return() *Mailer_AttachmentFile_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mailer_AttachmentFile_Call) RunAndReturn(run func(string)) *Mailer_AttachmentFile_Call {
	_c.Run(run)
	return _c
}

// Body provides a mock function with given fields: value
func (_m *Mailer) Body(value string) {
	_m.Called(value)
}

// Mailer_Body_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Body'
type Mailer_Body_Call struct {
	*mock.Call
}

// Body is a helper method to define mock.On call
//   - value string
func (_e *Mailer_Expecter) Body(value interface{}) *Mailer_Body_Call {
	return &Mailer_Body_Call{Call: _e.mock.On("Body", value)}
}

func (_c *Mailer_Body_Call) Run(run func(value string)) *Mailer_Body_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Mailer_Body_Call) Return() *Mailer_Body_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mailer_Body_Call) RunAndReturn(run func(string)) *Mailer_Body_Call {
	_c.Run(run)
	return _c
}

// From provides a mock function with given fields: fromEmail, fromName
func (_m *Mailer) From(fromEmail string, fromName string) {
	_m.Called(fromEmail, fromName)
}

// Mailer_From_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'From'
type Mailer_From_Call struct {
	*mock.Call
}

// From is a helper method to define mock.On call
//   - fromEmail string
//   - fromName string
func (_e *Mailer_Expecter) From(fromEmail interface{}, fromName interface{}) *Mailer_From_Call {
	return &Mailer_From_Call{Call: _e.mock.On("From", fromEmail, fromName)}
}

func (_c *Mailer_From_Call) Run(run func(fromEmail string, fromName string)) *Mailer_From_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Mailer_From_Call) Return() *Mailer_From_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mailer_From_Call) RunAndReturn(run func(string, string)) *Mailer_From_Call {
	_c.Run(run)
	return _c
}

// Send provides a mock function with no fields
func (_m *Mailer) Send() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Mailer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
func (_e *Mailer_Expecter) Send() *Mailer_Send_Call {
	return &Mailer_Send_Call{Call: _e.mock.On("Send")}
}

func (_c *Mailer_Send_Call) Run(run func()) *Mailer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mailer_Send_Call) Return(_a0 error) *Mailer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailer_Send_Call) RunAndReturn(run func() error) *Mailer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function with given fields: value
func (_m *Mailer) Subject(value string) {
	_m.Called(value)
}

// Mailer_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type Mailer_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
//   - value string
func (_e *Mailer_Expecter) Subject(value interface{}) *Mailer_Subject_Call {
	return &Mailer_Subject_Call{Call: _e.mock.On("Subject", value)}
}

func (_c *Mailer_Subject_Call) Run(run func(value string)) *Mailer_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Mailer_Subject_Call) Return() *Mailer_Subject_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mailer_Subject_Call) RunAndReturn(run func(string)) *Mailer_Subject_Call {
	_c.Run(run)
	return _c
}

// To provides a mock function with given fields: receiver
func (_m *Mailer) To(receiver []string) {
	_m.Called(receiver)
}

// Mailer_To_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'To'
type Mailer_To_Call struct {
	*mock.Call
}

// To is a helper method to define mock.On call
//   - receiver []string
func (_e *Mailer_Expecter) To(receiver interface{}) *Mailer_To_Call {
	return &Mailer_To_Call{Call: _e.mock.On("To", receiver)}
}

func (_c *Mailer_To_Call) Run(run func(receiver []string)) *Mailer_To_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *Mailer_To_Call) Return() *Mailer_To_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mailer_To_Call) RunAndReturn(run func([]string)) *Mailer_To_Call {
	_c.Run(run)
	return _c
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
