// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

type Mailer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mailer) EXPECT() *Mailer_Expecter {
	return &Mailer_Expecter{mock: &_m.Mock}
}

// SendCancelRecruitmentEmail provides a mock function with given fields: to, name
func (_m *Mailer) SendCancelRecruitmentEmail(to string, name string) error {
	ret := _m.Called(to, name)

	if len(ret) == 0 {
		panic("no return value specified for SendCancelRecruitmentEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(to, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailer_SendCancelRecruitmentEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCancelRecruitmentEmail'
type Mailer_SendCancelRecruitmentEmail_Call struct {
	*mock.Call
}

// SendCancelRecruitmentEmail is a helper method to define mock.On call
//   - to string
//   - name string
func (_e *Mailer_Expecter) SendCancelRecruitmentEmail(to interface{}, name interface{}) *Mailer_SendCancelRecruitmentEmail_Call {
	return &Mailer_SendCancelRecruitmentEmail_Call{Call: _e.mock.On("SendCancelRecruitmentEmail", to, name)}
}

func (_c *Mailer_SendCancelRecruitmentEmail_Call) Run(run func(to string, name string)) *Mailer_SendCancelRecruitmentEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Mailer_SendCancelRecruitmentEmail_Call) Return(_a0 error) *Mailer_SendCancelRecruitmentEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailer_SendCancelRecruitmentEmail_Call) RunAndReturn(run func(string, string) error) *Mailer_SendCancelRecruitmentEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendResetPasswordEmail provides a mock function with given fields: to, name, token
func (_m *Mailer) SendResetPasswordEmail(to string, name string, token string) error {
	ret := _m.Called(to, name, token)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPasswordEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(to, name, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailer_SendResetPasswordEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResetPasswordEmail'
type Mailer_SendResetPasswordEmail_Call struct {
	*mock.Call
}

// SendResetPasswordEmail is a helper method to define mock.On call
//   - to string
//   - name string
//   - token string
func (_e *Mailer_Expecter) SendResetPasswordEmail(to interface{}, name interface{}, token interface{}) *Mailer_SendResetPasswordEmail_Call {
	return &Mailer_SendResetPasswordEmail_Call{Call: _e.mock.On("SendResetPasswordEmail", to, name, token)}
}

func (_c *Mailer_SendResetPasswordEmail_Call) Run(run func(to string, name string, token string)) *Mailer_SendResetPasswordEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Mailer_SendResetPasswordEmail_Call) Return(_a0 error) *Mailer_SendResetPasswordEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailer_SendResetPasswordEmail_Call) RunAndReturn(run func(string, string, string) error) *Mailer_SendResetPasswordEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendStopOnboardingEmail provides a mock function with given fields: to, name
func (_m *Mailer) SendStopOnboardingEmail(to string, name string) error {
	ret := _m.Called(to, name)

	if len(ret) == 0 {
		panic("no return value specified for SendStopOnboardingEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(to, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailer_SendStopOnboardingEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStopOnboardingEmail'
type Mailer_SendStopOnboardingEmail_Call struct {
	*mock.Call
}

// SendStopOnboardingEmail is a helper method to define mock.On call
//   - to string
//   - name string
func (_e *Mailer_Expecter) SendStopOnboardingEmail(to interface{}, name interface{}) *Mailer_SendStopOnboardingEmail_Call {
	return &Mailer_SendStopOnboardingEmail_Call{Call: _e.mock.On("SendStopOnboardingEmail", to, name)}
}

func (_c *Mailer_SendStopOnboardingEmail_Call) Run(run func(to string, name string)) *Mailer_SendStopOnboardingEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Mailer_SendStopOnboardingEmail_Call) Return(_a0 error) *Mailer_SendStopOnboardingEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailer_SendStopOnboardingEmail_Call) RunAndReturn(run func(string, string) error) *Mailer_SendStopOnboardingEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendVerificationEmail provides a mock function with given fields: to, name, token
func (_m *Mailer) SendVerificationEmail(to string, name string, token string) error {
	ret := _m.Called(to, name, token)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(to, name, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailer_SendVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationEmail'
type Mailer_SendVerificationEmail_Call struct {
	*mock.Call
}

// SendVerificationEmail is a helper method to define mock.On call
//   - to string
//   - name string
//   - token string
func (_e *Mailer_Expecter) SendVerificationEmail(to interface{}, name interface{}, token interface{}) *Mailer_SendVerificationEmail_Call {
	return &Mailer_SendVerificationEmail_Call{Call: _e.mock.On("SendVerificationEmail", to, name, token)}
}

func (_c *Mailer_SendVerificationEmail_Call) Run(run func(to string, name string, token string)) *Mailer_SendVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Mailer_SendVerificationEmail_Call) Return(_a0 error) *Mailer_SendVerificationEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailer_SendVerificationEmail_Call) RunAndReturn(run func(string, string, string) error) *Mailer_SendVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
