// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	domain "github.com/adkurnwn/gigsourcehub-general-api/domain"
	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"
	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// MemberAppUsecase is an autogenerated mock type for the MemberAppUsecase type
type MemberAppUsecase struct {
	mock.Mock
}

type MemberAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberAppUsecase) EXPECT() *MemberAppUsecase_Expecter {
	return &MemberAppUsecase_Expecter{mock: &_m.Mock}
}

// ActivateUserBySuperadmin provides a mock function with given fields: ctx, id
func (_m *MemberAppUsecase) ActivateUserBySuperadmin(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ActivateUserBySuperadmin")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_ActivateUserBySuperadmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateUserBySuperadmin'
type MemberAppUsecase_ActivateUserBySuperadmin_Call struct {
	*mock.Call
}

// ActivateUserBySuperadmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MemberAppUsecase_Expecter) ActivateUserBySuperadmin(ctx interface{}, id interface{}) *MemberAppUsecase_ActivateUserBySuperadmin_Call {
	return &MemberAppUsecase_ActivateUserBySuperadmin_Call{Call: _e.mock.On("ActivateUserBySuperadmin", ctx, id)}
}

func (_c *MemberAppUsecase_ActivateUserBySuperadmin_Call) Run(run func(ctx context.Context, id string)) *MemberAppUsecase_ActivateUserBySuperadmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_ActivateUserBySuperadmin_Call) Return(_a0 response.Base) *MemberAppUsecase_ActivateUserBySuperadmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_ActivateUserBySuperadmin_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_ActivateUserBySuperadmin_Call {
	_c.Call.Return(run)
	return _c
}

// BlockUserBySuperadmin provides a mock function with given fields: ctx, id
func (_m *MemberAppUsecase) BlockUserBySuperadmin(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BlockUserBySuperadmin")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_BlockUserBySuperadmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockUserBySuperadmin'
type MemberAppUsecase_BlockUserBySuperadmin_Call struct {
	*mock.Call
}

// BlockUserBySuperadmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MemberAppUsecase_Expecter) BlockUserBySuperadmin(ctx interface{}, id interface{}) *MemberAppUsecase_BlockUserBySuperadmin_Call {
	return &MemberAppUsecase_BlockUserBySuperadmin_Call{Call: _e.mock.On("BlockUserBySuperadmin", ctx, id)}
}

func (_c *MemberAppUsecase_BlockUserBySuperadmin_Call) Run(run func(ctx context.Context, id string)) *MemberAppUsecase_BlockUserBySuperadmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_BlockUserBySuperadmin_Call) Return(_a0 response.Base) *MemberAppUsecase_BlockUserBySuperadmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_BlockUserBySuperadmin_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_BlockUserBySuperadmin_Call {
	_c.Call.Return(run)
	return _c
}

// CancelRecruitment provides a mock function with given fields: ctx, id
func (_m *MemberAppUsecase) CancelRecruitment(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelRecruitment")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_CancelRecruitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelRecruitment'
type MemberAppUsecase_CancelRecruitment_Call struct {
	*mock.Call
}

// CancelRecruitment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MemberAppUsecase_Expecter) CancelRecruitment(ctx interface{}, id interface{}) *MemberAppUsecase_CancelRecruitment_Call {
	return &MemberAppUsecase_CancelRecruitment_Call{Call: _e.mock.On("CancelRecruitment", ctx, id)}
}

func (_c *MemberAppUsecase_CancelRecruitment_Call) Run(run func(ctx context.Context, id string)) *MemberAppUsecase_CancelRecruitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_CancelRecruitment_Call) Return(_a0 response.Base) *MemberAppUsecase_CancelRecruitment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_CancelRecruitment_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_CancelRecruitment_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmDeclineRecruitment provides a mock function with given fields: ctx, id
func (_m *MemberAppUsecase) ConfirmDeclineRecruitment(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmDeclineRecruitment")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_ConfirmDeclineRecruitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmDeclineRecruitment'
type MemberAppUsecase_ConfirmDeclineRecruitment_Call struct {
	*mock.Call
}

// ConfirmDeclineRecruitment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MemberAppUsecase_Expecter) ConfirmDeclineRecruitment(ctx interface{}, id interface{}) *MemberAppUsecase_ConfirmDeclineRecruitment_Call {
	return &MemberAppUsecase_ConfirmDeclineRecruitment_Call{Call: _e.mock.On("ConfirmDeclineRecruitment", ctx, id)}
}

func (_c *MemberAppUsecase_ConfirmDeclineRecruitment_Call) Run(run func(ctx context.Context, id string)) *MemberAppUsecase_ConfirmDeclineRecruitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_ConfirmDeclineRecruitment_Call) Return(_a0 response.Base) *MemberAppUsecase_ConfirmDeclineRecruitment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_ConfirmDeclineRecruitment_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_ConfirmDeclineRecruitment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBySuperadmin provides a mock function with given fields: ctx, req
func (_m *MemberAppUsecase) CreateBySuperadmin(ctx context.Context, req request_model.CreateUserBySuperadminRequest) response.Base {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBySuperadmin")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.CreateUserBySuperadminRequest) response.Base); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_CreateBySuperadmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBySuperadmin'
type MemberAppUsecase_CreateBySuperadmin_Call struct {
	*mock.Call
}

// CreateBySuperadmin is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.CreateUserBySuperadminRequest
func (_e *MemberAppUsecase_Expecter) CreateBySuperadmin(ctx interface{}, req interface{}) *MemberAppUsecase_CreateBySuperadmin_Call {
	return &MemberAppUsecase_CreateBySuperadmin_Call{Call: _e.mock.On("CreateBySuperadmin", ctx, req)}
}

func (_c *MemberAppUsecase_CreateBySuperadmin_Call) Run(run func(ctx context.Context, req request_model.CreateUserBySuperadminRequest)) *MemberAppUsecase_CreateBySuperadmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.CreateUserBySuperadminRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_CreateBySuperadmin_Call) Return(_a0 response.Base) *MemberAppUsecase_CreateBySuperadmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_CreateBySuperadmin_Call) RunAndReturn(run func(context.Context, request_model.CreateUserBySuperadminRequest) response.Base) *MemberAppUsecase_CreateBySuperadmin_Call {
	_c.Call.Return(run)
	return _c
}

// DeclineRecruitment provides a mock function with given fields: ctx, id, req
func (_m *MemberAppUsecase) DeclineRecruitment(ctx context.Context, id string, req request_model.DeclineRecruitmentRequest) response.Base {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for DeclineRecruitment")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.DeclineRecruitmentRequest) response.Base); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_DeclineRecruitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclineRecruitment'
type MemberAppUsecase_DeclineRecruitment_Call struct {
	*mock.Call
}

// DeclineRecruitment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req request_model.DeclineRecruitmentRequest
func (_e *MemberAppUsecase_Expecter) DeclineRecruitment(ctx interface{}, id interface{}, req interface{}) *MemberAppUsecase_DeclineRecruitment_Call {
	return &MemberAppUsecase_DeclineRecruitment_Call{Call: _e.mock.On("DeclineRecruitment", ctx, id, req)}
}

func (_c *MemberAppUsecase_DeclineRecruitment_Call) Run(run func(ctx context.Context, id string, req request_model.DeclineRecruitmentRequest)) *MemberAppUsecase_DeclineRecruitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.DeclineRecruitmentRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_DeclineRecruitment_Call) Return(_a0 response.Base) *MemberAppUsecase_DeclineRecruitment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_DeclineRecruitment_Call) RunAndReturn(run func(context.Context, string, request_model.DeclineRecruitmentRequest) response.Base) *MemberAppUsecase_DeclineRecruitment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, userID, req
func (_m *MemberAppUsecase) DeleteAccount(ctx context.Context, userID string, req request_model.DeleteAccountRequest) response.Base {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.DeleteAccountRequest) response.Base); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MemberAppUsecase_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request_model.DeleteAccountRequest
func (_e *MemberAppUsecase_Expecter) DeleteAccount(ctx interface{}, userID interface{}, req interface{}) *MemberAppUsecase_DeleteAccount_Call {
	return &MemberAppUsecase_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, userID, req)}
}

func (_c *MemberAppUsecase_DeleteAccount_Call) Run(run func(ctx context.Context, userID string, req request_model.DeleteAccountRequest)) *MemberAppUsecase_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.DeleteAccountRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_DeleteAccount_Call) Return(_a0 response.Base) *MemberAppUsecase_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_DeleteAccount_Call) RunAndReturn(run func(context.Context, string, request_model.DeleteAccountRequest) response.Base) *MemberAppUsecase_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DisableUserBySuperadmin provides a mock function with given fields: ctx, id
func (_m *MemberAppUsecase) DisableUserBySuperadmin(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DisableUserBySuperadmin")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_DisableUserBySuperadmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableUserBySuperadmin'
type MemberAppUsecase_DisableUserBySuperadmin_Call struct {
	*mock.Call
}

// DisableUserBySuperadmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MemberAppUsecase_Expecter) DisableUserBySuperadmin(ctx interface{}, id interface{}) *MemberAppUsecase_DisableUserBySuperadmin_Call {
	return &MemberAppUsecase_DisableUserBySuperadmin_Call{Call: _e.mock.On("DisableUserBySuperadmin", ctx, id)}
}

func (_c *MemberAppUsecase_DisableUserBySuperadmin_Call) Run(run func(ctx context.Context, id string)) *MemberAppUsecase_DisableUserBySuperadmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_DisableUserBySuperadmin_Call) Return(_a0 response.Base) *MemberAppUsecase_DisableUserBySuperadmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_DisableUserBySuperadmin_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_DisableUserBySuperadmin_Call {
	_c.Call.Return(run)
	return _c
}

// EditUserBySuperadmin provides a mock function with given fields: ctx, id, req
func (_m *MemberAppUsecase) EditUserBySuperadmin(ctx context.Context, id string, req request_model.EditUserBySuperadminRequest) response.Base {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for EditUserBySuperadmin")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.EditUserBySuperadminRequest) response.Base); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_EditUserBySuperadmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditUserBySuperadmin'
type MemberAppUsecase_EditUserBySuperadmin_Call struct {
	*mock.Call
}

// EditUserBySuperadmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req request_model.EditUserBySuperadminRequest
func (_e *MemberAppUsecase_Expecter) EditUserBySuperadmin(ctx interface{}, id interface{}, req interface{}) *MemberAppUsecase_EditUserBySuperadmin_Call {
	return &MemberAppUsecase_EditUserBySuperadmin_Call{Call: _e.mock.On("EditUserBySuperadmin", ctx, id, req)}
}

func (_c *MemberAppUsecase_EditUserBySuperadmin_Call) Run(run func(ctx context.Context, id string, req request_model.EditUserBySuperadminRequest)) *MemberAppUsecase_EditUserBySuperadmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.EditUserBySuperadminRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_EditUserBySuperadmin_Call) Return(_a0 response.Base) *MemberAppUsecase_EditUserBySuperadmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_EditUserBySuperadmin_Call) RunAndReturn(run func(context.Context, string, request_model.EditUserBySuperadminRequest) response.Base) *MemberAppUsecase_EditUserBySuperadmin_Call {
	_c.Call.Return(run)
	return _c
}

// FetchCandidateBookmarked provides a mock function with given fields: ctx, adminID, page, limit, cursor
func (_m *MemberAppUsecase) FetchCandidateBookmarked(ctx context.Context, adminID string, page int64, limit int64, cursor string) response.Base {
	ret := _m.Called(ctx, adminID, page, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchCandidateBookmarked")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) response.Base); ok {
		r0 = rf(ctx, adminID, page, limit, cursor)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchCandidateBookmarked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCandidateBookmarked'
type MemberAppUsecase_FetchCandidateBookmarked_Call struct {
	*mock.Call
}

// FetchCandidateBookmarked is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - page int64
//   - limit int64
//   - cursor string
func (_e *MemberAppUsecase_Expecter) FetchCandidateBookmarked(ctx interface{}, adminID interface{}, page interface{}, limit interface{}, cursor interface{}) *MemberAppUsecase_FetchCandidateBookmarked_Call {
	return &MemberAppUsecase_FetchCandidateBookmarked_Call{Call: _e.mock.On("FetchCandidateBookmarked", ctx, adminID, page, limit, cursor)}
}

func (_c *MemberAppUsecase_FetchCandidateBookmarked_Call) Run(run func(ctx context.Context, adminID string, page int64, limit int64, cursor string)) *MemberAppUsecase_FetchCandidateBookmarked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchCandidateBookmarked_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchCandidateBookmarked_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchCandidateBookmarked_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) response.Base) *MemberAppUsecase_FetchCandidateBookmarked_Call {
	_c.Call.Return(run)
	return _c
}

// FetchCandidateRecruitment provides a mock function with given fields: ctx, page, limit, cursor
func (_m *MemberAppUsecase) FetchCandidateRecruitment(ctx context.Context, page int64, limit int64, cursor string) response.Base {
	ret := _m.Called(ctx, page, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchCandidateRecruitment")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) response.Base); ok {
		r0 = rf(ctx, page, limit, cursor)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchCandidateRecruitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCandidateRecruitment'
type MemberAppUsecase_FetchCandidateRecruitment_Call struct {
	*mock.Call
}

// FetchCandidateRecruitment is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - cursor string
func (_e *MemberAppUsecase_Expecter) FetchCandidateRecruitment(ctx interface{}, page interface{}, limit interface{}, cursor interface{}) *MemberAppUsecase_FetchCandidateRecruitment_Call {
	return &MemberAppUsecase_FetchCandidateRecruitment_Call{Call: _e.mock.On("FetchCandidateRecruitment", ctx, page, limit, cursor)}
}

func (_c *MemberAppUsecase_FetchCandidateRecruitment_Call) Run(run func(ctx context.Context, page int64, limit int64, cursor string)) *MemberAppUsecase_FetchCandidateRecruitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchCandidateRecruitment_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchCandidateRecruitment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchCandidateRecruitment_Call) RunAndReturn(run func(context.Context, int64, int64, string) response.Base) *MemberAppUsecase_FetchCandidateRecruitment_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOnboardingActive provides a mock function with given fields: ctx, page, limit, cursor
func (_m *MemberAppUsecase) FetchOnboardingActive(ctx context.Context, page int64, limit int64, cursor string) response.Base {
	ret := _m.Called(ctx, page, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchOnboardingActive")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) response.Base); ok {
		r0 = rf(ctx, page, limit, cursor)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchOnboardingActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOnboardingActive'
type MemberAppUsecase_FetchOnboardingActive_Call struct {
	*mock.Call
}

// FetchOnboardingActive is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - cursor string
func (_e *MemberAppUsecase_Expecter) FetchOnboardingActive(ctx interface{}, page interface{}, limit interface{}, cursor interface{}) *MemberAppUsecase_FetchOnboardingActive_Call {
	return &MemberAppUsecase_FetchOnboardingActive_Call{Call: _e.mock.On("FetchOnboardingActive", ctx, page, limit, cursor)}
}

func (_c *MemberAppUsecase_FetchOnboardingActive_Call) Run(run func(ctx context.Context, page int64, limit int64, cursor string)) *MemberAppUsecase_FetchOnboardingActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingActive_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchOnboardingActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingActive_Call) RunAndReturn(run func(context.Context, int64, int64, string) response.Base) *MemberAppUsecase_FetchOnboardingActive_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOnboardingActiveTeam provides a mock function with given fields: ctx, employeeID, page, limit, cursor
func (_m *MemberAppUsecase) FetchOnboardingActiveTeam(ctx context.Context, employeeID string, page int64, limit int64, cursor string) response.Base {
	ret := _m.Called(ctx, employeeID, page, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchOnboardingActiveTeam")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) response.Base); ok {
		r0 = rf(ctx, employeeID, page, limit, cursor)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchOnboardingActiveTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOnboardingActiveTeam'
type MemberAppUsecase_FetchOnboardingActiveTeam_Call struct {
	*mock.Call
}

// FetchOnboardingActiveTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID string
//   - page int64
//   - limit int64
//   - cursor string
func (_e *MemberAppUsecase_Expecter) FetchOnboardingActiveTeam(ctx interface{}, employeeID interface{}, page interface{}, limit interface{}, cursor interface{}) *MemberAppUsecase_FetchOnboardingActiveTeam_Call {
	return &MemberAppUsecase_FetchOnboardingActiveTeam_Call{Call: _e.mock.On("FetchOnboardingActiveTeam", ctx, employeeID, page, limit, cursor)}
}

func (_c *MemberAppUsecase_FetchOnboardingActiveTeam_Call) Run(run func(ctx context.Context, employeeID string, page int64, limit int64, cursor string)) *MemberAppUsecase_FetchOnboardingActiveTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingActiveTeam_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchOnboardingActiveTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingActiveTeam_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) response.Base) *MemberAppUsecase_FetchOnboardingActiveTeam_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOnboardingArchive provides a mock function with given fields: ctx, page, limit, cursor
func (_m *MemberAppUsecase) FetchOnboardingArchive(ctx context.Context, page int64, limit int64, cursor string) response.Base {
	ret := _m.Called(ctx, page, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchOnboardingArchive")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) response.Base); ok {
		r0 = rf(ctx, page, limit, cursor)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchOnboardingArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOnboardingArchive'
type MemberAppUsecase_FetchOnboardingArchive_Call struct {
	*mock.Call
}

// FetchOnboardingArchive is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - cursor string
func (_e *MemberAppUsecase_Expecter) FetchOnboardingArchive(ctx interface{}, page interface{}, limit interface{}, cursor interface{}) *MemberAppUsecase_FetchOnboardingArchive_Call {
	return &MemberAppUsecase_FetchOnboardingArchive_Call{Call: _e.mock.On("FetchOnboardingArchive", ctx, page, limit, cursor)}
}

func (_c *MemberAppUsecase_FetchOnboardingArchive_Call) Run(run func(ctx context.Context, page int64, limit int64, cursor string)) *MemberAppUsecase_FetchOnboardingArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingArchive_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchOnboardingArchive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingArchive_Call) RunAndReturn(run func(context.Context, int64, int64, string) response.Base) *MemberAppUsecase_FetchOnboardingArchive_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOnboardingByCandidate provides a mock function with given fields: ctx, candidateID, page, limit, cursor
func (_m *MemberAppUsecase) FetchOnboardingByCandidate(ctx context.Context, candidateID string, page int64, limit int64, cursor string) response.Base {
	ret := _m.Called(ctx, candidateID, page, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchOnboardingByCandidate")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) response.Base); ok {
		r0 = rf(ctx, candidateID, page, limit, cursor)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchOnboardingByCandidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOnboardingByCandidate'
type MemberAppUsecase_FetchOnboardingByCandidate_Call struct {
	*mock.Call
}

// FetchOnboardingByCandidate is a helper method to define mock.On call
//   - ctx context.Context
//   - candidateID string
//   - page int64
//   - limit int64
//   - cursor string
func (_e *MemberAppUsecase_Expecter) FetchOnboardingByCandidate(ctx interface{}, candidateID interface{}, page interface{}, limit interface{}, cursor interface{}) *MemberAppUsecase_FetchOnboardingByCandidate_Call {
	return &MemberAppUsecase_FetchOnboardingByCandidate_Call{Call: _e.mock.On("FetchOnboardingByCandidate", ctx, candidateID, page, limit, cursor)}
}

func (_c *MemberAppUsecase_FetchOnboardingByCandidate_Call) Run(run func(ctx context.Context, candidateID string, page int64, limit int64, cursor string)) *MemberAppUsecase_FetchOnboardingByCandidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingByCandidate_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchOnboardingByCandidate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingByCandidate_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) response.Base) *MemberAppUsecase_FetchOnboardingByCandidate_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOnboardingHistory provides a mock function with given fields: ctx, employeeID, page, limit, cursor
func (_m *MemberAppUsecase) FetchOnboardingHistory(ctx context.Context, employeeID string, page int64, limit int64, cursor string) response.Base {
	ret := _m.Called(ctx, employeeID, page, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchOnboardingHistory")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) response.Base); ok {
		r0 = rf(ctx, employeeID, page, limit, cursor)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchOnboardingHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOnboardingHistory'
type MemberAppUsecase_FetchOnboardingHistory_Call struct {
	*mock.Call
}

// FetchOnboardingHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID string
//   - page int64
//   - limit int64
//   - cursor string
func (_e *MemberAppUsecase_Expecter) FetchOnboardingHistory(ctx interface{}, employeeID interface{}, page interface{}, limit interface{}, cursor interface{}) *MemberAppUsecase_FetchOnboardingHistory_Call {
	return &MemberAppUsecase_FetchOnboardingHistory_Call{Call: _e.mock.On("FetchOnboardingHistory", ctx, employeeID, page, limit, cursor)}
}

func (_c *MemberAppUsecase_FetchOnboardingHistory_Call) Run(run func(ctx context.Context, employeeID string, page int64, limit int64, cursor string)) *MemberAppUsecase_FetchOnboardingHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingHistory_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchOnboardingHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchOnboardingHistory_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) response.Base) *MemberAppUsecase_FetchOnboardingHistory_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserDetail provides a mock function with given fields: ctx, id
func (_m *MemberAppUsecase) FetchUserDetail(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserDetail")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchUserDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserDetail'
type MemberAppUsecase_FetchUserDetail_Call struct {
	*mock.Call
}

// FetchUserDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MemberAppUsecase_Expecter) FetchUserDetail(ctx interface{}, id interface{}) *MemberAppUsecase_FetchUserDetail_Call {
	return &MemberAppUsecase_FetchUserDetail_Call{Call: _e.mock.On("FetchUserDetail", ctx, id)}
}

func (_c *MemberAppUsecase_FetchUserDetail_Call) Run(run func(ctx context.Context, id string)) *MemberAppUsecase_FetchUserDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchUserDetail_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchUserDetail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchUserDetail_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_FetchUserDetail_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserThumb provides a mock function with given fields: ctx, id
func (_m *MemberAppUsecase) FetchUserThumb(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserThumb")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchUserThumb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserThumb'
type MemberAppUsecase_FetchUserThumb_Call struct {
	*mock.Call
}

// FetchUserThumb is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MemberAppUsecase_Expecter) FetchUserThumb(ctx interface{}, id interface{}) *MemberAppUsecase_FetchUserThumb_Call {
	return &MemberAppUsecase_FetchUserThumb_Call{Call: _e.mock.On("FetchUserThumb", ctx, id)}
}

func (_c *MemberAppUsecase_FetchUserThumb_Call) Run(run func(ctx context.Context, id string)) *MemberAppUsecase_FetchUserThumb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchUserThumb_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchUserThumb_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchUserThumb_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_FetchUserThumb_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUsers provides a mock function with given fields: ctx, page, limit, cursor, search, roleName, adminID
func (_m *MemberAppUsecase) FetchUsers(ctx context.Context, page int64, limit int64, cursor string, search *string, roleName *string, adminID *string) response.Base {
	ret := _m.Called(ctx, page, limit, cursor, search, roleName, adminID)

	if len(ret) == 0 {
		panic("no return value specified for FetchUsers")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, *string, *string, *string) response.Base); ok {
		r0 = rf(ctx, page, limit, cursor, search, roleName, adminID)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FetchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUsers'
type MemberAppUsecase_FetchUsers_Call struct {
	*mock.Call
}

// FetchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - cursor string
//   - search *string
//   - roleName *string
//   - adminID *string
func (_e *MemberAppUsecase_Expecter) FetchUsers(ctx interface{}, page interface{}, limit interface{}, cursor interface{}, search interface{}, roleName interface{}, adminID interface{}) *MemberAppUsecase_FetchUsers_Call {
	return &MemberAppUsecase_FetchUsers_Call{Call: _e.mock.On("FetchUsers", ctx, page, limit, cursor, search, roleName, adminID)}
}

func (_c *MemberAppUsecase_FetchUsers_Call) Run(run func(ctx context.Context, page int64, limit int64, cursor string, search *string, roleName *string, adminID *string)) *MemberAppUsecase_FetchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string), args[4].(*string), args[5].(*string), args[6].(*string))
	})
	return _c
}

func (_c *MemberAppUsecase_FetchUsers_Call) Return(_a0 response.Base) *MemberAppUsecase_FetchUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FetchUsers_Call) RunAndReturn(run func(context.Context, int64, int64, string, *string, *string, *string) response.Base) *MemberAppUsecase_FetchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// FinalizeRecruitment provides a mock function with given fields: ctx, adminID, req
func (_m *MemberAppUsecase) FinalizeRecruitment(ctx context.Context, adminID string, req request_model.FinalizeRecruitmentRequest) response.Base {
	ret := _m.Called(ctx, adminID, req)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeRecruitment")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.FinalizeRecruitmentRequest) response.Base); ok {
		r0 = rf(ctx, adminID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_FinalizeRecruitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeRecruitment'
type MemberAppUsecase_FinalizeRecruitment_Call struct {
	*mock.Call
}

// FinalizeRecruitment is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID string
//   - req request_model.FinalizeRecruitmentRequest
func (_e *MemberAppUsecase_Expecter) FinalizeRecruitment(ctx interface{}, adminID interface{}, req interface{}) *MemberAppUsecase_FinalizeRecruitment_Call {
	return &MemberAppUsecase_FinalizeRecruitment_Call{Call: _e.mock.On("FinalizeRecruitment", ctx, adminID, req)}
}

func (_c *MemberAppUsecase_FinalizeRecruitment_Call) Run(run func(ctx context.Context, adminID string, req request_model.FinalizeRecruitmentRequest)) *MemberAppUsecase_FinalizeRecruitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.FinalizeRecruitmentRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_FinalizeRecruitment_Call) Return(_a0 response.Base) *MemberAppUsecase_FinalizeRecruitment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_FinalizeRecruitment_Call) RunAndReturn(run func(context.Context, string, request_model.FinalizeRecruitmentRequest) response.Base) *MemberAppUsecase_FinalizeRecruitment_Call {
	_c.Call.Return(run)
	return _c
}

// ForgotPassword provides a mock function with given fields: ctx, req
func (_m *MemberAppUsecase) ForgotPassword(ctx context.Context, req request_model.ForgotPasswordRequest) response.Base {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.ForgotPasswordRequest) response.Base); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MemberAppUsecase_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.ForgotPasswordRequest
func (_e *MemberAppUsecase_Expecter) ForgotPassword(ctx interface{}, req interface{}) *MemberAppUsecase_ForgotPassword_Call {
	return &MemberAppUsecase_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, req)}
}

func (_c *MemberAppUsecase_ForgotPassword_Call) Run(run func(ctx context.Context, req request_model.ForgotPasswordRequest)) *MemberAppUsecase_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.ForgotPasswordRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_ForgotPassword_Call) Return(_a0 response.Base) *MemberAppUsecase_ForgotPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_ForgotPassword_Call) RunAndReturn(run func(context.Context, request_model.ForgotPasswordRequest) response.Base) *MemberAppUsecase_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSubrequest provides a mock function with given fields: ctx, id
func (_m *MemberAppUsecase) GetActiveSubrequest(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSubrequest")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_GetActiveSubrequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSubrequest'
type MemberAppUsecase_GetActiveSubrequest_Call struct {
	*mock.Call
}

// GetActiveSubrequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MemberAppUsecase_Expecter) GetActiveSubrequest(ctx interface{}, id interface{}) *MemberAppUsecase_GetActiveSubrequest_Call {
	return &MemberAppUsecase_GetActiveSubrequest_Call{Call: _e.mock.On("GetActiveSubrequest", ctx, id)}
}

func (_c *MemberAppUsecase_GetActiveSubrequest_Call) Run(run func(ctx context.Context, id string)) *MemberAppUsecase_GetActiveSubrequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_GetActiveSubrequest_Call) Return(_a0 response.Base) *MemberAppUsecase_GetActiveSubrequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_GetActiveSubrequest_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_GetActiveSubrequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function with given fields: ctx, claim
func (_m *MemberAppUsecase) GetMe(ctx context.Context, claim domain.JWTClaimUser) response.Base {
	ret := _m.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, domain.JWTClaimUser) response.Base); ok {
		r0 = rf(ctx, claim)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MemberAppUsecase_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - claim domain.JWTClaimUser
func (_e *MemberAppUsecase_Expecter) GetMe(ctx interface{}, claim interface{}) *MemberAppUsecase_GetMe_Call {
	return &MemberAppUsecase_GetMe_Call{Call: _e.mock.On("GetMe", ctx, claim)}
}

func (_c *MemberAppUsecase_GetMe_Call) Run(run func(ctx context.Context, claim domain.JWTClaimUser)) *MemberAppUsecase_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JWTClaimUser))
	})
	return _c
}

func (_c *MemberAppUsecase_GetMe_Call) Return(_a0 response.Base) *MemberAppUsecase_GetMe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_GetMe_Call) RunAndReturn(run func(context.Context, domain.JWTClaimUser) response.Base) *MemberAppUsecase_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, claim
func (_m *MemberAppUsecase) GetProfile(ctx context.Context, claim domain.JWTClaimUser) response.Base {
	ret := _m.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, domain.JWTClaimUser) response.Base); ok {
		r0 = rf(ctx, claim)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MemberAppUsecase_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - claim domain.JWTClaimUser
func (_e *MemberAppUsecase_Expecter) GetProfile(ctx interface{}, claim interface{}) *MemberAppUsecase_GetProfile_Call {
	return &MemberAppUsecase_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, claim)}
}

func (_c *MemberAppUsecase_GetProfile_Call) Run(run func(ctx context.Context, claim domain.JWTClaimUser)) *MemberAppUsecase_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JWTClaimUser))
	})
	return _c
}

func (_c *MemberAppUsecase_GetProfile_Call) Return(_a0 response.Base) *MemberAppUsecase_GetProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_GetProfile_Call) RunAndReturn(run func(context.Context, domain.JWTClaimUser) response.Base) *MemberAppUsecase_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, payload
func (_m *MemberAppUsecase) Login(ctx context.Context, payload request_model.LoginRequest) response.Base {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.LoginRequest) response.Base); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MemberAppUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - payload request_model.LoginRequest
func (_e *MemberAppUsecase_Expecter) Login(ctx interface{}, payload interface{}) *MemberAppUsecase_Login_Call {
	return &MemberAppUsecase_Login_Call{Call: _e.mock.On("Login", ctx, payload)}
}

func (_c *MemberAppUsecase_Login_Call) Run(run func(ctx context.Context, payload request_model.LoginRequest)) *MemberAppUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.LoginRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_Login_Call) Return(_a0 response.Base) *MemberAppUsecase_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_Login_Call) RunAndReturn(run func(context.Context, request_model.LoginRequest) response.Base) *MemberAppUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, claim, refreshToken
func (_m *MemberAppUsecase) Logout(ctx context.Context, claim domain.JWTClaimUser, refreshToken string) response.Base {
	ret := _m.Called(ctx, claim, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, domain.JWTClaimUser, string) response.Base); ok {
		r0 = rf(ctx, claim, refreshToken)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MemberAppUsecase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - claim domain.JWTClaimUser
//   - refreshToken string
func (_e *MemberAppUsecase_Expecter) Logout(ctx interface{}, claim interface{}, refreshToken interface{}) *MemberAppUsecase_Logout_Call {
	return &MemberAppUsecase_Logout_Call{Call: _e.mock.On("Logout", ctx, claim, refreshToken)}
}

func (_c *MemberAppUsecase_Logout_Call) Run(run func(ctx context.Context, claim domain.JWTClaimUser, refreshToken string)) *MemberAppUsecase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JWTClaimUser), args[2].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_Logout_Call) Return(_a0 response.Base) *MemberAppUsecase_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_Logout_Call) RunAndReturn(run func(context.Context, domain.JWTClaimUser, string) response.Base) *MemberAppUsecase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// PatchUserRecruitmentStatus provides a mock function with given fields: ctx, id, req
func (_m *MemberAppUsecase) PatchUserRecruitmentStatus(ctx context.Context, id string, req request_model.PatchUserRecruitmentStatusRequest) response.Base {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for PatchUserRecruitmentStatus")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.PatchUserRecruitmentStatusRequest) response.Base); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_PatchUserRecruitmentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchUserRecruitmentStatus'
type MemberAppUsecase_PatchUserRecruitmentStatus_Call struct {
	*mock.Call
}

// PatchUserRecruitmentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req request_model.PatchUserRecruitmentStatusRequest
func (_e *MemberAppUsecase_Expecter) PatchUserRecruitmentStatus(ctx interface{}, id interface{}, req interface{}) *MemberAppUsecase_PatchUserRecruitmentStatus_Call {
	return &MemberAppUsecase_PatchUserRecruitmentStatus_Call{Call: _e.mock.On("PatchUserRecruitmentStatus", ctx, id, req)}
}

func (_c *MemberAppUsecase_PatchUserRecruitmentStatus_Call) Run(run func(ctx context.Context, id string, req request_model.PatchUserRecruitmentStatusRequest)) *MemberAppUsecase_PatchUserRecruitmentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.PatchUserRecruitmentStatusRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_PatchUserRecruitmentStatus_Call) Return(_a0 response.Base) *MemberAppUsecase_PatchUserRecruitmentStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_PatchUserRecruitmentStatus_Call) RunAndReturn(run func(context.Context, string, request_model.PatchUserRecruitmentStatusRequest) response.Base) *MemberAppUsecase_PatchUserRecruitmentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, payload
func (_m *MemberAppUsecase) RefreshToken(ctx context.Context, payload request_model.RefreshTokenRequest) response.Base {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.RefreshTokenRequest) response.Base); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MemberAppUsecase_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - payload request_model.RefreshTokenRequest
func (_e *MemberAppUsecase_Expecter) RefreshToken(ctx interface{}, payload interface{}) *MemberAppUsecase_RefreshToken_Call {
	return &MemberAppUsecase_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, payload)}
}

func (_c *MemberAppUsecase_RefreshToken_Call) Run(run func(ctx context.Context, payload request_model.RefreshTokenRequest)) *MemberAppUsecase_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.RefreshTokenRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_RefreshToken_Call) Return(_a0 response.Base) *MemberAppUsecase_RefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_RefreshToken_Call) RunAndReturn(run func(context.Context, request_model.RefreshTokenRequest) response.Base) *MemberAppUsecase_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, payload
func (_m *MemberAppUsecase) Register(ctx context.Context, payload request_model.RegisterRequest) response.Base {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.RegisterRequest) response.Base); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MemberAppUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - payload request_model.RegisterRequest
func (_e *MemberAppUsecase_Expecter) Register(ctx interface{}, payload interface{}) *MemberAppUsecase_Register_Call {
	return &MemberAppUsecase_Register_Call{Call: _e.mock.On("Register", ctx, payload)}
}

func (_c *MemberAppUsecase_Register_Call) Run(run func(ctx context.Context, payload request_model.RegisterRequest)) *MemberAppUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.RegisterRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_Register_Call) Return(_a0 response.Base) *MemberAppUsecase_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_Register_Call) RunAndReturn(run func(context.Context, request_model.RegisterRequest) response.Base) *MemberAppUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerification provides a mock function with given fields: ctx, req
func (_m *MemberAppUsecase) ResendVerification(ctx context.Context, req request_model.ResendVerificationRequest) response.Base {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerification")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.ResendVerificationRequest) response.Base); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_ResendVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerification'
type MemberAppUsecase_ResendVerification_Call struct {
	*mock.Call
}

// ResendVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.ResendVerificationRequest
func (_e *MemberAppUsecase_Expecter) ResendVerification(ctx interface{}, req interface{}) *MemberAppUsecase_ResendVerification_Call {
	return &MemberAppUsecase_ResendVerification_Call{Call: _e.mock.On("ResendVerification", ctx, req)}
}

func (_c *MemberAppUsecase_ResendVerification_Call) Run(run func(ctx context.Context, req request_model.ResendVerificationRequest)) *MemberAppUsecase_ResendVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.ResendVerificationRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_ResendVerification_Call) Return(_a0 response.Base) *MemberAppUsecase_ResendVerification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_ResendVerification_Call) RunAndReturn(run func(context.Context, request_model.ResendVerificationRequest) response.Base) *MemberAppUsecase_ResendVerification_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, req
func (_m *MemberAppUsecase) ResetPassword(ctx context.Context, req request_model.ResetPasswordRequest) response.Base {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.ResetPasswordRequest) response.Base); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MemberAppUsecase_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.ResetPasswordRequest
func (_e *MemberAppUsecase_Expecter) ResetPassword(ctx interface{}, req interface{}) *MemberAppUsecase_ResetPassword_Call {
	return &MemberAppUsecase_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, req)}
}

func (_c *MemberAppUsecase_ResetPassword_Call) Run(run func(ctx context.Context, req request_model.ResetPasswordRequest)) *MemberAppUsecase_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.ResetPasswordRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_ResetPassword_Call) Return(_a0 response.Base) *MemberAppUsecase_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_ResetPassword_Call) RunAndReturn(run func(context.Context, request_model.ResetPasswordRequest) response.Base) *MemberAppUsecase_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// StopOnboarding provides a mock function with given fields: ctx, id, req
func (_m *MemberAppUsecase) StopOnboarding(ctx context.Context, id string, req request_model.StopOnboardingRequest) response.Base {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for StopOnboarding")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.StopOnboardingRequest) response.Base); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_StopOnboarding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopOnboarding'
type MemberAppUsecase_StopOnboarding_Call struct {
	*mock.Call
}

// StopOnboarding is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req request_model.StopOnboardingRequest
func (_e *MemberAppUsecase_Expecter) StopOnboarding(ctx interface{}, id interface{}, req interface{}) *MemberAppUsecase_StopOnboarding_Call {
	return &MemberAppUsecase_StopOnboarding_Call{Call: _e.mock.On("StopOnboarding", ctx, id, req)}
}

func (_c *MemberAppUsecase_StopOnboarding_Call) Run(run func(ctx context.Context, id string, req request_model.StopOnboardingRequest)) *MemberAppUsecase_StopOnboarding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.StopOnboardingRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_StopOnboarding_Call) Return(_a0 response.Base) *MemberAppUsecase_StopOnboarding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_StopOnboarding_Call) RunAndReturn(run func(context.Context, string, request_model.StopOnboardingRequest) response.Base) *MemberAppUsecase_StopOnboarding_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, userID, req
func (_m *MemberAppUsecase) UpdatePassword(ctx context.Context, userID string, req request_model.UpdatePasswordRequest) response.Base {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.UpdatePasswordRequest) response.Base); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MemberAppUsecase_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request_model.UpdatePasswordRequest
func (_e *MemberAppUsecase_Expecter) UpdatePassword(ctx interface{}, userID interface{}, req interface{}) *MemberAppUsecase_UpdatePassword_Call {
	return &MemberAppUsecase_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, req)}
}

func (_c *MemberAppUsecase_UpdatePassword_Call) Run(run func(ctx context.Context, userID string, req request_model.UpdatePasswordRequest)) *MemberAppUsecase_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.UpdatePasswordRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_UpdatePassword_Call) Return(_a0 response.Base) *MemberAppUsecase_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_UpdatePassword_Call) RunAndReturn(run func(context.Context, string, request_model.UpdatePasswordRequest) response.Base) *MemberAppUsecase_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, req
func (_m *MemberAppUsecase) UpdateProfile(ctx context.Context, userID string, req request_model.UpdateProfileRequest) response.Base {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.UpdateProfileRequest) response.Base); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MemberAppUsecase_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request_model.UpdateProfileRequest
func (_e *MemberAppUsecase_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MemberAppUsecase_UpdateProfile_Call {
	return &MemberAppUsecase_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MemberAppUsecase_UpdateProfile_Call) Run(run func(ctx context.Context, userID string, req request_model.UpdateProfileRequest)) *MemberAppUsecase_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.UpdateProfileRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_UpdateProfile_Call) Return(_a0 response.Base) *MemberAppUsecase_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, request_model.UpdateProfileRequest) response.Base) *MemberAppUsecase_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadProfilePicture provides a mock function with given fields: ctx, userID, file
func (_m *MemberAppUsecase) UploadProfilePicture(ctx context.Context, userID string, file *multipart.FileHeader) response.Base {
	ret := _m.Called(ctx, userID, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadProfilePicture")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, *multipart.FileHeader) response.Base); ok {
		r0 = rf(ctx, userID, file)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_UploadProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadProfilePicture'
type MemberAppUsecase_UploadProfilePicture_Call struct {
	*mock.Call
}

// UploadProfilePicture is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - file *multipart.FileHeader
func (_e *MemberAppUsecase_Expecter) UploadProfilePicture(ctx interface{}, userID interface{}, file interface{}) *MemberAppUsecase_UploadProfilePicture_Call {
	return &MemberAppUsecase_UploadProfilePicture_Call{Call: _e.mock.On("UploadProfilePicture", ctx, userID, file)}
}

func (_c *MemberAppUsecase_UploadProfilePicture_Call) Run(run func(ctx context.Context, userID string, file *multipart.FileHeader)) *MemberAppUsecase_UploadProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*multipart.FileHeader))
	})
	return _c
}

func (_c *MemberAppUsecase_UploadProfilePicture_Call) Return(_a0 response.Base) *MemberAppUsecase_UploadProfilePicture_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_UploadProfilePicture_Call) RunAndReturn(run func(context.Context, string, *multipart.FileHeader) response.Base) *MemberAppUsecase_UploadProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAccount provides a mock function with given fields: ctx, token
func (_m *MemberAppUsecase) VerifyAccount(ctx context.Context, token string) response.Base {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccount")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_VerifyAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccount'
type MemberAppUsecase_VerifyAccount_Call struct {
	*mock.Call
}

// VerifyAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MemberAppUsecase_Expecter) VerifyAccount(ctx interface{}, token interface{}) *MemberAppUsecase_VerifyAccount_Call {
	return &MemberAppUsecase_VerifyAccount_Call{Call: _e.mock.On("VerifyAccount", ctx, token)}
}

func (_c *MemberAppUsecase_VerifyAccount_Call) Run(run func(ctx context.Context, token string)) *MemberAppUsecase_VerifyAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_VerifyAccount_Call) Return(_a0 response.Base) *MemberAppUsecase_VerifyAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_VerifyAccount_Call) RunAndReturn(run func(context.Context, string) response.Base) *MemberAppUsecase_VerifyAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberAppUsecase creates a new instance of MemberAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberAppUsecase {
	mock := &MemberAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
