// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/adkurnwn/gigsourcehub-general-api/domain"
	mock "github.com/stretchr/testify/mock"

	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"

	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"

	url "net/url"
)

// MemberAppUsecase is an autogenerated mock type for the MemberAppUsecase type
type MemberAppUsecase struct {
	mock.Mock
}

type MemberAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberAppUsecase) EXPECT() *MemberAppUsecase_Expecter {
	return &MemberAppUsecase_Expecter{mock: &_m.Mock}
}

// GetMe provides a mock function with given fields: ctx, claim
func (_m *MemberAppUsecase) GetMe(ctx context.Context, claim domain.JWTClaimUser) response.Base {
	ret := _m.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, domain.JWTClaimUser) response.Base); ok {
		r0 = rf(ctx, claim)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MemberAppUsecase_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - claim domain.JWTClaimUser
func (_e *MemberAppUsecase_Expecter) GetMe(ctx interface{}, claim interface{}) *MemberAppUsecase_GetMe_Call {
	return &MemberAppUsecase_GetMe_Call{Call: _e.mock.On("GetMe", ctx, claim)}
}

func (_c *MemberAppUsecase_GetMe_Call) Run(run func(ctx context.Context, claim domain.JWTClaimUser)) *MemberAppUsecase_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JWTClaimUser))
	})
	return _c
}

func (_c *MemberAppUsecase_GetMe_Call) Return(_a0 response.Base) *MemberAppUsecase_GetMe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_GetMe_Call) RunAndReturn(run func(context.Context, domain.JWTClaimUser) response.Base) *MemberAppUsecase_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, payload
func (_m *MemberAppUsecase) Login(ctx context.Context, payload request_model.LoginRequest) response.Base {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.LoginRequest) response.Base); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MemberAppUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - payload request_model.LoginRequest
func (_e *MemberAppUsecase_Expecter) Login(ctx interface{}, payload interface{}) *MemberAppUsecase_Login_Call {
	return &MemberAppUsecase_Login_Call{Call: _e.mock.On("Login", ctx, payload)}
}

func (_c *MemberAppUsecase_Login_Call) Run(run func(ctx context.Context, payload request_model.LoginRequest)) *MemberAppUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.LoginRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_Login_Call) Return(_a0 response.Base) *MemberAppUsecase_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_Login_Call) RunAndReturn(run func(context.Context, request_model.LoginRequest) response.Base) *MemberAppUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, payload
func (_m *MemberAppUsecase) Register(ctx context.Context, payload request_model.RegisterRequest) response.Base {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.RegisterRequest) response.Base); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MemberAppUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - payload request_model.RegisterRequest
func (_e *MemberAppUsecase_Expecter) Register(ctx interface{}, payload interface{}) *MemberAppUsecase_Register_Call {
	return &MemberAppUsecase_Register_Call{Call: _e.mock.On("Register", ctx, payload)}
}

func (_c *MemberAppUsecase_Register_Call) Run(run func(ctx context.Context, payload request_model.RegisterRequest)) *MemberAppUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.RegisterRequest))
	})
	return _c
}

func (_c *MemberAppUsecase_Register_Call) Return(_a0 response.Base) *MemberAppUsecase_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_Register_Call) RunAndReturn(run func(context.Context, request_model.RegisterRequest) response.Base) *MemberAppUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SampleUserDetail provides a mock function with given fields: ctx, claim, id
func (_m *MemberAppUsecase) SampleUserDetail(ctx context.Context, claim domain.JWTClaimUser, id string) response.Base {
	ret := _m.Called(ctx, claim, id)

	if len(ret) == 0 {
		panic("no return value specified for SampleUserDetail")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, domain.JWTClaimUser, string) response.Base); ok {
		r0 = rf(ctx, claim, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_SampleUserDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SampleUserDetail'
type MemberAppUsecase_SampleUserDetail_Call struct {
	*mock.Call
}

// SampleUserDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - claim domain.JWTClaimUser
//   - id string
func (_e *MemberAppUsecase_Expecter) SampleUserDetail(ctx interface{}, claim interface{}, id interface{}) *MemberAppUsecase_SampleUserDetail_Call {
	return &MemberAppUsecase_SampleUserDetail_Call{Call: _e.mock.On("SampleUserDetail", ctx, claim, id)}
}

func (_c *MemberAppUsecase_SampleUserDetail_Call) Run(run func(ctx context.Context, claim domain.JWTClaimUser, id string)) *MemberAppUsecase_SampleUserDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JWTClaimUser), args[2].(string))
	})
	return _c
}

func (_c *MemberAppUsecase_SampleUserDetail_Call) Return(_a0 response.Base) *MemberAppUsecase_SampleUserDetail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_SampleUserDetail_Call) RunAndReturn(run func(context.Context, domain.JWTClaimUser, string) response.Base) *MemberAppUsecase_SampleUserDetail_Call {
	_c.Call.Return(run)
	return _c
}

// SampleUserExport provides a mock function with given fields: ctx, claim, query
func (_m *MemberAppUsecase) SampleUserExport(ctx context.Context, claim domain.JWTClaimUser, query url.Values) response.Base {
	ret := _m.Called(ctx, claim, query)

	if len(ret) == 0 {
		panic("no return value specified for SampleUserExport")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, domain.JWTClaimUser, url.Values) response.Base); ok {
		r0 = rf(ctx, claim, query)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_SampleUserExport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SampleUserExport'
type MemberAppUsecase_SampleUserExport_Call struct {
	*mock.Call
}

// SampleUserExport is a helper method to define mock.On call
//   - ctx context.Context
//   - claim domain.JWTClaimUser
//   - query url.Values
func (_e *MemberAppUsecase_Expecter) SampleUserExport(ctx interface{}, claim interface{}, query interface{}) *MemberAppUsecase_SampleUserExport_Call {
	return &MemberAppUsecase_SampleUserExport_Call{Call: _e.mock.On("SampleUserExport", ctx, claim, query)}
}

func (_c *MemberAppUsecase_SampleUserExport_Call) Run(run func(ctx context.Context, claim domain.JWTClaimUser, query url.Values)) *MemberAppUsecase_SampleUserExport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JWTClaimUser), args[2].(url.Values))
	})
	return _c
}

func (_c *MemberAppUsecase_SampleUserExport_Call) Return(_a0 response.Base) *MemberAppUsecase_SampleUserExport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_SampleUserExport_Call) RunAndReturn(run func(context.Context, domain.JWTClaimUser, url.Values) response.Base) *MemberAppUsecase_SampleUserExport_Call {
	_c.Call.Return(run)
	return _c
}

// SampleUserList provides a mock function with given fields: ctx, claim, query
func (_m *MemberAppUsecase) SampleUserList(ctx context.Context, claim domain.JWTClaimUser, query url.Values) response.Base {
	ret := _m.Called(ctx, claim, query)

	if len(ret) == 0 {
		panic("no return value specified for SampleUserList")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, domain.JWTClaimUser, url.Values) response.Base); ok {
		r0 = rf(ctx, claim, query)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// MemberAppUsecase_SampleUserList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SampleUserList'
type MemberAppUsecase_SampleUserList_Call struct {
	*mock.Call
}

// SampleUserList is a helper method to define mock.On call
//   - ctx context.Context
//   - claim domain.JWTClaimUser
//   - query url.Values
func (_e *MemberAppUsecase_Expecter) SampleUserList(ctx interface{}, claim interface{}, query interface{}) *MemberAppUsecase_SampleUserList_Call {
	return &MemberAppUsecase_SampleUserList_Call{Call: _e.mock.On("SampleUserList", ctx, claim, query)}
}

func (_c *MemberAppUsecase_SampleUserList_Call) Run(run func(ctx context.Context, claim domain.JWTClaimUser, query url.Values)) *MemberAppUsecase_SampleUserList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JWTClaimUser), args[2].(url.Values))
	})
	return _c
}

func (_c *MemberAppUsecase_SampleUserList_Call) Return(_a0 response.Base) *MemberAppUsecase_SampleUserList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberAppUsecase_SampleUserList_Call) RunAndReturn(run func(context.Context, domain.JWTClaimUser, url.Values) response.Base) *MemberAppUsecase_SampleUserList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberAppUsecase creates a new instance of MemberAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberAppUsecase {
	mock := &MemberAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
