// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MessageBroker is an autogenerated mock type for the MessageBroker type
type MessageBroker struct {
	mock.Mock
}

type MessageBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageBroker) EXPECT() *MessageBroker_Expecter {
	return &MessageBroker_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MessageBroker) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageBroker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MessageBroker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MessageBroker_Expecter) Close() *MessageBroker_Close_Call {
	return &MessageBroker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MessageBroker_Close_Call) Run(run func()) *MessageBroker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageBroker_Close_Call) Return(_a0 error) *MessageBroker_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageBroker_Close_Call) RunAndReturn(run func() error) *MessageBroker_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function with given fields: ctx, queueName, handler
func (_m *MessageBroker) Consume(ctx context.Context, queueName string, handler func([]byte) error) error {
	ret := _m.Called(ctx, queueName, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func([]byte) error) error); ok {
		r0 = rf(ctx, queueName, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageBroker_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MessageBroker_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
//   - handler func([]byte) error
func (_e *MessageBroker_Expecter) Consume(ctx interface{}, queueName interface{}, handler interface{}) *MessageBroker_Consume_Call {
	return &MessageBroker_Consume_Call{Call: _e.mock.On("Consume", ctx, queueName, handler)}
}

func (_c *MessageBroker_Consume_Call) Run(run func(ctx context.Context, queueName string, handler func([]byte) error)) *MessageBroker_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func([]byte) error))
	})
	return _c
}

func (_c *MessageBroker_Consume_Call) Return(_a0 error) *MessageBroker_Consume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageBroker_Consume_Call) RunAndReturn(run func(context.Context, string, func([]byte) error) error) *MessageBroker_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, queueName, message
func (_m *MessageBroker) Publish(ctx context.Context, queueName string, message interface{}) error {
	ret := _m.Called(ctx, queueName, message)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, queueName, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageBroker_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MessageBroker_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
//   - message interface{}
func (_e *MessageBroker_Expecter) Publish(ctx interface{}, queueName interface{}, message interface{}) *MessageBroker_Publish_Call {
	return &MessageBroker_Publish_Call{Call: _e.mock.On("Publish", ctx, queueName, message)}
}

func (_c *MessageBroker_Publish_Call) Run(run func(ctx context.Context, queueName string, message interface{})) *MessageBroker_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MessageBroker_Publish_Call) Return(_a0 error) *MessageBroker_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageBroker_Publish_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MessageBroker_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageBroker creates a new instance of MessageBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageBroker {
	mock := &MessageBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
