// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"
	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// ProvinsiAppUsecase is an autogenerated mock type for the ProvinsiAppUsecase type
type ProvinsiAppUsecase struct {
	mock.Mock
}

type ProvinsiAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ProvinsiAppUsecase) EXPECT() *ProvinsiAppUsecase_Expecter {
	return &ProvinsiAppUsecase_Expecter{mock: &_m.Mock}
}

// FetchAll provides a mock function with given fields: ctx, filter
func (_m *ProvinsiAppUsecase) FetchAll(ctx context.Context, filter gorm_model.ProvinsiFilter) response.Base {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, gorm_model.ProvinsiFilter) response.Base); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// ProvinsiAppUsecase_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type ProvinsiAppUsecase_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter gorm_model.ProvinsiFilter
func (_e *ProvinsiAppUsecase_Expecter) FetchAll(ctx interface{}, filter interface{}) *ProvinsiAppUsecase_FetchAll_Call {
	return &ProvinsiAppUsecase_FetchAll_Call{Call: _e.mock.On("FetchAll", ctx, filter)}
}

func (_c *ProvinsiAppUsecase_FetchAll_Call) Run(run func(ctx context.Context, filter gorm_model.ProvinsiFilter)) *ProvinsiAppUsecase_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gorm_model.ProvinsiFilter))
	})
	return _c
}

func (_c *ProvinsiAppUsecase_FetchAll_Call) Return(_a0 response.Base) *ProvinsiAppUsecase_FetchAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProvinsiAppUsecase_FetchAll_Call) RunAndReturn(run func(context.Context, gorm_model.ProvinsiFilter) response.Base) *ProvinsiAppUsecase_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// FetchData provides a mock function with given fields: ctx, id
func (_m *ProvinsiAppUsecase) FetchData(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchData")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// ProvinsiAppUsecase_FetchData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchData'
type ProvinsiAppUsecase_FetchData_Call struct {
	*mock.Call
}

// FetchData is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ProvinsiAppUsecase_Expecter) FetchData(ctx interface{}, id interface{}) *ProvinsiAppUsecase_FetchData_Call {
	return &ProvinsiAppUsecase_FetchData_Call{Call: _e.mock.On("FetchData", ctx, id)}
}

func (_c *ProvinsiAppUsecase_FetchData_Call) Run(run func(ctx context.Context, id string)) *ProvinsiAppUsecase_FetchData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProvinsiAppUsecase_FetchData_Call) Return(_a0 response.Base) *ProvinsiAppUsecase_FetchData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProvinsiAppUsecase_FetchData_Call) RunAndReturn(run func(context.Context, string) response.Base) *ProvinsiAppUsecase_FetchData_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvinsiAppUsecase creates a new instance of ProvinsiAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvinsiAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProvinsiAppUsecase {
	mock := &ProvinsiAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
