// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"

	mock "github.com/stretchr/testify/mock"

	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"

	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
)

// RecruitmentStatusAppUsecase is an autogenerated mock type for the RecruitmentStatusAppUsecase type
type RecruitmentStatusAppUsecase struct {
	mock.Mock
}

type RecruitmentStatusAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *RecruitmentStatusAppUsecase) EXPECT() *RecruitmentStatusAppUsecase_Expecter {
	return &RecruitmentStatusAppUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *RecruitmentStatusAppUsecase) Create(ctx context.Context, req request_model.CreateRecruitmentStatusRequest) response.Base {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.CreateRecruitmentStatusRequest) response.Base); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// RecruitmentStatusAppUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RecruitmentStatusAppUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.CreateRecruitmentStatusRequest
func (_e *RecruitmentStatusAppUsecase_Expecter) Create(ctx interface{}, req interface{}) *RecruitmentStatusAppUsecase_Create_Call {
	return &RecruitmentStatusAppUsecase_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *RecruitmentStatusAppUsecase_Create_Call) Run(run func(ctx context.Context, req request_model.CreateRecruitmentStatusRequest)) *RecruitmentStatusAppUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.CreateRecruitmentStatusRequest))
	})
	return _c
}

func (_c *RecruitmentStatusAppUsecase_Create_Call) Return(_a0 response.Base) *RecruitmentStatusAppUsecase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecruitmentStatusAppUsecase_Create_Call) RunAndReturn(run func(context.Context, request_model.CreateRecruitmentStatusRequest) response.Base) *RecruitmentStatusAppUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *RecruitmentStatusAppUsecase) Delete(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// RecruitmentStatusAppUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RecruitmentStatusAppUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RecruitmentStatusAppUsecase_Expecter) Delete(ctx interface{}, id interface{}) *RecruitmentStatusAppUsecase_Delete_Call {
	return &RecruitmentStatusAppUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *RecruitmentStatusAppUsecase_Delete_Call) Run(run func(ctx context.Context, id string)) *RecruitmentStatusAppUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RecruitmentStatusAppUsecase_Delete_Call) Return(_a0 response.Base) *RecruitmentStatusAppUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecruitmentStatusAppUsecase_Delete_Call) RunAndReturn(run func(context.Context, string) response.Base) *RecruitmentStatusAppUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAll provides a mock function with given fields: ctx, page, limit, cursor, filter
func (_m *RecruitmentStatusAppUsecase) FetchAll(ctx context.Context, page int64, limit int64, cursor string, filter gorm_model.RecruitmentStatusFilter) response.Base {
	ret := _m.Called(ctx, page, limit, cursor, filter)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, gorm_model.RecruitmentStatusFilter) response.Base); ok {
		r0 = rf(ctx, page, limit, cursor, filter)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// RecruitmentStatusAppUsecase_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type RecruitmentStatusAppUsecase_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - cursor string
//   - filter gorm_model.RecruitmentStatusFilter
func (_e *RecruitmentStatusAppUsecase_Expecter) FetchAll(ctx interface{}, page interface{}, limit interface{}, cursor interface{}, filter interface{}) *RecruitmentStatusAppUsecase_FetchAll_Call {
	return &RecruitmentStatusAppUsecase_FetchAll_Call{Call: _e.mock.On("FetchAll", ctx, page, limit, cursor, filter)}
}

func (_c *RecruitmentStatusAppUsecase_FetchAll_Call) Run(run func(ctx context.Context, page int64, limit int64, cursor string, filter gorm_model.RecruitmentStatusFilter)) *RecruitmentStatusAppUsecase_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string), args[4].(gorm_model.RecruitmentStatusFilter))
	})
	return _c
}

func (_c *RecruitmentStatusAppUsecase_FetchAll_Call) Return(_a0 response.Base) *RecruitmentStatusAppUsecase_FetchAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecruitmentStatusAppUsecase_FetchAll_Call) RunAndReturn(run func(context.Context, int64, int64, string, gorm_model.RecruitmentStatusFilter) response.Base) *RecruitmentStatusAppUsecase_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// FetchData provides a mock function with given fields: ctx, id
func (_m *RecruitmentStatusAppUsecase) FetchData(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchData")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// RecruitmentStatusAppUsecase_FetchData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchData'
type RecruitmentStatusAppUsecase_FetchData_Call struct {
	*mock.Call
}

// FetchData is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RecruitmentStatusAppUsecase_Expecter) FetchData(ctx interface{}, id interface{}) *RecruitmentStatusAppUsecase_FetchData_Call {
	return &RecruitmentStatusAppUsecase_FetchData_Call{Call: _e.mock.On("FetchData", ctx, id)}
}

func (_c *RecruitmentStatusAppUsecase_FetchData_Call) Run(run func(ctx context.Context, id string)) *RecruitmentStatusAppUsecase_FetchData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RecruitmentStatusAppUsecase_FetchData_Call) Return(_a0 response.Base) *RecruitmentStatusAppUsecase_FetchData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecruitmentStatusAppUsecase_FetchData_Call) RunAndReturn(run func(context.Context, string) response.Base) *RecruitmentStatusAppUsecase_FetchData_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *RecruitmentStatusAppUsecase) Update(ctx context.Context, id string, req request_model.UpdateRecruitmentStatusRequest) response.Base {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.UpdateRecruitmentStatusRequest) response.Base); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// RecruitmentStatusAppUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RecruitmentStatusAppUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req request_model.UpdateRecruitmentStatusRequest
func (_e *RecruitmentStatusAppUsecase_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *RecruitmentStatusAppUsecase_Update_Call {
	return &RecruitmentStatusAppUsecase_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *RecruitmentStatusAppUsecase_Update_Call) Run(run func(ctx context.Context, id string, req request_model.UpdateRecruitmentStatusRequest)) *RecruitmentStatusAppUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.UpdateRecruitmentStatusRequest))
	})
	return _c
}

func (_c *RecruitmentStatusAppUsecase_Update_Call) Return(_a0 response.Base) *RecruitmentStatusAppUsecase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecruitmentStatusAppUsecase_Update_Call) RunAndReturn(run func(context.Context, string, request_model.UpdateRecruitmentStatusRequest) response.Base) *RecruitmentStatusAppUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecruitmentStatusAppUsecase creates a new instance of RecruitmentStatusAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecruitmentStatusAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecruitmentStatusAppUsecase {
	mock := &RecruitmentStatusAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
