// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"

	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
)

// RequestAppUsecase is an autogenerated mock type for the RequestAppUsecase type
type RequestAppUsecase struct {
	mock.Mock
}

type RequestAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestAppUsecase) EXPECT() *RequestAppUsecase_Expecter {
	return &RequestAppUsecase_Expecter{mock: &_m.Mock}
}

// CreateByEmployee provides a mock function with given fields: ctx, employeeID, req
func (_m *RequestAppUsecase) CreateByEmployee(ctx context.Context, employeeID string, req request_model.CreateRequestRequest) response.Base {
	ret := _m.Called(ctx, employeeID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateByEmployee")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.CreateRequestRequest) response.Base); ok {
		r0 = rf(ctx, employeeID, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// RequestAppUsecase_CreateByEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateByEmployee'
type RequestAppUsecase_CreateByEmployee_Call struct {
	*mock.Call
}

// CreateByEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID string
//   - req request_model.CreateRequestRequest
func (_e *RequestAppUsecase_Expecter) CreateByEmployee(ctx interface{}, employeeID interface{}, req interface{}) *RequestAppUsecase_CreateByEmployee_Call {
	return &RequestAppUsecase_CreateByEmployee_Call{Call: _e.mock.On("CreateByEmployee", ctx, employeeID, req)}
}

func (_c *RequestAppUsecase_CreateByEmployee_Call) Run(run func(ctx context.Context, employeeID string, req request_model.CreateRequestRequest)) *RequestAppUsecase_CreateByEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.CreateRequestRequest))
	})
	return _c
}

func (_c *RequestAppUsecase_CreateByEmployee_Call) Return(_a0 response.Base) *RequestAppUsecase_CreateByEmployee_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestAppUsecase_CreateByEmployee_Call) RunAndReturn(run func(context.Context, string, request_model.CreateRequestRequest) response.Base) *RequestAppUsecase_CreateByEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// NewRequestAppUsecase creates a new instance of RequestAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestAppUsecase {
	mock := &RequestAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
