// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"
	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"
	response "github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	mock "github.com/stretchr/testify/mock"
)

// SectorAppUsecase is an autogenerated mock type for the SectorAppUsecase type
type SectorAppUsecase struct {
	mock.Mock
}

type SectorAppUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *SectorAppUsecase) EXPECT() *SectorAppUsecase_Expecter {
	return &SectorAppUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *SectorAppUsecase) Create(ctx context.Context, req request_model.CreateSectorRequest) response.Base {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, request_model.CreateSectorRequest) response.Base); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// SectorAppUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SectorAppUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.CreateSectorRequest
func (_e *SectorAppUsecase_Expecter) Create(ctx interface{}, req interface{}) *SectorAppUsecase_Create_Call {
	return &SectorAppUsecase_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *SectorAppUsecase_Create_Call) Run(run func(ctx context.Context, req request_model.CreateSectorRequest)) *SectorAppUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.CreateSectorRequest))
	})
	return _c
}

func (_c *SectorAppUsecase_Create_Call) Return(_a0 response.Base) *SectorAppUsecase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SectorAppUsecase_Create_Call) RunAndReturn(run func(context.Context, request_model.CreateSectorRequest) response.Base) *SectorAppUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SectorAppUsecase) Delete(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// SectorAppUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SectorAppUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SectorAppUsecase_Expecter) Delete(ctx interface{}, id interface{}) *SectorAppUsecase_Delete_Call {
	return &SectorAppUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SectorAppUsecase_Delete_Call) Run(run func(ctx context.Context, id string)) *SectorAppUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SectorAppUsecase_Delete_Call) Return(_a0 response.Base) *SectorAppUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SectorAppUsecase_Delete_Call) RunAndReturn(run func(context.Context, string) response.Base) *SectorAppUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAll provides a mock function with given fields: ctx, page, limit, cursor, filter
func (_m *SectorAppUsecase) FetchAll(ctx context.Context, page int64, limit int64, cursor string, filter gorm_model.SectorFilter) response.Base {
	ret := _m.Called(ctx, page, limit, cursor, filter)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, gorm_model.SectorFilter) response.Base); ok {
		r0 = rf(ctx, page, limit, cursor, filter)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// SectorAppUsecase_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type SectorAppUsecase_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - limit int64
//   - cursor string
//   - filter gorm_model.SectorFilter
func (_e *SectorAppUsecase_Expecter) FetchAll(ctx interface{}, page interface{}, limit interface{}, cursor interface{}, filter interface{}) *SectorAppUsecase_FetchAll_Call {
	return &SectorAppUsecase_FetchAll_Call{Call: _e.mock.On("FetchAll", ctx, page, limit, cursor, filter)}
}

func (_c *SectorAppUsecase_FetchAll_Call) Run(run func(ctx context.Context, page int64, limit int64, cursor string, filter gorm_model.SectorFilter)) *SectorAppUsecase_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string), args[4].(gorm_model.SectorFilter))
	})
	return _c
}

func (_c *SectorAppUsecase_FetchAll_Call) Return(_a0 response.Base) *SectorAppUsecase_FetchAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SectorAppUsecase_FetchAll_Call) RunAndReturn(run func(context.Context, int64, int64, string, gorm_model.SectorFilter) response.Base) *SectorAppUsecase_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// FetchData provides a mock function with given fields: ctx, id
func (_m *SectorAppUsecase) FetchData(ctx context.Context, id string) response.Base {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchData")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string) response.Base); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// SectorAppUsecase_FetchData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchData'
type SectorAppUsecase_FetchData_Call struct {
	*mock.Call
}

// FetchData is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SectorAppUsecase_Expecter) FetchData(ctx interface{}, id interface{}) *SectorAppUsecase_FetchData_Call {
	return &SectorAppUsecase_FetchData_Call{Call: _e.mock.On("FetchData", ctx, id)}
}

func (_c *SectorAppUsecase_FetchData_Call) Run(run func(ctx context.Context, id string)) *SectorAppUsecase_FetchData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SectorAppUsecase_FetchData_Call) Return(_a0 response.Base) *SectorAppUsecase_FetchData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SectorAppUsecase_FetchData_Call) RunAndReturn(run func(context.Context, string) response.Base) *SectorAppUsecase_FetchData_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *SectorAppUsecase) Update(ctx context.Context, id string, req request_model.UpdateSectorRequest) response.Base {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 response.Base
	if rf, ok := ret.Get(0).(func(context.Context, string, request_model.UpdateSectorRequest) response.Base); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(response.Base)
	}

	return r0
}

// SectorAppUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SectorAppUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req request_model.UpdateSectorRequest
func (_e *SectorAppUsecase_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *SectorAppUsecase_Update_Call {
	return &SectorAppUsecase_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *SectorAppUsecase_Update_Call) Run(run func(ctx context.Context, id string, req request_model.UpdateSectorRequest)) *SectorAppUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request_model.UpdateSectorRequest))
	})
	return _c
}

func (_c *SectorAppUsecase_Update_Call) Return(_a0 response.Base) *SectorAppUsecase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SectorAppUsecase_Update_Call) RunAndReturn(run func(context.Context, string, request_model.UpdateSectorRequest) response.Base) *SectorAppUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewSectorAppUsecase creates a new instance of SectorAppUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSectorAppUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SectorAppUsecase {
	mock := &SectorAppUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
