// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/sql"

	sqlx "github.com/jmoiron/sqlx"
)

// SqlRepo is an autogenerated mock type for the SqlRepo type
type SqlRepo struct {
	mock.Mock
}

type SqlRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SqlRepo) EXPECT() *SqlRepo_Expecter {
	return &SqlRepo_Expecter{mock: &_m.Mock}
}

// CountUser provides a mock function with given fields: ctx, options
func (_m *SqlRepo) CountUser(ctx context.Context, options sql_model.UserFilter) int64 {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for CountUser")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, sql_model.UserFilter) int64); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// SqlRepo_CountUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUser'
type SqlRepo_CountUser_Call struct {
	*mock.Call
}

// CountUser is a helper method to define mock.On call
//   - ctx context.Context
//   - options sql_model.UserFilter
func (_e *SqlRepo_Expecter) CountUser(ctx interface{}, options interface{}) *SqlRepo_CountUser_Call {
	return &SqlRepo_CountUser_Call{Call: _e.mock.On("CountUser", ctx, options)}
}

func (_c *SqlRepo_CountUser_Call) Run(run func(ctx context.Context, options sql_model.UserFilter)) *SqlRepo_CountUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sql_model.UserFilter))
	})
	return _c
}

func (_c *SqlRepo_CountUser_Call) Return(_a0 int64) *SqlRepo_CountUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SqlRepo_CountUser_Call) RunAndReturn(run func(context.Context, sql_model.UserFilter) int64) *SqlRepo_CountUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, model
func (_m *SqlRepo) CreateUser(ctx context.Context, model *sql_model.User) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql_model.User) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SqlRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type SqlRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - model *sql_model.User
func (_e *SqlRepo_Expecter) CreateUser(ctx interface{}, model interface{}) *SqlRepo_CreateUser_Call {
	return &SqlRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, model)}
}

func (_c *SqlRepo_CreateUser_Call) Run(run func(ctx context.Context, model *sql_model.User)) *SqlRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql_model.User))
	})
	return _c
}

func (_c *SqlRepo_CreateUser_Call) Return(err error) *SqlRepo_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SqlRepo_CreateUser_Call) RunAndReturn(run func(context.Context, *sql_model.User) error) *SqlRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOneUser provides a mock function with given fields: ctx, options
func (_m *SqlRepo) FetchOneUser(ctx context.Context, options sql_model.UserFilter) (*sql_model.User, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for FetchOneUser")
	}

	var r0 *sql_model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_model.UserFilter) (*sql_model.User, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_model.UserFilter) *sql_model.User); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql_model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_model.UserFilter) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SqlRepo_FetchOneUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOneUser'
type SqlRepo_FetchOneUser_Call struct {
	*mock.Call
}

// FetchOneUser is a helper method to define mock.On call
//   - ctx context.Context
//   - options sql_model.UserFilter
func (_e *SqlRepo_Expecter) FetchOneUser(ctx interface{}, options interface{}) *SqlRepo_FetchOneUser_Call {
	return &SqlRepo_FetchOneUser_Call{Call: _e.mock.On("FetchOneUser", ctx, options)}
}

func (_c *SqlRepo_FetchOneUser_Call) Run(run func(ctx context.Context, options sql_model.UserFilter)) *SqlRepo_FetchOneUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sql_model.UserFilter))
	})
	return _c
}

func (_c *SqlRepo_FetchOneUser_Call) Return(_a0 *sql_model.User, _a1 error) *SqlRepo_FetchOneUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SqlRepo_FetchOneUser_Call) RunAndReturn(run func(context.Context, sql_model.UserFilter) (*sql_model.User, error)) *SqlRepo_FetchOneUser_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUser provides a mock function with given fields: ctx, options
func (_m *SqlRepo) FetchUser(ctx context.Context, options sql_model.UserFilter) (*sqlx.Rows, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for FetchUser")
	}

	var r0 *sqlx.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_model.UserFilter) (*sqlx.Rows, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_model.UserFilter) *sqlx.Rows); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_model.UserFilter) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SqlRepo_FetchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUser'
type SqlRepo_FetchUser_Call struct {
	*mock.Call
}

// FetchUser is a helper method to define mock.On call
//   - ctx context.Context
//   - options sql_model.UserFilter
func (_e *SqlRepo_Expecter) FetchUser(ctx interface{}, options interface{}) *SqlRepo_FetchUser_Call {
	return &SqlRepo_FetchUser_Call{Call: _e.mock.On("FetchUser", ctx, options)}
}

func (_c *SqlRepo_FetchUser_Call) Run(run func(ctx context.Context, options sql_model.UserFilter)) *SqlRepo_FetchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sql_model.UserFilter))
	})
	return _c
}

func (_c *SqlRepo_FetchUser_Call) Return(_a0 *sqlx.Rows, _a1 error) *SqlRepo_FetchUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SqlRepo_FetchUser_Call) RunAndReturn(run func(context.Context, sql_model.UserFilter) (*sqlx.Rows, error)) *SqlRepo_FetchUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewSqlRepo creates a new instance of SqlRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqlRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SqlRepo {
	mock := &SqlRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
