// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeSearchServiceServer is an autogenerated mock type for the UnsafeSearchServiceServer type
type UnsafeSearchServiceServer struct {
	mock.Mock
}

type UnsafeSearchServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeSearchServiceServer) EXPECT() *UnsafeSearchServiceServer_Expecter {
	return &UnsafeSearchServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedSearchServiceServer provides a mock function with no fields
func (_m *UnsafeSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {
	_m.Called()
}

// UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSearchServiceServer'
type UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSearchServiceServer is a helper method to define mock.On call
func (_e *UnsafeSearchServiceServer_Expecter) mustEmbedUnimplementedSearchServiceServer() *UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call {
	return &UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSearchServiceServer")}
}

func (_c *UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call) Run(run func()) *UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call) Return() *UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call) RunAndReturn(run func()) *UnsafeSearchServiceServer_mustEmbedUnimplementedSearchServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewUnsafeSearchServiceServer creates a new instance of UnsafeSearchServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeSearchServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeSearchServiceServer {
	mock := &UnsafeSearchServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
