// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"
	request_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/request"
	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

type Usecase_Expecter struct {
	mock *mock.Mock
}

func (_m *Usecase) EXPECT() *Usecase_Expecter {
	return &Usecase_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx
func (_m *Usecase) Fetch(ctx context.Context) (*gorm_model.SystemSetting, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *gorm_model.SystemSetting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm_model.SystemSetting, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm_model.SystemSetting); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm_model.SystemSetting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Usecase_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type Usecase_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Usecase_Expecter) Fetch(ctx interface{}) *Usecase_Fetch_Call {
	return &Usecase_Fetch_Call{Call: _e.mock.On("Fetch", ctx)}
}

func (_c *Usecase_Fetch_Call) Run(run func(ctx context.Context)) *Usecase_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Usecase_Fetch_Call) Return(_a0 *gorm_model.SystemSetting, _a1 error) *Usecase_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Usecase_Fetch_Call) RunAndReturn(run func(context.Context) (*gorm_model.SystemSetting, error)) *Usecase_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *Usecase) Update(ctx context.Context, req request_model.UpdateSystemSettingRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request_model.UpdateSystemSettingRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Usecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Usecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req request_model.UpdateSystemSettingRequest
func (_e *Usecase_Expecter) Update(ctx interface{}, req interface{}) *Usecase_Update_Call {
	return &Usecase_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *Usecase_Update_Call) Run(run func(ctx context.Context, req request_model.UpdateSystemSettingRequest)) *Usecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request_model.UpdateSystemSettingRequest))
	})
	return _c
}

func (_c *Usecase_Update_Call) Return(_a0 error) *Usecase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Usecase_Update_Call) RunAndReturn(run func(context.Context, request_model.UpdateSystemSettingRequest) error) *Usecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCVTemplate provides a mock function with given fields: ctx, fileHeader
func (_m *Usecase) UploadCVTemplate(ctx context.Context, fileHeader *multipart.FileHeader) (string, error) {
	ret := _m.Called(ctx, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for UploadCVTemplate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) (string, error)); ok {
		return rf(ctx, fileHeader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) string); ok {
		r0 = rf(ctx, fileHeader)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, fileHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Usecase_UploadCVTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCVTemplate'
type Usecase_UploadCVTemplate_Call struct {
	*mock.Call
}

// UploadCVTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - fileHeader *multipart.FileHeader
func (_e *Usecase_Expecter) UploadCVTemplate(ctx interface{}, fileHeader interface{}) *Usecase_UploadCVTemplate_Call {
	return &Usecase_UploadCVTemplate_Call{Call: _e.mock.On("UploadCVTemplate", ctx, fileHeader)}
}

func (_c *Usecase_UploadCVTemplate_Call) Run(run func(ctx context.Context, fileHeader *multipart.FileHeader)) *Usecase_UploadCVTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*multipart.FileHeader))
	})
	return _c
}

func (_c *Usecase_UploadCVTemplate_Call) Return(_a0 string, _a1 error) *Usecase_UploadCVTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Usecase_UploadCVTemplate_Call) RunAndReturn(run func(context.Context, *multipart.FileHeader) (string, error)) *Usecase_UploadCVTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
