// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichmentRequest) Reset() {
	*x = EnrichmentRequest{}
	mi := &file_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichmentRequest) ProtoMessage() {}

func (x *EnrichmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichmentRequest.ProtoReflect.Descriptor instead.
func (*EnrichmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichmentRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type EnrichmentData struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	UserId                        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobRoles                      []string               `protobuf:"bytes,2,rep,name=job_roles,json=jobRoles,proto3" json:"job_roles,omitempty"`
	CandidateLevel                string                 `protobuf:"bytes,3,opt,name=candidate_level,json=candidateLevel,proto3" json:"candidate_level,omitempty"`
	AvgWorkQuality                float64                `protobuf:"fixed64,4,opt,name=avg_work_quality,json=avgWorkQuality,proto3" json:"avg_work_quality,omitempty"`
	AvgTimeliness                 float64                `protobuf:"fixed64,5,opt,name=avg_timeliness,json=avgTimeliness,proto3" json:"avg_timeliness,omitempty"`
	AvgCommunicationCollaboration float64                `protobuf:"fixed64,6,opt,name=avg_communication_collaboration,json=avgCommunicationCollaboration,proto3" json:"avg_communication_collaboration,omitempty"`
	AvgProblemSolvingInitiative   float64                `protobuf:"fixed64,7,opt,name=avg_problem_solving_initiative,json=avgProblemSolvingInitiative,proto3" json:"avg_problem_solving_initiative,omitempty"`
	HasScore                      bool                   `protobuf:"varint,8,opt,name=has_score,json=hasScore,proto3" json:"has_score,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *EnrichmentData) Reset() {
	*x = EnrichmentData{}
	mi := &file_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichmentData) ProtoMessage() {}

func (x *EnrichmentData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichmentData.ProtoReflect.Descriptor instead.
func (*EnrichmentData) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichmentData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrichmentData) GetJobRoles() []string {
	if x != nil {
		return x.JobRoles
	}
	return nil
}

func (x *EnrichmentData) GetCandidateLevel() string {
	if x != nil {
		return x.CandidateLevel
	}
	return ""
}

func (x *EnrichmentData) GetAvgWorkQuality() float64 {
	if x != nil {
		return x.AvgWorkQuality
	}
	return 0
}

func (x *EnrichmentData) GetAvgTimeliness() float64 {
	if x != nil {
		return x.AvgTimeliness
	}
	return 0
}

func (x *EnrichmentData) GetAvgCommunicationCollaboration() float64 {
	if x != nil {
		return x.AvgCommunicationCollaboration
	}
	return 0
}

func (x *EnrichmentData) GetAvgProblemSolvingInitiative() float64 {
	if x != nil {
		return x.AvgProblemSolvingInitiative
	}
	return 0
}

func (x *EnrichmentData) GetHasScore() bool {
	if x != nil {
		return x.HasScore
	}
	return false
}

type EnrichmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*EnrichmentData      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichmentResponse) Reset() {
	*x = EnrichmentResponse{}
	mi := &file_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichmentResponse) ProtoMessage() {}

func (x *EnrichmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichmentResponse.ProtoReflect.Descriptor instead.
func (*EnrichmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *EnrichmentResponse) GetData() []*EnrichmentData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       *structpb.Struct       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetContent() *structpb.Struct {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCandidateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Roles           []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Summary         string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	EducationMajor  string                 `protobuf:"bytes,5,opt,name=education_major,json=educationMajor,proto3" json:"education_major,omitempty"`
	Gpa             float64                `protobuf:"fixed64,6,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Location        string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	TechStack       []string               `protobuf:"bytes,8,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`
	YearsExperience int32                  `protobuf:"varint,9,opt,name=years_experience,json=yearsExperience,proto3" json:"years_experience,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCandidateRequest) Reset() {
	*x = UpdateCandidateRequest{}
	mi := &file_proto_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateRequest) ProtoMessage() {}

func (x *UpdateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateRequest.ProtoReflect.Descriptor instead.
func (*UpdateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCandidateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCandidateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCandidateRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UpdateCandidateRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateCandidateRequest) GetEducationMajor() string {
	if x != nil {
		return x.EducationMajor
	}
	return ""
}

func (x *UpdateCandidateRequest) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *UpdateCandidateRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateCandidateRequest) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *UpdateCandidateRequest) GetYearsExperience() int32 {
	if x != nil {
		return x.YearsExperience
	}
	return 0
}

type UpdateCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateResponse) Reset() {
	*x = UpdateCandidateResponse{}
	mi := &file_proto_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateResponse) ProtoMessage() {}

func (x *UpdateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateResponse.ProtoReflect.Descriptor instead.
func (*UpdateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCandidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateCandidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_search_proto protoreflect.FileDescriptor

const file_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x12proto/search.proto\x12\x06search\x1a\x1cgoogle/protobuf/struct.proto\".\n" +
	"\x11EnrichmentRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xea\x02\n" +
	"\x0eEnrichmentData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjob_roles\x18\x02 \x03(\tR\bjobRoles\x12'\n" +
	"\x0fcandidate_level\x18\x03 \x01(\tR\x0ecandidateLevel\x12(\n" +
	"\x10avg_work_quality\x18\x04 \x01(\x01R\x0eavgWorkQuality\x12%\n" +
	"\x0eavg_timeliness\x18\x05 \x01(\x01R\ravgTimeliness\x12F\n" +
	"\x1favg_communication_collaboration\x18\x06 \x01(\x01R\x1davgCommunicationCollaboration\x12C\n" +
	"\x1eavg_problem_solving_initiative\x18\a \x01(\x01R\x1bavgProblemSolvingInitiative\x12\x1b\n" +
	"\thas_score\x18\b \x01(\bR\bhasScore\"@\n" +
	"\x12EnrichmentResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.search.EnrichmentDataR\x04data\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"g\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\acontent\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"Z\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.search.SearchResultR\aresults\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x02\n" +
	"\x16UpdateCandidateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12'\n" +
	"\x0feducation_major\x18\x05 \x01(\tR\x0eeducationMajor\x12\x10\n" +
	"\x03gpa\x18\x06 \x01(\x01R\x03gpa\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\b \x03(\tR\ttechStack\x12)\n" +
	"\x10years_experience\x18\t \x01(\x05R\x0fyearsExperience\"M\n" +
	"\x17UpdateCandidateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x01\n" +
	"\rSearchService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12R\n" +
	"\x0fUpdateCandidate\x12\x1e.search.UpdateCandidateRequest\x1a\x1f.search.UpdateCandidateResponse2^\n" +
	"\x10CandidateService\x12J\n" +
	"\x11GetEnrichmentData\x12\x19.search.EnrichmentRequest\x1a\x1a.search.EnrichmentResponseB\x1bZ\x19gigsourcehub-ai-api/protob\x06proto3"

var (
	file_proto_search_proto_rawDescOnce sync.Once
	file_proto_search_proto_rawDescData []byte
)

func file_proto_search_proto_rawDescGZIP() []byte {
	file_proto_search_proto_rawDescOnce.Do(func() {
		file_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)))
	})
	return file_proto_search_proto_rawDescData
}

var file_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_search_proto_goTypes = []any{
	(*EnrichmentRequest)(nil),       // 0: search.EnrichmentRequest
	(*EnrichmentData)(nil),          // 1: search.EnrichmentData
	(*EnrichmentResponse)(nil),      // 2: search.EnrichmentResponse
	(*SearchRequest)(nil),           // 3: search.SearchRequest
	(*SearchResult)(nil),            // 4: search.SearchResult
	(*SearchResponse)(nil),          // 5: search.SearchResponse
	(*UpdateCandidateRequest)(nil),  // 6: search.UpdateCandidateRequest
	(*UpdateCandidateResponse)(nil), // 7: search.UpdateCandidateResponse
	(*structpb.Struct)(nil),         // 8: google.protobuf.Struct
}
var file_proto_search_proto_depIdxs = []int32{
	1, // 0: search.EnrichmentResponse.data:type_name -> search.EnrichmentData
	8, // 1: search.SearchResult.content:type_name -> google.protobuf.Struct
	4, // 2: search.SearchResponse.results:type_name -> search.SearchResult
	3, // 3: search.SearchService.Search:input_type -> search.SearchRequest
	6, // 4: search.SearchService.UpdateCandidate:input_type -> search.UpdateCandidateRequest
	0, // 5: search.CandidateService.GetEnrichmentData:input_type -> search.EnrichmentRequest
	5, // 6: search.SearchService.Search:output_type -> search.SearchResponse
	7, // 7: search.SearchService.UpdateCandidate:output_type -> search.UpdateCandidateResponse
	2, // 8: search.CandidateService.GetEnrichmentData:output_type -> search.EnrichmentResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_search_proto_init() }
func file_proto_search_proto_init() {
	if File_proto_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_search_proto_goTypes,
		DependencyIndexes: file_proto_search_proto_depIdxs,
		MessageInfos:      file_proto_search_proto_msgTypes,
	}.Build()
	File_proto_search_proto = out.File
	file_proto_search_proto_goTypes = nil
	file_proto_search_proto_depIdxs = nil
}
