syntax = "proto3";

package search;

option go_package = "gigsourcehub-ai-api/proto";

import "google/protobuf/struct.proto";

service SearchService {
  rpc Search (SearchRequest) returns (SearchResponse);
}

service CandidateService {
  rpc GetEnrichmentData (EnrichmentRequest) returns (EnrichmentResponse);
}

message EnrichmentRequest {
  repeated string user_ids = 1;
}

message EnrichmentData {
  string user_id = 1;
  repeated string job_roles = 2;
  string candidate_level = 3;
  double avg_work_quality = 4;
  double avg_timeliness = 5;
  double avg_communication_collaboration = 6;
  double avg_problem_solving_initiative = 7;
  bool has_score = 8;
}

message EnrichmentResponse {
  repeated EnrichmentData data = 1;
}

message SearchRequest {
  string query = 1;
}

message SearchResult {
  string id = 1;
  google.protobuf.Struct content = 2;
  float score = 3;
}

message SearchResponse {
  repeated SearchResult results = 1;
  string message = 2;
}
