// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRolesRequest) Reset() {
	*x = GetJobRolesRequest{}
	mi := &file_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRolesRequest) ProtoMessage() {}

func (x *GetJobRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRolesRequest.ProtoReflect.Descriptor instead.
func (*GetJobRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0}
}

type JobRoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRoleInfo) Reset() {
	*x = JobRoleInfo{}
	mi := &file_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRoleInfo) ProtoMessage() {}

func (x *JobRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRoleInfo.ProtoReflect.Descriptor instead.
func (*JobRoleInfo) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *JobRoleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobRoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetJobRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRoles      []*JobRoleInfo         `protobuf:"bytes,1,rep,name=job_roles,json=jobRoles,proto3" json:"job_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRolesResponse) Reset() {
	*x = GetJobRolesResponse{}
	mi := &file_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRolesResponse) ProtoMessage() {}

func (x *GetJobRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRolesResponse.ProtoReflect.Descriptor instead.
func (*GetJobRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRolesResponse) GetJobRoles() []*JobRoleInfo {
	if x != nil {
		return x.JobRoles
	}
	return nil
}

type GetSectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectorsRequest) Reset() {
	*x = GetSectorsRequest{}
	mi := &file_proto_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectorsRequest) ProtoMessage() {}

func (x *GetSectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectorsRequest.ProtoReflect.Descriptor instead.
func (*GetSectorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{3}
}

type SectorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectorInfo) Reset() {
	*x = SectorInfo{}
	mi := &file_proto_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectorInfo) ProtoMessage() {}

func (x *SectorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectorInfo.ProtoReflect.Descriptor instead.
func (*SectorInfo) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{4}
}

func (x *SectorInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SectorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sectors       []*SectorInfo          `protobuf:"bytes,1,rep,name=sectors,proto3" json:"sectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectorsResponse) Reset() {
	*x = GetSectorsResponse{}
	mi := &file_proto_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectorsResponse) ProtoMessage() {}

func (x *GetSectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectorsResponse.ProtoReflect.Descriptor instead.
func (*GetSectorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{5}
}

func (x *GetSectorsResponse) GetSectors() []*SectorInfo {
	if x != nil {
		return x.Sectors
	}
	return nil
}

type EnrichmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichmentRequest) Reset() {
	*x = EnrichmentRequest{}
	mi := &file_proto_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichmentRequest) ProtoMessage() {}

func (x *EnrichmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichmentRequest.ProtoReflect.Descriptor instead.
func (*EnrichmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{6}
}

func (x *EnrichmentRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type EnrichmentData struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	UserId                        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobRoles                      []string               `protobuf:"bytes,2,rep,name=job_roles,json=jobRoles,proto3" json:"job_roles,omitempty"`
	CandidateLevel                string                 `protobuf:"bytes,3,opt,name=candidate_level,json=candidateLevel,proto3" json:"candidate_level,omitempty"`
	AvgWorkQuality                float64                `protobuf:"fixed64,4,opt,name=avg_work_quality,json=avgWorkQuality,proto3" json:"avg_work_quality,omitempty"`
	AvgTimeliness                 float64                `protobuf:"fixed64,5,opt,name=avg_timeliness,json=avgTimeliness,proto3" json:"avg_timeliness,omitempty"`
	AvgCommunicationCollaboration float64                `protobuf:"fixed64,6,opt,name=avg_communication_collaboration,json=avgCommunicationCollaboration,proto3" json:"avg_communication_collaboration,omitempty"`
	AvgProblemSolvingInitiative   float64                `protobuf:"fixed64,7,opt,name=avg_problem_solving_initiative,json=avgProblemSolvingInitiative,proto3" json:"avg_problem_solving_initiative,omitempty"`
	HasScore                      bool                   `protobuf:"varint,8,opt,name=has_score,json=hasScore,proto3" json:"has_score,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *EnrichmentData) Reset() {
	*x = EnrichmentData{}
	mi := &file_proto_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichmentData) ProtoMessage() {}

func (x *EnrichmentData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichmentData.ProtoReflect.Descriptor instead.
func (*EnrichmentData) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{7}
}

func (x *EnrichmentData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrichmentData) GetJobRoles() []string {
	if x != nil {
		return x.JobRoles
	}
	return nil
}

func (x *EnrichmentData) GetCandidateLevel() string {
	if x != nil {
		return x.CandidateLevel
	}
	return ""
}

func (x *EnrichmentData) GetAvgWorkQuality() float64 {
	if x != nil {
		return x.AvgWorkQuality
	}
	return 0
}

func (x *EnrichmentData) GetAvgTimeliness() float64 {
	if x != nil {
		return x.AvgTimeliness
	}
	return 0
}

func (x *EnrichmentData) GetAvgCommunicationCollaboration() float64 {
	if x != nil {
		return x.AvgCommunicationCollaboration
	}
	return 0
}

func (x *EnrichmentData) GetAvgProblemSolvingInitiative() float64 {
	if x != nil {
		return x.AvgProblemSolvingInitiative
	}
	return 0
}

func (x *EnrichmentData) GetHasScore() bool {
	if x != nil {
		return x.HasScore
	}
	return false
}

type EnrichmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*EnrichmentData      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichmentResponse) Reset() {
	*x = EnrichmentResponse{}
	mi := &file_proto_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichmentResponse) ProtoMessage() {}

func (x *EnrichmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichmentResponse.ProtoReflect.Descriptor instead.
func (*EnrichmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{8}
}

func (x *EnrichmentResponse) GetData() []*EnrichmentData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       *structpb.Struct       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetContent() *structpb.Struct {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{11}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCandidateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Roles           []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Summary         string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	EducationMajor  string                 `protobuf:"bytes,5,opt,name=education_major,json=educationMajor,proto3" json:"education_major,omitempty"`
	Gpa             float64                `protobuf:"fixed64,6,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Location        string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	TechStack       []string               `protobuf:"bytes,8,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`
	YearsExperience int32                  `protobuf:"varint,9,opt,name=years_experience,json=yearsExperience,proto3" json:"years_experience,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCandidateRequest) Reset() {
	*x = UpdateCandidateRequest{}
	mi := &file_proto_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateRequest) ProtoMessage() {}

func (x *UpdateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateRequest.ProtoReflect.Descriptor instead.
func (*UpdateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCandidateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCandidateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCandidateRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UpdateCandidateRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateCandidateRequest) GetEducationMajor() string {
	if x != nil {
		return x.EducationMajor
	}
	return ""
}

func (x *UpdateCandidateRequest) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *UpdateCandidateRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateCandidateRequest) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *UpdateCandidateRequest) GetYearsExperience() int32 {
	if x != nil {
		return x.YearsExperience
	}
	return 0
}

type UpdateCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateResponse) Reset() {
	*x = UpdateCandidateResponse{}
	mi := &file_proto_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateResponse) ProtoMessage() {}

func (x *UpdateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateResponse.ProtoReflect.Descriptor instead.
func (*UpdateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateCandidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateCandidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCVProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CvId          string                 `protobuf:"bytes,1,opt,name=cv_id,json=cvId,proto3" json:"cv_id,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCVProgressRequest) Reset() {
	*x = UpdateCVProgressRequest{}
	mi := &file_proto_search_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCVProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCVProgressRequest) ProtoMessage() {}

func (x *UpdateCVProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCVProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateCVProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCVProgressRequest) GetCvId() string {
	if x != nil {
		return x.CvId
	}
	return ""
}

func (x *UpdateCVProgressRequest) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *UpdateCVProgressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCVProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCVProgressResponse) Reset() {
	*x = UpdateCVProgressResponse{}
	mi := &file_proto_search_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCVProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCVProgressResponse) ProtoMessage() {}

func (x *UpdateCVProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCVProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateCVProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCVProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateCVProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCandidateRequest) Reset() {
	*x = DeleteCandidateRequest{}
	mi := &file_proto_search_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateRequest) ProtoMessage() {}

func (x *DeleteCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateRequest.ProtoReflect.Descriptor instead.
func (*DeleteCandidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCandidateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCandidateResponse) Reset() {
	*x = DeleteCandidateResponse{}
	mi := &file_proto_search_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateResponse) ProtoMessage() {}

func (x *DeleteCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateResponse.ProtoReflect.Descriptor instead.
func (*DeleteCandidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCandidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCandidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_search_proto protoreflect.FileDescriptor

const file_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x12proto/search.proto\x12\x06search\x1a\x1cgoogle/protobuf/struct.proto\"\x14\n" +
	"\x12GetJobRolesRequest\"1\n" +
	"\vJobRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"G\n" +
	"\x13GetJobRolesResponse\x120\n" +
	"\tjob_roles\x18\x01 \x03(\v2\x13.search.JobRoleInfoR\bjobRoles\"\x13\n" +
	"\x11GetSectorsRequest\"0\n" +
	"\n" +
	"SectorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\x12GetSectorsResponse\x12,\n" +
	"\asectors\x18\x01 \x03(\v2\x12.search.SectorInfoR\asectors\".\n" +
	"\x11EnrichmentRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xea\x02\n" +
	"\x0eEnrichmentData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjob_roles\x18\x02 \x03(\tR\bjobRoles\x12'\n" +
	"\x0fcandidate_level\x18\x03 \x01(\tR\x0ecandidateLevel\x12(\n" +
	"\x10avg_work_quality\x18\x04 \x01(\x01R\x0eavgWorkQuality\x12%\n" +
	"\x0eavg_timeliness\x18\x05 \x01(\x01R\ravgTimeliness\x12F\n" +
	"\x1favg_communication_collaboration\x18\x06 \x01(\x01R\x1davgCommunicationCollaboration\x12C\n" +
	"\x1eavg_problem_solving_initiative\x18\a \x01(\x01R\x1bavgProblemSolvingInitiative\x12\x1b\n" +
	"\thas_score\x18\b \x01(\bR\bhasScore\"@\n" +
	"\x12EnrichmentResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.search.EnrichmentDataR\x04data\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"g\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\acontent\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"Z\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.search.SearchResultR\aresults\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x02\n" +
	"\x16UpdateCandidateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12'\n" +
	"\x0feducation_major\x18\x05 \x01(\tR\x0eeducationMajor\x12\x10\n" +
	"\x03gpa\x18\x06 \x01(\x01R\x03gpa\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\b \x03(\tR\ttechStack\x12)\n" +
	"\x10years_experience\x18\t \x01(\x05R\x0fyearsExperience\"M\n" +
	"\x17UpdateCandidateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x17UpdateCVProgressRequest\x12\x13\n" +
	"\x05cv_id\x18\x01 \x01(\tR\x04cvId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"N\n" +
	"\x18UpdateCVProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x16DeleteCandidateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x17DeleteCandidateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf0\x01\n" +
	"\rSearchService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12R\n" +
	"\x0fUpdateCandidate\x12\x1e.search.UpdateCandidateRequest\x1a\x1f.search.UpdateCandidateResponse\x12R\n" +
	"\x0fDeleteCandidate\x12\x1e.search.DeleteCandidateRequest\x1a\x1f.search.DeleteCandidateResponse2\xc2\x02\n" +
	"\x10CandidateService\x12J\n" +
	"\x11GetEnrichmentData\x12\x19.search.EnrichmentRequest\x1a\x1a.search.EnrichmentResponse\x12C\n" +
	"\n" +
	"GetSectors\x12\x19.search.GetSectorsRequest\x1a\x1a.search.GetSectorsResponse\x12U\n" +
	"\x10UpdateCVProgress\x12\x1f.search.UpdateCVProgressRequest\x1a .search.UpdateCVProgressResponse\x12F\n" +
	"\vGetJobRoles\x12\x1a.search.GetJobRolesRequest\x1a\x1b.search.GetJobRolesResponseB\x1bZ\x19gigsourcehub-ai-api/protob\x06proto3"

var (
	file_proto_search_proto_rawDescOnce sync.Once
	file_proto_search_proto_rawDescData []byte
)

func file_proto_search_proto_rawDescGZIP() []byte {
	file_proto_search_proto_rawDescOnce.Do(func() {
		file_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)))
	})
	return file_proto_search_proto_rawDescData
}

var file_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_search_proto_goTypes = []any{
	(*GetJobRolesRequest)(nil),       // 0: search.GetJobRolesRequest
	(*JobRoleInfo)(nil),              // 1: search.JobRoleInfo
	(*GetJobRolesResponse)(nil),      // 2: search.GetJobRolesResponse
	(*GetSectorsRequest)(nil),        // 3: search.GetSectorsRequest
	(*SectorInfo)(nil),               // 4: search.SectorInfo
	(*GetSectorsResponse)(nil),       // 5: search.GetSectorsResponse
	(*EnrichmentRequest)(nil),        // 6: search.EnrichmentRequest
	(*EnrichmentData)(nil),           // 7: search.EnrichmentData
	(*EnrichmentResponse)(nil),       // 8: search.EnrichmentResponse
	(*SearchRequest)(nil),            // 9: search.SearchRequest
	(*SearchResult)(nil),             // 10: search.SearchResult
	(*SearchResponse)(nil),           // 11: search.SearchResponse
	(*UpdateCandidateRequest)(nil),   // 12: search.UpdateCandidateRequest
	(*UpdateCandidateResponse)(nil),  // 13: search.UpdateCandidateResponse
	(*UpdateCVProgressRequest)(nil),  // 14: search.UpdateCVProgressRequest
	(*UpdateCVProgressResponse)(nil), // 15: search.UpdateCVProgressResponse
	(*DeleteCandidateRequest)(nil),   // 16: search.DeleteCandidateRequest
	(*DeleteCandidateResponse)(nil),  // 17: search.DeleteCandidateResponse
	(*structpb.Struct)(nil),          // 18: google.protobuf.Struct
}
var file_proto_search_proto_depIdxs = []int32{
	1,  // 0: search.GetJobRolesResponse.job_roles:type_name -> search.JobRoleInfo
	4,  // 1: search.GetSectorsResponse.sectors:type_name -> search.SectorInfo
	7,  // 2: search.EnrichmentResponse.data:type_name -> search.EnrichmentData
	18, // 3: search.SearchResult.content:type_name -> google.protobuf.Struct
	10, // 4: search.SearchResponse.results:type_name -> search.SearchResult
	9,  // 5: search.SearchService.Search:input_type -> search.SearchRequest
	12, // 6: search.SearchService.UpdateCandidate:input_type -> search.UpdateCandidateRequest
	16, // 7: search.SearchService.DeleteCandidate:input_type -> search.DeleteCandidateRequest
	6,  // 8: search.CandidateService.GetEnrichmentData:input_type -> search.EnrichmentRequest
	3,  // 9: search.CandidateService.GetSectors:input_type -> search.GetSectorsRequest
	14, // 10: search.CandidateService.UpdateCVProgress:input_type -> search.UpdateCVProgressRequest
	0,  // 11: search.CandidateService.GetJobRoles:input_type -> search.GetJobRolesRequest
	11, // 12: search.SearchService.Search:output_type -> search.SearchResponse
	13, // 13: search.SearchService.UpdateCandidate:output_type -> search.UpdateCandidateResponse
	17, // 14: search.SearchService.DeleteCandidate:output_type -> search.DeleteCandidateResponse
	8,  // 15: search.CandidateService.GetEnrichmentData:output_type -> search.EnrichmentResponse
	5,  // 16: search.CandidateService.GetSectors:output_type -> search.GetSectorsResponse
	15, // 17: search.CandidateService.UpdateCVProgress:output_type -> search.UpdateCVProgressResponse
	2,  // 18: search.CandidateService.GetJobRoles:output_type -> search.GetJobRolesResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_search_proto_init() }
func file_proto_search_proto_init() {
	if File_proto_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_search_proto_goTypes,
		DependencyIndexes: file_proto_search_proto_depIdxs,
		MessageInfos:      file_proto_search_proto_msgTypes,
	}.Build()
	File_proto_search_proto = out.File
	file_proto_search_proto_goTypes = nil
	file_proto_search_proto_depIdxs = nil
}
