package usecase_activity_log

import (
	"bytes"
	"context"
	"encoding/csv"
	"net/http"
	"strconv"
	"strings"
	"time"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"
	"github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	"github.com/jung-kurt/gofpdf"
	"github.com/sirupsen/logrus"
	"github.com/xuri/excelize/v2"
)

func (u *appUsecase) FetchAll(ctx context.Context, page, limit int64, cursor string, filter gorm_model.LogActivityFilter) response.Base {
	ctx, cancel := context.WithTimeout(ctx, u.contextTimeout)
	defer cancel()

	limit64 := limit
	offset64 := (page - 1) * limit
	filter.Limit = &limit64
	filter.Offset = &offset64

	logs, err := u.gormDbRepo.FetchLogActivity(ctx, filter)
	if err != nil {
		logrus.Errorf("FetchAll ActivityLog error: %v", err)
		return response.Error(http.StatusInternalServerError, "failed to fetch activity logs")
	}

	total, err := u.gormDbRepo.FetchCountLogActivity(ctx, filter)
	if err != nil {
		logrus.Errorf("FetchCount ActivityLog error: %v", err)
	}

	var results []interface{}
	for _, log := range logs {
		actorName := "-"
		actorRole := "-"
		if log.Actor != nil {
			actorName = log.Actor.Name
			if log.Actor.SystemRole != nil {
				actorRole = log.Actor.SystemRole.Name
			}
		}

		results = append(results, map[string]interface{}{
			"id":          log.ID,
			"actor_id":    log.ActorID,
			"actor_name":  actorName,
			"actor_role":  actorRole,
			"action_type": log.ActionType,
			"module":      log.Module,
			"description": log.Description,
			"metadata":    log.Metadata,
			"ip_address":  log.IPAddress,
			"is_success":  log.IsSuccess,
			"created_at":  log.CreatedAt,
		})
	}

	var nextCursor *string
	if (page-1)*limit+int64(len(results)) < total {
		nextVal := strconv.FormatInt(page+1, 10)
		nextCursor = &nextVal
	}

	return response.Success(response.List{
		List:   results,
		Limit:  limit,
		Page:   page,
		Total:  total,
		Cursor: nextCursor,
	})
}

func (u *appUsecase) ExportData(ctx context.Context, filter gorm_model.LogActivityFilter, format string, actorID string) ([]byte, string, string, error) {
	ctx, cancel := context.WithTimeout(ctx, u.contextTimeout)
	defer cancel()

	// Adjust filter to fetch all relevant logs (no limit)
	limit64 := int64(10000)
	offset64 := int64(0)
	filter.Limit = &limit64
	filter.Offset = &offset64

	logs, err := u.gormDbRepo.FetchLogActivity(ctx, filter)
	if err != nil {
		return nil, "", "", err
	}

	headers := []string{"Timestamp", "Actor Name", "Role", "Action Type", "Module", "Description", "IP Address", "Status"}

	switch format {
	case "xlsx":
		f := excelize.NewFile()
		sheet := "Sheet1"
		f.SetSheetName("Sheet1", sheet)

		// Create header style
		headerStyle, err := f.NewStyle(&excelize.Style{
			Font: &excelize.Font{Bold: true, Color: "FFFFFF"},
			Fill: excelize.Fill{Type: "pattern", Color: []string{"0014B2"}, Pattern: 1},
			Alignment: &excelize.Alignment{Horizontal: "center"},
		})
		if err != nil {
			logrus.Errorf("failed to create header style: %v", err)
		}

		// Write headers
		for i, h := range headers {
			cell, _ := excelize.CoordinatesToCellName(i+1, 1)
			f.SetCellValue(sheet, cell, h)
		}
		f.SetRowStyle(sheet, 1, 1, headerStyle)

		// Freeze first row (Locked Header)
		f.SetPanes(sheet, &excelize.Panes{
			Freeze:      true,
			Split:       false,
			XSplit:      0,
			YSplit:      1,
			TopLeftCell: "A2",
			ActivePane:  "bottomLeft",
		})

		// Write data
		for r, log := range logs {
			rowIdx := r + 2
			data := u.extractLogData(log)
			for c, val := range data {
				cell, _ := excelize.CoordinatesToCellName(c+1, rowIdx)
				f.SetCellValue(sheet, cell, val)
			}
		}

		// Auto-fit columns
		f.SetColWidth(sheet, "A", "A", 20)
		f.SetColWidth(sheet, "B", "C", 20)
		f.SetColWidth(sheet, "D", "E", 15)
		f.SetColWidth(sheet, "F", "F", 50)
		f.SetColWidth(sheet, "G", "H", 15)

		var buf bytes.Buffer
		if err := f.Write(&buf); err != nil {
			return nil, "", "", err
		}
		return buf.Bytes(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx", nil

	case "pdf":
		// Fetch actor name
		actorName := "System"
		if actor, err := u.gormDbRepo.FetchOneUser(ctx, gorm_model.UserFilter{DefaultFilter: gorm_model.DefaultFilter{ID: actorID}}); err == nil && actor != nil {
			actorName = actor.Name
		}

		pdf := gofpdf.New("L", "mm", "A4", "")
		pdf.AddPage()
		
		// Title
		pdf.SetFont("Arial", "B", 18)
		pdf.SetTextColor(0, 20, 178) // #0014B2
		pdf.CellFormat(0, 10, "GigSource Hub Audit Log Report", "", 1, "C", false, 0, "")
		
		// Metadata Header
		pdf.SetFont("Arial", "", 10)
		pdf.SetTextColor(100, 116, 139) // Slate grey
		now := time.Now().Format("2006-01-02 15:04:05")
		pdf.CellFormat(0, 8, "Generated By: "+actorName+" | Generated At: "+now, "", 1, "C", false, 0, "")
		pdf.Ln(10)

		pdf.SetFont("Arial", "B", 10)
		pdf.SetFillColor(0, 20, 178) // #0014B2
		pdf.SetTextColor(255, 255, 255)

		colWidths := []float64{35, 30, 25, 25, 30, 80, 25, 20}
		for i, h := range headers {
			pdf.CellFormat(colWidths[i], 10, h, "1", 0, "C", true, 0, "")
		}
		pdf.Ln(-1)

		pdf.SetFont("Arial", "", 9)
		pdf.SetTextColor(0, 0, 0)

		for _, log := range logs {
			data := u.extractLogData(log)
			
			// Force wrap for columns that might have long unbroken strings
			data[1] = u.forceWrap(pdf, data[1], colWidths[1]) // Actor Name
			data[5] = u.forceWrap(pdf, data[5], colWidths[5]) // Description
			
			// Calculate max height for this row based on both Actor Name and Description after force wrapping
			linesActor := pdf.SplitLines([]byte(data[1]), colWidths[1])
			linesDesc := pdf.SplitLines([]byte(data[5]), colWidths[5])
			
			maxLines := len(linesActor)
			if len(linesDesc) > maxLines {
				maxLines = len(linesDesc)
			}
			
			rowHeight := float64(maxLines) * 5
			if rowHeight < 8 {
				rowHeight = 8
			}

			// Check for page break
			if pdf.GetY() + rowHeight > 180 {
				pdf.AddPage()
				pdf.SetFont("Arial", "B", 10)
				pdf.SetFillColor(0, 20, 178)
				pdf.SetTextColor(255, 255, 255)
				for i, h := range headers {
					pdf.CellFormat(colWidths[i], 10, h, "1", 0, "C", true, 0, "")
				}
				pdf.Ln(-1)
				pdf.SetFont("Arial", "", 9)
				pdf.SetTextColor(0, 0, 0)
			}

			x, y := pdf.GetX(), pdf.GetY()
			for i, val := range data {
				// 1. Draw the text content without internal borders
				pdf.SetXY(x, y)
				if i == 5 || i == 1 { // Wrap columns
					pdf.MultiCell(colWidths[i], 5, val, "", "L", false)
				} else {
					pdf.CellFormat(colWidths[i], rowHeight, val, "", 0, "L", false, 0, "")
				}

				// 2. Draw the single border box for the entire cell height
				pdf.SetXY(x, y)
				pdf.CellFormat(colWidths[i], rowHeight, "", "1", 0, "L", false, 0, "")
				
				x += colWidths[i]
			}
			pdf.SetY(y + rowHeight)
		}
		var buf bytes.Buffer
		if err := pdf.Output(&buf); err != nil {
			return nil, "", "", err
		}
		return buf.Bytes(), "application/pdf", "pdf", nil

	default: // CSV
		b := &bytes.Buffer{}
		w := csv.NewWriter(b)
		w.Write(headers)
		for _, log := range logs {
			w.Write(u.extractLogData(log))
		}
		w.Flush()
		return b.Bytes(), "text/csv", "csv", nil
	}
}

func (u *appUsecase) extractLogData(log gorm_model.LogActivity) []string {
	actorName := "-"
	actorRole := "-"
	if log.Actor != nil {
		actorName = log.Actor.Name
		if log.Actor.SystemRole != nil {
			actorRole = log.Actor.SystemRole.Name
		}
	}

	status := "Failed"
	if log.IsSuccess {
		status = "Success"
	}

	desc := "-"
	if log.Description != nil {
		desc = *log.Description
	}

	ip := "-"
	if log.IPAddress != nil {
		ip = *log.IPAddress
	}

	return []string{
		log.CreatedAt.Format("2006-01-02 15:04:05"),
		actorName,
		actorRole,
		log.ActionType,
		log.Module,
		desc,
		ip,
		status,
	}
}

func (u *appUsecase) forceWrap(pdf *gofpdf.Fpdf, text string, maxWidth float64) string {
	if text == "" {
		return "-"
	}

	// Use a small margin to be safe
	internalWidth := maxWidth - 4

	var result strings.Builder
	var currentLine strings.Builder

	// Split by space first to respect natural breaks, then force wrap long words
	words := strings.Split(text, " ")
	for i, word := range words {
		if i > 0 {
			currentLine.WriteString(" ")
		}

		// If the whole word fits, add it
		if pdf.GetStringWidth(currentLine.String()+word) < internalWidth {
			currentLine.WriteString(word)
		} else {
			// If adding the word overflows, we must break it or start a new line
			if pdf.GetStringWidth(word) > internalWidth {
				// Word itself is longer than the line -> Force character-wise break
				for _, r := range word {
					char := string(r)
					if pdf.GetStringWidth(currentLine.String()+char) > internalWidth {
						result.WriteString(currentLine.String() + "\n")
						currentLine.Reset()
					}
					currentLine.WriteString(char)
				}
			} else {
				// Word fits on a new line -> Move to next line
				result.WriteString(currentLine.String() + "\n")
				currentLine.Reset()
				currentLine.WriteString(word)
			}
		}
	}
	result.WriteString(currentLine.String())
	return result.String()
}
