package usecase_request

import (
	"bytes"
	"context"
	"encoding/csv"
	"time"

	gorm_model "github.com/adkurnwn/gigsourcehub-general-api/domain/model/gorm"
	"github.com/adkurnwn/gigsourcehub-general-api/domain/model/response"
	"github.com/jung-kurt/gofpdf"
	"github.com/xuri/excelize/v2"
)

func (u *appUsecase) generateExport(title string, description string, headers []string, data [][]string, format string, adminName string) ([]byte, string, string, error) {
	switch format {
	case "xlsx":
		f := excelize.NewFile()
		sheet := "Sheet1"
		f.SetSheetName("Sheet1", sheet)

		f.SetCellValue(sheet, "A1", title)
		f.SetCellValue(sheet, "A2", "Generated By: "+adminName)
		f.SetCellValue(sheet, "A3", "Filters: "+description)

		headerStyle, _ := f.NewStyle(&excelize.Style{
			Font: &excelize.Font{Bold: true, Color: "FFFFFF"},
			Fill: excelize.Fill{Type: "pattern", Color: []string{"0014B2"}, Pattern: 1},
			Alignment: &excelize.Alignment{Horizontal: "center"},
		})

		startRow := 5
		for i, h := range headers {
			cell, _ := excelize.CoordinatesToCellName(i+1, startRow)
			f.SetCellValue(sheet, cell, h)
		}
		f.SetRowStyle(sheet, startRow, startRow, headerStyle)

		f.SetPanes(sheet, &excelize.Panes{
			Freeze:      true,
			Split:       false,
			XSplit:      0,
			YSplit:      startRow,
			TopLeftCell: "A" + string(rune(startRow+1+'0')),
			ActivePane:  "bottomLeft",
		})

		for r, row := range data {
			rowIdx := r + startRow + 1
			for c, val := range row {
				cell, _ := excelize.CoordinatesToCellName(c+1, rowIdx)
				f.SetCellValue(sheet, cell, val)
			}
		}

		for i := 0; i < len(headers); i++ {
			col, _ := excelize.ColumnNumberToName(i + 1)
			f.SetColWidth(sheet, col, col, 20)
		}

		var buf bytes.Buffer
		if err := f.Write(&buf); err != nil {
			return nil, "", "", err
		}
		return buf.Bytes(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx", nil

	case "pdf":
		pdf := gofpdf.New("L", "mm", "A4", "")
		pdf.AddPage()

		pdf.SetFont("Arial", "B", 18)
		pdf.SetTextColor(0, 20, 178)
		pdf.CellFormat(0, 10, title, "", 1, "C", false, 0, "")

		pdf.SetFont("Arial", "", 10)
		pdf.SetTextColor(100, 116, 139)
		now := time.Now().Format("2006-01-02 15:04:05")
		pdf.CellFormat(0, 8, "Generated By: "+adminName+" | Generated At: "+now, "", 1, "C", false, 0, "")
		pdf.CellFormat(0, 8, "Filters: "+description, "", 1, "C", false, 0, "")
		pdf.Ln(5)

		pdf.SetFont("Arial", "B", 10)
		pdf.SetFillColor(0, 20, 178)
		pdf.SetTextColor(255, 255, 255)

		colWidth := 270.0 / float64(len(headers))
		for _, h := range headers {
			pdf.CellFormat(colWidth, 10, h, "1", 0, "C", true, 0, "")
		}
		pdf.Ln(-1)

		pdf.SetFont("Arial", "", 9)
		pdf.SetTextColor(0, 0, 0)

		for _, row := range data {
			if pdf.GetY() > 180 {
				pdf.AddPage()
				pdf.SetFont("Arial", "B", 10)
				pdf.SetFillColor(0, 20, 178)
				pdf.SetTextColor(255, 255, 255)
				for _, h := range headers {
					pdf.CellFormat(colWidth, 10, h, "1", 0, "C", true, 0, "")
				}
				pdf.Ln(-1)
				pdf.SetFont("Arial", "", 9)
				pdf.SetTextColor(0, 0, 0)
			}

			x, y := pdf.GetX(), pdf.GetY()
			maxLines := 1
			for _, val := range row {
				lines := len(pdf.SplitLines([]byte(val), colWidth-4))
				if lines > maxLines {
					maxLines = lines
				}
			}
			rowHeight := float64(maxLines) * 5
			if rowHeight < 8 {
				rowHeight = 8
			}

			for _, val := range row {
				pdf.SetXY(x, y)
				pdf.MultiCell(colWidth, 5, val, "", "L", false)
				pdf.SetXY(x, y)
				pdf.CellFormat(colWidth, rowHeight, "", "1", 0, "L", false, 0, "")
				x += colWidth
			}
			pdf.SetY(y + rowHeight)
		}

		var buf bytes.Buffer
		if err := pdf.Output(&buf); err != nil {
			return nil, "", "", err
		}
		return buf.Bytes(), "application/pdf", "pdf", nil

	default: // csv
		b := &bytes.Buffer{}
		w := csv.NewWriter(b)

		w.Write([]string{title})
		w.Write([]string{"Generated By", adminName})
		w.Write([]string{"Filters", description})
		w.Write([]string{}) // empty row

		w.Write(headers)
		for _, row := range data {
			w.Write(row)
		}
		w.Flush()
		return b.Bytes(), "text/csv", "csv", nil
	}
}

func (u *appUsecase) ExportRequests(ctx context.Context, filter gorm_model.RequestFilter, format string, adminID string) ([]byte, string, string, error) {
	adminName := "System"
	if admin, err := u.gormDbRepo.FetchOneUser(ctx, gorm_model.UserFilter{DefaultFilter: gorm_model.DefaultFilter{ID: adminID}}); err == nil && admin != nil {
		adminName = admin.Name
	}

	res := u.FetchByAdmin(ctx, 1, 10000, filter)
	if res.Status != 200 {
		return nil, "", "", nil
	}

	listData, ok := res.Data.(response.List)
	if !ok {
		return nil, "", "", nil
	}

	headers := []string{"Request No", "Project", "Proposed By", "Admin PIC", "Urgency", "Status"}
	var data [][]string
	for _, item := range listData.List {
		reqResp, ok := item.(gorm_model.RequestResp)
		if ok {
			proposedBy := "-"
			if reqResp.EmployeeName != nil {
				proposedBy = *reqResp.EmployeeName
			}
			adminPic := "-"
			if reqResp.AdminName != nil {
				adminPic = *reqResp.AdminName
			}

			data = append(data, []string{
				reqResp.ID,
				reqResp.ProjectName,
				proposedBy,
				adminPic,
				string(reqResp.Urgency),
				string(reqResp.Status),
			})
		}
	}

	return u.generateExport("Admin Requests Export", filter.GetDescription(), headers, data, format, adminName)
}
